### ISSUE TITLE
Mine expanding level bugs out

### ISSUE THREAD

**Issue by someaddons** [ldtteam/minecolonies#2849] opened 2018-09-04 06:40 UTC
### Minecolonies version

minecolonies-1.12.2-0.9.109-ALPHA-universal

### Actual behaviour

When you click on a mine level(in the miner's block's gui) to make a mineshaft out of it it caused ~6200 additional workorders to be added to the NBT workorders. After that minecolonies's event subscribers started lagging.

### Steps to reproduce the problem

1. Select a mineshaft level to build in the miners GUI
2. Check NBT for workorders(NBTExplorer)

[colonies-2018-09-03_20.43.10.zip](https://github.com/ldtteam/minecolonies/files/2347443/colonies-2018-09-03_20.43.10.zip)

**Comment by Raycoms** [comment] 2018-09-04 11:58
Wow that's weird, I tried it out but it didn't happen here.. hmm, I will improve the cleanup task

**Comment by Raycoms** [comment] 2018-09-04 12:03
Were you able to reproduce this several times?

**Comment by someaddons** [comment] 2018-09-04 16:10
deleted all those mine entries and tried again, but wasnt able to retrigger it. Working fine again for at least  ~1h

**Comment by Raycoms** [comment] 2018-09-04 16:18
Tell us if you find a way to trigger it, so we can debug it, it's quite
difficult to debug it if we can't reproduce it. Anyway these workOrders
shoudl clean itseld up after at least 1 done job as well

Am Di., 4. Sep. 2018 um 13:10 Uhr schrieb someaddons <
notifications@github.com>:

**Comment by someaddons** [comment] 2018-09-04 17:40
after playing ~3-4h it is back to 6484 workorders again, all I did after clearing the entries was go to the miner block and click randomly on a few levels.

**Comment by Paril** [comment] 2018-10-01 12:57
I managed to do this without ever touching the Miner's UI.
I built one of the Medieval mines, upgraded it to level 2, and eventually this just happened on its own.

**Comment by Raycoms** [comment] 2018-10-07 21:24
Should be fixed now.

**Closed as completed by Raycoms** 2018-10-07 21:24 UTC
Labels: Bug
