### ISSUE TITLE
Build Upgrade Options Crash

### ISSUE THREAD

**Issue by SeldomSpirit** [ldtteam/minecolonies#7937] opened 2022-01-14 06:09 UTC
Attached crash report.
Apparently when i click to update building it crashes, everytime, but was working fine yesterday.
[crash-2022-01-14_01.03.44-client.txt](https://github.com/ldtteam/minecolonies/files/7868191/crash-2022-01-14_01.03.44-client.txt)

**Comment by uecasm** [comment] 2022-01-14 06:47
Duplicate of ldtteam/Structurize#473

Either downgrade Forge to 39.0.17 or upgrade MineColonies to 1.18.1-1.0.349-ALPHA.

**Closed as completed by uecasm** 2022-01-14 06:47 UTC
Labels: Bug
