### ISSUE TITLE
Town Protection System  not working with Explosions.

### ISSUE THREAD

**Issue by Wissi** [ldtteam/minecolonies#663] opened 2017-02-28 05:08 UTC
The Town's protection system is not preventing the blocks from being destroyed by explosion.
The creepers explode and vanilla blocks break (modded blocks do not destroy).
Also when you "hang" a Citizen with a lead, he will "explode" and break blocks as well.

Apparently explosions are not prevented and blocks are being destroyed within Town's protected area.

**Comment by marvin-bitterlich** [comment] 2017-02-28 07:09
This definitely needs a log as we are preventing explosions pretty throughout.

**Comment by Wissi** [comment] 2017-03-02 19:42
"Unverified"? 
Do you need a server log? A client log? Just login to the Official server and BOOM! either a creeper of TNT player placed. 
Do you need more information from player side?

**Comment by marchermans** [comment] 2017-03-02 20:37
Yes i tried this myself, i could not reproduce it. Granted i tried this on client only. But i had no problems.
I will move it to verified as you say you can produce it on the official server then.

**Comment by Wissi** [comment] 2017-03-03 03:49
Yes, just login to the official server and you'll see. Not sure if it's a server side config or issue with the server side mod or spongeforge. All users complaining.

**Comment by Raycoms** [comment] 2017-03-03 14:30
@Kostronor might the config be wrong?

2017-03-03 0:49 GMT-03:00 Wissi <notifications@github.com>:

**Comment by gd71** [comment] 2017-03-05 18:52
Also happened on my server (also sponge) two times today with creepers with the last release minecolonies-universal-1.10.2-0.6.299.
Never seen before with previous minecolonies releases (but same sponge release)
I didn't catch any log for that

**Comment by Wissi** [comment] 2017-03-07 21:35
@Kostronor So.. since it wasn't an issue before... you think it might be a matter of a simple config that changed and can be reverted?

**Comment by gd71** [comment] 2017-03-26 09:06
A sponge issue have been fixed here : SpongePowered/SpongeForge#1364
Hopefully this will do the trick, I will test as soon as it will be released

**Comment by marvin-bitterlich** [comment] 2017-04-18 10:11
should be fixed

**Closed as completed by marvin-bitterlich** 2017-04-18 10:11 UTC
