### ISSUE TITLE
Hovering over an icon in EMI crafting menu selection screen causes crash

### ISSUE THREAD

**Issue by ncottrill** [ldtteam/minecolonies#10279] opened 2024-09-26 16:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.707

### Structurize Version

1.0.751

### Related Mods and their Versions

ATM 10 modpack 10-0.57

### Current Behavior

![image](https://github.com/user-attachments/assets/d729a753-ccf5-4748-b1d1-ace5102cbcef)

### Expected Behavior

The house image (in the yellow square) crashes the game when any of us hovers over it.

### Reproduction Steps

Play ATM 10 modpack version of Minecraft game
Open EMI (press E)
Hover over the house icon (shown in image)

### Logs

Dont have logs from this time

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment] 2024-09-26 17:15
Duplicate of #10276, and already fixed in the newest version of minecolonies

**Closed as completed** 2024-09-26 17:17 UTC
Labels: Bug
