### ISSUE TITLE
Problem with builder GUI and a full workers chest

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#793] opened 2017-04-10 12:17 UTC
It seems like if you fill the chest via worker GUI with the required materials. And his worker chest is full, the items go to the other chest of the builder (if available) but they don't get decreased in the GUI

**Comment by xavierh** [comment] 2017-04-10 12:39
Thanks for reporting it, will have a look at it

**Comment by xavierh** [comment] 2017-04-10 13:09
Weird as I am marking the building as dirty here https://github.com/Minecolonies/minecolonies/blob/version/1.11/src/main/java/com/minecolonies/coremod/network/messages/TransferItemsRequestMessage.java#L141
Will have to test.

**Comment by xavierh** [comment] 2017-04-16 13:21
I tested it on 1.11.2, I filled my chest with 1 torch per slot. then give some item using the buidler's gui. it does work perfectly well for me.

Only on 1.10.2 ?

**Comment by xavierh** [comment] 2017-04-16 14:40
Tested on 1.10.2 (without orion changes) and it does work as well. did you test since orion fixes ?

**Comment by xavierh** [comment] 2017-04-16 14:54
Tested with latest develop as from now, I can not reproduce, could you check that it is fixed ?

**Comment by marchermans** [comment] 2017-04-16 16:41
Yeah if it was not getting decreased because an NPE was triggered. It should be fixed now.

**Closed as completed** 2017-04-16 16:47 UTC
Labels: Bug
