### ISSUE TITLE
Weird tree recognition by the Lumberjack

### ISSUE THREAD

**Issue by Dragolance117** [ldtteam/minecolonies#5450] opened 2020-07-24 16:48 UTC
Hey dear developers of the amazing minecolonies mod!

This isn't really an annoying bug but just something I encountered while playing so I thought it would be useful to share with you.

I am playing on the Minecolonies Official v1.4 modpack for minecraft 1.15.2 .

I'm making a fancy looking tree farm around my Lumberjack's hut. I however noticed some weird logic in his tree-recognition programming (I think). My lumberjack does not recognize the following setup (scenario 1) as a tree.
![2020-07-24_18 15 08](https://user-images.githubusercontent.com/67859381/88414674-87eacd00-cddd-11ea-8709-9dc452abeabb.png)

He also does not recognize the next setup as a tree, the only difference being that I placed a grass block next to dirt where the tree is on (scenario 2). This setup would allow him to not get suck in scenario 3.
![2020-07-24_18 15 39](https://user-images.githubusercontent.com/67859381/88414689-8de0ae00-cddd-11ea-83d8-82de040fe55b.png)

When I tried the following setup, the woodcutter recognized the tree and walked towards it, however he could not stand on the grass block next to the tree (leaves were in the way) so he got stuck there and was unable to cut the tree down (scenario 3). He was able to cut the tree down when I removed the leaves that were in the way. 
![2020-07-24_18 26 31](https://user-images.githubusercontent.com/67859381/88414709-933df880-cddd-11ea-84b1-140920146100.png)

I'm assuming that this is the case since the lumberjack needs a dirt/grass block to stand on while cutting the tree down. This dirt/grass block then needs to be next to the tree and on the same elevation as the dirt underneath the tree.  

This isn't really something that needs to be fixed as I can work around it quite easily. I know that it's probably quite hard to code the lumberjack in such a way that he doesn't cut down all the houses in the colony (although this could be prevented by forcing the player to indicate a 'work area' when first building the lumberjack's hut, using the already implemented restriction option). 

Suggestion: Maybe it is possible to allow the lumberjack to cut down trees while standing on all types of blocks, perhaps even with a variable elevation difference, so that he doesn't need a dirt block next to the tree and on the same elevation to cut it down (solution to scenario 1, 2 and 3). And maybe you could allow the lumberjack to destroy leaves that are in his way, this would prevent getting stuck in scenario 3?

Thanks for looking at this and thanks a lot for this amazing modpack!
Have a nice day!

**Comment by Raycoms** [comment] 2020-07-24 17:34
It does work with a slab around the stump too for example, a lot of players use that. And yeah, it's not really possible to avoid that at the current moment. Finding trees is super difficult since a tree is literally a log on dirt with leaves around.

I'll close this since it works as intended and I described a decent workaround.

**Closed as completed by Raycoms** 2020-07-24 17:34 UTC

**Comment by Dragolance117** [comment] 2020-07-24 19:01
Slabs are a good suggestion! Thanks!
