### ISSUE TITLE
[BUG] The resident just disappears

### ISSUE THREAD

**Issue by Cklarkus** [ldtteam/minecolonies#10023] opened 2024-07-09 23:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.603-RELEASE

### Structurize Version

structurize-1.20.1-1.0.742-RELEASE

### Related Mods and their Versions

1. forge 47.2.21
2. blockui-1.20.1-1.0.156-RELEASE
3. domum_ornamentum-1.20.1-1.0.186-RELEASE-universal
4. multipiston-1.20-1.2.43-RELEASE

### Current Behavior

the resident just disappears, runs and runs and just disappears. It will only appear if you summon it again. . In the server console it says "[Server thread/WARN] [minecolonies/]: Citizen #1:4 has gone AWOL, respawning them!". It seems to happen with the defenders
Video example: https://www.youtube.com/watch?v=yGRa3-1YUMw

### Expected Behavior

n/a

### Reproduction Steps

n/a

### Logs

https://mclo.gs/V8XfCrb

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by cyberNinja6143** [comment] 2024-07-10 02:14
Did you try restarting the server?

**Comment by Cklarkus** [comment] 2024-07-10 02:17
> Did you try restarting the server?

Yes, I've tried restarting the server, recreating a new colony, a different version of minecolony. None of that helps.

**Comment by cyberNinja6143** [comment] 2024-07-10 05:22
I know why it's happening. In a rare case where the citizen is not present and it still has data the mod tries to respawn it. The issue is after respawning, it never registers the citizen so it is never marked as present. This causes the mod to keep respawning in an infinite loop. 

I was working on a fix but my Gradle stopped working. Ill try again tomorrow.

**Comment by cyberNinja6143** [comment] 2024-07-10 08:55
I was able to fix my gradle. I tired very hard to replicate your issue on my personal server but I was unable to. Maybe you are using an older version or it is possibly a mod conflict if you are using multiple mods.

![Screenshot 2024-07-10 015413](https://github.com/ldtteam/minecolonies/assets/132031796/4a4e01f7-863a-4996-b9ca-b68dea22a785)

It was very difficult to get one of the guard citizens out of bounds but after that it did not continue to respawn.

**Comment by Cklarkus** [comment] 2024-07-10 13:31
> I was able to fix my gradle. I tired very hard to replicate your issue on my personal server but I was unable to. Maybe you are using an older version or it is possibly a mod conflict if you are using multiple mods.
> 
> ![Screenshot 2024-07-10 015413](https://private-user-images.githubusercontent.com/132031796/347333065-4a4e01f7-863a-4996-b9ca-b68dea22a785.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTc5NjAsIm5iZiI6MTcyMDYxNzY2MCwicGF0aCI6Ii8xMzIwMzE3OTYvMzQ3MzMzMDY1LTRhNGUwMWY3LTg2M2EtNDk5Ni1iOWNhLWI2OGRlYTIyYTc4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQxMzIxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDliOWEwNDUwZWRhYzA4N2Y3ZWQxZDgzNWMxNWVkOGE0ZGY4OTUwYmUyN2ZhNmVhYjI3NWE4MjQ4NDYyZTI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NQAun99S-mV4idbvhoTfRM7kQv7KboBTS9jW7Yw2vnU)
> 
> It was very difficult to get one of the guard citizens out of bounds but after that it did not continue to respawn.

Probably really a mod conflict, too bad, impossible to find. Strange that it is the guardian that is unloaded from the world. I should try in singleplayer world, maybe something at the server level

**Comment by Talyda** [comment] 2024-07-10 22:05
> Probably really a mod conflict, too bad, impossible to find. Strange that it is the guardian that is unloaded from the world. I should try in singleplayer world, maybe something at the server level

Not impossible =) I know you have discord, so [you can check here](https://discord.com/channels/139070364159311872/377078011394260994/1260718324371951686), for the binary search method

**Closed as completed** 2024-08-09 10:59 UTC
Labels: Bug
