### ISSUE TITLE
Moobien's Bugs

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#5944] opened 2020-10-18 08:07 UTC
As per https://github.com/ldtteam/minecolonies-features/issues/174

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.352-ALPHA
- Structurize Version: 0.13.92-ALPHA
- Related Mods and their Versions:

1) I am getting a LOT of suffocation in wall notices for the Fortress Barracks. Image 1 is looking directly at the coordinates in the messages. same location every time.

2) Wood Warehouse. I love that you guys have incorporated DMen into the warehouse but I am notiicing that there is a LOT of congregating going on. Refer to Images 2-6, I tried blocking the lladder access to this lower section in the warehouse but I am still getting guards getting in there somehow. Most of the people in this lower section have been here for several days now, and even when using the rally banner the guards in here don't move.

3) Major issue here. children keep falling into the fire in the fortress restaraunt, only wat to stop this was to get rid of the fire. Image 15

4) Getting a lot of colonists saying there is no barracks or guard tower near them and yet they are maybe 30 block at most from a barracks.

5) I have noticed that colonists seem to get stuck on rails a lot. they kinda spin in place. its as though they have tried to dismount the minecart and got stuck. I have also noticed this behaviour without the rails research done.

6) I have noticed that in 1.16.3 if you set your graphics to the ultra fancy or whatever that mode is, the schematic preview is invisible.

https://imgur.com/a/8MNlFVp
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment] 2020-10-18 08:23
6 Yes, most mods have that problem. Not a bug. Just no compat.
5 Fixed
4 @someaddons 
3 #5006 
2 Fixed in latest
1 double issue

**Comment by Moobien** [comment] 2020-10-18 09:05
sorry the tavern, not the barracks has the suffocation issue

**Comment by Moobien** [comment] 2020-10-18 09:07
@Raycoms  #6 was me offering you guys my kelp farm, all vanilla and minecolonies parts.

**Comment by Raycoms** [comment] 2020-10-21 20:50
the rest should be fixed or treated in another issue now

**Closed as completed by Raycoms** 2020-10-21 20:50 UTC
Labels: Bug

**Comment by Moobien** [comment] 2020-11-02 15:19
Found another bug thats been around for a while. 

there is one 'issue' I have noticed but I don't know if its design or bug. when you paste in a town hall, regardless of level, it pastes the level you chose but the hut block is only level 0 so if you paste a lvl 2, and do a repair or even a build it tears it all down and builds the lvl 1 TH

**Comment by Moobien** [comment] 2020-11-02 15:20
@Raycoms ^^

**Comment by Raycoms** [comment] 2020-11-02 15:23
You can place it. Create the colony, and then paste the level you want. But the colony has to be created first
