### ISSUE TITLE
 Deliverman voiding fish when one half of a chest in the warehouse if full

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#644] opened 2017-02-21 15:44 UTC
### Minecolonies version

minecolonies-universal-1.11-0.6.2837

### Expected behavior

Deliveryman use entire chest, not half of a chest, and then use other empty chests when the main chest is full.

### Actual behaviour

http://imgur.com/mHawQSw
Deliveryman using half of the chest, and then voiding the extra fish.

**Comment by Raycoms** [comment] 2017-02-21 16:09
That's actually not a bug.
but we can discuss it for sure.

Atm all the chests are handled like "single chests".
Which, IMO, improves the sorting in most cases.

2017-02-21 12:44 GMT-03:00 ProsperCraft <notifications@github.com>:

**Comment by marchermans** [comment] 2017-02-21 16:25
I started working on the Deliveryman System now. I have added a note to its usecase study.
All relevant information can be found in issue: #638, Closing in favor for that issue and as this is not really a bug. Please continue discussing it in the mentioned Issue.

**Comment by Raycoms** [comment] 2017-02-21 16:39
Problem is that the items do disappear and don't go into other chests.
Something seems wrong with the "isChestFull" check most probably.

**Comment by psxlover** [comment] 2017-03-07 23:14
I run into this too, but with the logs. Even though there are a lot of empty chests in my warehouse, the only one that has Oak/Spruce/Jungle/Birch wood is on the lower half of a double chest which is completely full (the upper half still has room). Perhaps it is looking for space in the wrong "single chest" of the double chest.

**Comment by Raycoms** [comment] 2017-03-07 23:17
Does this happen only in 1.11 or also in 1.10?

2017-03-07 20:14 GMT-03:00 Alex Pap <notifications@github.com>:

**Comment by Raycoms** [comment] 2017-03-07 23:18
Nevermind, found the bug.

2017-03-07 20:17 GMT-03:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by Raycoms** [comment] 2017-03-07 23:32
You can test it here:
https://www.dropbox.com/sh/9cnqcjl0nan57cy/AABxuUuDgBzWlkWJAnkfnGrBa/branch/fix/%23644-%23679?dl=0&preview=minecolonies-universal-1.10.2-0.6.3062.jar

2017-03-07 20:24 GMT-03:00 Marvin Hofmann <notifications@github.com>:

**Comment by psxlover** [comment] 2017-03-07 23:33
I was about to ask why you were checking for "this" instead of "entity" in https://github.com/Minecolonies/minecolonies/blob/72186127d3458e4c020a1995b964e258e1a7559b/src/main/java/com/minecolonies/coremod/tileentities/TileEntityWareHouse.java#L411 but seems like you saw it already.

**Comment by Raycoms** [comment] 2017-03-07 23:43
Yeah, stupid copy paste xD

2017-03-07 20:33 GMT-03:00 Alex Pap <notifications@github.com>:

**Closed as completed** 2017-03-08 15:05 UTC
