### ISSUE TITLE
Colonists die in the morning

### ISSUE THREAD

**Issue by Lordbaane** [ldtteam/minecolonies#2132] opened 2018-02-01 22:19 UTC
minecolonies-universal-1.12.2-0.8.7312

### Expected behavior

- Go to sleep, wake up and find the colonists are okay

### Actual behaviour

- Lost 4 after the first morning saying they fell out of the world!

### Steps to reproduce the problem

1. Relogged in, lost the colonists
2. Keeps happening each night
3. ...
4. There dead Jim....

**Comment by figtito** [comment] 2018-02-02 04:15
Experiencing the same issue with 7312. Console says the fell out of the world.

**Comment by Araxidis** [comment] 2018-02-02 04:54
I have had exactly this same issue. Using the same version. Did not have that problem with .7281.

**Comment by marchermans** [comment] 2018-02-02 08:59
Yeah my fault. I added the sleep spawn logic and it falls back to 0,0,0 which is ofcourse under the bedrock.
Will push a fix today.

**Comment by ProsperCraft** [comment] 2018-02-02 16:06
Mine suffocate.

**Comment by Araxidis** [comment] 2018-02-02 16:13
> Mine suffocate.

Different issue. I believe this is caused because the colonists are now sleeping in the beds when they weren't before. So, if the house design doesn't take this into account, the stand up in the morning and get stuck in the walls. I fixed this problem by just removing the beds from the houses :P

**Comment by Justen-N** [comment] 2018-02-02 18:24
Arax, Marc pushed a fix for the suffocating issue that caused the current
issue. Are you using the most recent build?

**Comment by Araxidis** [comment] 2018-02-03 02:19
I know this post isn't about the suffocating but I do have the .7323 and my delivery guy died when he got out of bed. It was a level 3 alternative wood house. He was in the bed next to the house chest. The falling out of the world does, indeed, seem to be fixed though.

**Comment by Araxidis** [comment] 2018-02-03 03:25
Using 7323 and was dismayed to find this in the morning:
![image](https://user-images.githubusercontent.com/34173687/35762630-9be24dc4-085f-11e8-9085-b810bcc14adb.png)
They're all dead, Jim!

**Comment by nick-johnson** [comment] 2018-02-03 03:44
On 0.8.7323, still suffocate in walls.

**Comment by Lordbaane** [comment] 2018-02-03 19:59
I see the latest version after is out, I'm going to wait for the update that also addresses some of the other issues regarding the Baker. Though I don't seem to have the same issue regarding the smelter that was just posted.

**Comment by malkuth216** [comment] 2018-02-04 06:07
found that the same event is happening at start of day even if you don't sleep

**Comment by Boyownik** [comment] 2018-02-04 15:58
.7356 still colonists dying in the morning :/

**Closed as completed** 2018-02-04 16:10 UTC

**Comment by figtito** [comment] 2018-02-05 02:05
Colonists are still dying in the morning. I just updated to 7373 and the problem is still here.
