### ISSUE TITLE
[request/Feature] Custom Styles for Colonists [$5]

### ISSUE THREAD

**Issue by AndrewTru** [ldtteam/minecolonies#937] opened 2017-05-04 22:06 UTC
### Minecolonies version
1.11 on Twitch program

### Expected behavior

- the mod has an in game way to change the look of the colony members
- This has been 'talked' to be a pack with a override option to say if you like normal minecraft
or the modded in ones you get with the mod. the ones modded in more affect the female members
and not the men just saying.
- Pack creation and distribution will be transferred over to the Mod maker and team on completion of this bounty, I will try and help with the planning when possible. I just ask that I am informed about how the final idea is and where to find it.

### Actual behaviour
- current system can't work with changing of skin files.

### Steps to reproduce the problem
1. find skin files.
2. move provided skins outside folder
3. take another skin -EQG Rarity in my case.- and rename to the same name as the moved skin.
4. run minecraft and see if skin is used.
/\(may take some time, RNG will randomly pick the file used)
5. bug.
Photo of bug found at https://drive.google.com/open?id=0BwZHQkyU40dBX0ZtMGlVT0lBems

**Comment by AndrewTru** [comment] 2017-05-04 22:30
Just so you know the older version of the mod as well as the old mine colony mod had supported the above steps.
All I ask is why the above steps now are not working.

**Comment by Raycoms** [comment] 2017-05-05 00:14
That's strange. We didn't change anything there for a long while.

2017-05-04 19:30 GMT-03:00 AndrewTru <notifications@github.com>:

**Comment by AndrewTru** [comment] 2017-05-05 00:16
I take it you may need time to track down why this is happening?

**Comment by Raycoms** [comment] 2017-05-05 01:26
Probably, it would be very helpful if you could tell it in what version it
last worked.

2017-05-04 21:16 GMT-03:00 AndrewTru <notifications@github.com>:

**Comment by AndrewTru** [comment] 2017-05-05 01:28
Last I check it was when the mod was Mine colony in version 1.6.X this is the first time I have done it with this iteration of it.

**Comment by Raycoms** [comment] 2017-05-05 21:30
Oh that is really long ago, I guess this isn't working anymore because of minecraft itself.
@OrionDevelopment you know anything about textures?

**Comment by marvin-bitterlich** [comment] 2017-05-09 11:22
I'm posting a bounty on this one. @AndrewTru can you rework the issue to clearly state what needs to be done to improve the current situation?

**Comment by AndrewTru** [comment] 2017-05-09 12:03
for anyone who takes this bounty, I am currently looking at the chance for a skin system rework.
At the top of the issue thread you will find a link, that is the effect of customizing a skin with the current system, I will allow the collection of the bounty and end this issue if we can find a way to fix this effect.
I will be online as often as I can to reply to any questions you may have.
in other words, I like a way to add my own skins to the mod. that way a MLP version of the colony is not too far away. the skin is Rarity in a dress. nova.me is the site I used.
A skin/overlay patch if you will.
![settlerfemale2_mlp png](https://cloud.githubusercontent.com/assets/26558556/25849758/f8872e80-347c-11e7-9bc3-029975c49b48.png) here is the skin.png I used, and yes I know it's an overlay and not a true skin, found that out after I posted this issue. Yes, this may have just been user error but at the same time this wll just show where the mod and if needed minecraft itself can work on.

**Comment by Raycoms** [comment] 2017-05-09 12:08
Please note that some of our citizens use custom models.
That means that "general minecraft skins" won't work, especially not for
the female citizens.

2017-05-09 9:03 GMT-03:00 AndrewTru <notifications@github.com>:

**Comment by AndrewTru** [comment] 2017-05-09 12:10
@Raycoms I get that, the idea here is an in mod way to use that custom model to fix what was seen in the photo I gave at the start of this request, the one you marked as odd.

**Comment by AndrewTru** [comment] 2017-05-09 12:13
converter system or some like based code work, I know that you may not like to release the models themself but if the mod can 'lightly' do some of the work so the general minecraft skins can at least help paint a saved 'custom' model or two the core file stays but is painted to look like a skin you provide.
the overlay part is going to be a small issue in that regard but play the code just right and it will work out.

The idea is not to send out the models themselves but have some blank ones that the minecraft program can paint on to give the intended effect.

**Comment by Raycoms** [comment] 2017-05-09 12:16
The problem is with our custom models, there is no way we can detect if a
skin fits our custom model or not.
For the human I that's easy, but for the computer that's another story.
(Not my area of expertise as well).

What we can do:
- Config option to default all models to vanilla models.
- Then offer a way to load custom skins like a stylepack.

2017-05-09 9:13 GMT-03:00 AndrewTru <notifications@github.com>:

**Comment by AndrewTru** [comment] 2017-05-09 12:20
Let's do that, will you be providing the new packs or giving the player a pack maker?

**Comment by Raycoms** [comment] 2017-05-09 12:31
I'd suggest doing it like with the schematics.
Making a dedicated folder where the player can drop the styles of (named
accordingly).

2017-05-09 9:20 GMT-03:00 AndrewTru <notifications@github.com>:

**Comment by AndrewTru** [comment] 2017-05-09 12:36
That will work.
This folder will take any file or just a set type ( .jpg, .png,. style)?

**Comment by marchermans** [comment] 2017-05-09 13:50
Our textures are part of resourcepacks.
As long as the resource packs overloads minecolonies domain textures will be updated.

**Comment by AndrewTru** [comment] 2017-05-09 14:36
cool, Just checking. The style packs will be stored where?
in other words how will the player get the style packs into the folder
(downloaded as a resource pack, saved as a new file type, sent as part of the mod install as a .zip)

**Comment by marchermans** [comment] 2017-05-09 14:53
The textures are stored just like the vanilla textures. If you make a resource pack just like the way you make one for Minecraft but instead target minecolonies you will override its textures, langfiles, sounds etc

**Comment by AndrewTru** [comment] 2017-05-09 14:58
ah, got it.
I was just asking what the user will have to do to get the pack and point the minecraft install to it.
the back office I get, I am talking more the foregrounds.
asking as a user and not a coder.

**Comment by marchermans** [comment] 2017-05-09 17:34
Ah like any vanilla texturepack, you download it, put it in your texturepacks Folder, and selct it in the texturepacks Option in Minecraft. It will load the textures for you,

**Comment by AndrewTru** [comment] 2017-05-09 18:10
I take it the team will have a page on the Minecolonies site for the packs themselves?

**Comment by AndrewTru** [comment] 2017-06-25 02:25
@OrionDevelopment 
It seems I am not the only one looking into this, Issue #463 is looking into the system as well.

**Comment by AndrewTru** [comment] 2017-06-25 02:30
@Kostronor 
Another user is asking about the skin system, #463 and When I commented I by mistake closed this issue.
By the time I had reopened it the Help wanted tag was removed. Can you re-add the tag.
both this issue and the aforementioned one have a bounty on them.

**Comment by Raycoms** [comment] 2017-08-28 20:26
I think we can close this in favor of #463

**Closed as completed by Raycoms** 2017-08-28 20:26 UTC
Labels: Bounty
