### ISSUE TITLE
freetointeractblocks & autodeletecoloniesinhours configs don't seem to function

### ISSUE THREAD

**Issue by mahjerion** [ldtteam/minecolonies#6161] opened 2020-11-27 07:07 UTC
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.469-ALPHA-universal.jar
- Structurize Version: structurize-0.13.94-ALPHA-universal.jar
- Related Mods and their Versions: Waystones_1.15.2-6.0.2.jar, CalemiUtils-1.15-1.1.4-MC1.15.2.jar
- Forge Version: 31.2.45 <-- you guys should include this in your templates!

## Expected behavior

**freetointeractblocks** - by including interactable blocks from other mods they should be available to access even in claims.

**autodeletecoloniesinhours** - after 7 days, inactive colonies are removed.

## Actual behavior

**freetointeractblocks** - they just aren't interactable. Players have had to whitelist the specific coordinates but of course, this is finicky and also poses issues with newer players who just don't know about that.

**autodeletecoloniesinhours** - on the official CtE [Dissonance] servers, I've noticed that old colonies aren't deleting. I've double checked the configs. I notice that doing a '/mc colony info XX' shows that no matter which colony I check, the player was last seen 0 days ago (which of course, is not true - there are 100's of colonies).

Whitelist Config:
![image](https://user-images.githubusercontent.com/66142256/100420713-dee70400-3054-11eb-8cde-5459a2673336.png)

## Steps to reproduce the issue

1. Use same Forge version, MineColonies version, Waystones (most importantly), and config file.
1. See if they're interactable.

### Logs

No relevant logs, but here are my [config files](https://pastebin.com/U4zrjpK3).

### Notes

No notes, but thanks for the amazing mod. Pack wouldn't be the same without it!

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment] 2020-11-27 15:33
Duplicate of https://github.com/ldtteam/minecolonies/issues/6147

**Closed as completed** 2020-11-29 19:09 UTC
Labels: Bug
