### ISSUE TITLE
Game crashes whenever I open the "Fields" page of the Farm.

### ISSUE THREAD

**Issue by YoTroops** [ldtteam/minecolonies#8360] opened 2022-05-09 20:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

minecolonies-1.16.5-1.0.712-ALPHA

### Structurize Version

structurize-1.16.5-1.0.392-RELEASE

### Current Behavior

Whenever I go to my farm, and I open the "Fields" page, the game saves and quits, and crashes.

### Expected Behavior

I expected it to open the "Fields" page.

### Reproduction Steps

1. Go to the farm
2. Open the farm
3. Go to the fields page

### Logs

https://github.com/YoTroops/Crash/commit/c02643c84dfe9e1ba84e798ac46c9d803c453599

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by sgallaty** [comment] 2022-05-11 22:44
Also here in minecolonies-1.16.5-1.0.709-ALPHA

Not all fields.  100% reproducible when it is happening, happens in specific fields.

**Comment by MotionlessTrain** [comment] 2022-05-11 22:48
Just for the record, the crash also happens in 1.18.2 with Minecolonies 1.0.715 and blockui 0.0.47

**Comment by opmis** [comment] 2022-05-15 17:10
also in 1.16.5-1.0.729-Alpha, I believe it was working in 1.16.5-1.0.648-Alpha

**Comment by Thodor12** [comment] 2022-05-15 17:16
I simply cannot reproduce this, even on the exact mentioned version.

**Comment by Nightenom** [comment] 2022-05-15 17:18
@Thodor12 you can't pass null into settext, following method starts with null component and may end with return null
https://github.com/ldtteam/minecolonies/blame/version/main/src/api/java/com/minecolonies/api/util/BlockPosUtil.java#L714

**Comment by Thodor12** [comment] 2022-05-15 17:57
This should be resolved with #8376

**Closed as completed** 2022-05-16 06:36 UTC
Labels: Bug
