### ISSUE TITLE
Using Minecolonies Causes Crash? (logs)

### ISSUE THREAD

**Issue by ArkavianX** [ldtteam/minecolonies#7885] opened 2022-01-01 03:59 UTC
### Prerequisites 

- [MINEColonies Release and Structurize alpha]  I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context <

Minecraft 1.16.5
Forge 36.2.22
MineColonies 1.0.309
Structurize 0.13.252 Alpha - wasnt used

- Related Mods and their Versions: 
- ATM 6 Pack - updated this morning should be latest

## Expected behavior
1. To place the Supply Camp without buildtool -- game crash
2. Place using buildtool -- game crash
  * both crashes NO MODELS displayed just stall then crash
    
## Steps to reproduce the issue
Not sure, finished leveling a dirt area pad for placements when encountered error

- latest.log: https://gist.github.com/ArkavianX/164e6bd98b7fba2b15b141637690f8f4

- crashlog:  https://gist.github.com/ArkavianX/bdfbfab1f005fa1bc79945e12415f3b9

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Random832** [comment] 2022-01-02 10:12
This is caused by https://github.com/tasgon/observable/issues/23 and can be fixed by updating Observable.

**Closed as completed** 2022-01-02 10:14 UTC
Labels: Bug
