### ISSUE TITLE
Builder won't take items from builder hut chest

### ISSUE THREAD

**Issue by JumpySmudge** [ldtteam/minecolonies#2934] opened 2018-10-06 15:15 UTC
### Minecolonies version

Version:  minecolonies-1.12.2-0.9.141-ALPHA-universal.jar

### Expected behavior

Builder takes items from builder hut chest

### Actual behaviour

Need to fulfil request or give builder items manually. Builder won't take items out of the builder hut chest.

### Steps to reproduce the problem

1. Assign build job
2.  Place items builder hut chest using the resource list from the chest
3. Builder waits for requests to be fulfilled instead of taking items from chest, even it is the same item
4. ... Profit

**Comment by Nightenom** [comment] 2018-10-06 16:46
Duplicate of #2921

**Closed as completed by Nightenom** 2018-10-06 16:46 UTC
