### ISSUE TITLE
Tooltip and GUI Dont Match

### ISSUE THREAD

**Issue by Quest79** [ldtteam/minecolonies#10030] opened 2024-07-13 14:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.605

### Structurize Version

1.20.1-1.0.742

### Related Mods and their Versions

1. Forge 47.2.18
2. Block UI 1.20-1.2.43
3. Dom. 1.20.1-1.0.188

### Current Behavior

Tooltip and GUI order or items do not match. This is highly confusing as it not present in other areas of the mod. I made another ticket on the domum git as it has the same issue.

### Expected Behavior

I expect them to be in the same order. (there are only two!)

### Reproduction Steps

![javaw 071324 071138 🚆 1226x1066](https://github.com/user-attachments/assets/d9417c58-a50d-42d0-8173-714c2c4b4bbc)

### Logs

https://pastebin.com/dPWvvRRi

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment] 2024-07-13 17:05
Dupe of ldtteam/domum-ornamentum#244

**Closed as completed by Nightenom** 2024-07-13 17:05 UTC
Labels: Bug
