### ISSUE TITLE
Builders stop building/freeze

### ISSUE THREAD

**Issue by mackenziemay** [ldtteam/minecolonies#2284] opened 2018-03-03 02:06 UTC
### Minecolonies version

version 1.12.2-08.7582

### Expected behavior

- build anything thing

### Actual behaviour

- frozen in one spot not moving or asking for anything

**Comment by copperwarrior** [comment] 2018-03-03 02:06
Please update to the latest alpha and see if the issue persists

**Comment by mackenziemay** [comment] 2018-03-03 02:07
where do I find that?

**Comment by copperwarrior** [comment] 2018-03-03 02:09
https://minecraft.curseforge.com/projects/minecolonies

**Comment by mackenziemay** [comment] 2018-03-03 03:45
thank you!

**Comment by CringeCakes** [comment] 2018-03-16 16:58
The problem is still happening in the latest version (1.12.2-0.8.7809)

**Comment by Kisonu** [comment] 2018-05-30 07:30
issue happening with 0.8.8390 version as well.

**Comment by Raycoms** [comment] 2018-09-03 20:16
Should be fixed

**Closed as completed by Raycoms** 2018-09-03 20:16 UTC
