### ISSUE TITLE
Baker will not bake[BUG] <title>

### ISSUE THREAD

**Issue by Spacepilot99** [ldtteam/minecolonies#8659] opened 2022-09-20 16:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.889-RELEASE

### Structurize Version

structurize-1.18.2-1.0.411-ALPHA

### Current Behavior

The Baker will not bake any bread, I have set the fuel to only coal and given her a stack and put a stack in the hut block she has 5 stacks of wheat available to her I have tried giving her the items in her inventory and in the inventory or the hut block but she will not create bread dough or bread.
The only building that is requesting bread is the restaurant which is requesting one stack.
The bakery is a level 1 building, I have tried hiring different bakers, and repairing the entire structure.
There is a fuel request on the clipboard from the baker

Her behavior gets a little strange when I set a request for one stack of bread dough in the bakery, she takes three wheat out of the inventory then goes back into the wander animation, she gets to the front door and turns around, and runs back and puts the wheat back in the inventory, she then keeps repeating the same motion.

### Expected Behavior

use the wheat to make dough and then use the fuel to make bread.

### Reproduction Steps

level 1 baker.
level 2 restaurant 
5 stacks of wheat in baker's inventory
1 stack of coal in baker's inventory

### Logs

gist:22cec740317aacbbeda1a3278949c8d4 

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment] 2022-09-20 17:25
Could you try again on the latest alpha? You are about 140 versions behind

**Comment by Spacepilot99** [comment] 2022-09-21 17:36
Hi we have now updated to the latest version and she still acts the same way just wanders around

**Comment by Raycoms** [comment] 2022-09-21 17:37
Did tou

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by MotionlessTrain** [comment] 2022-09-21 19:18
Could you try putting the wheat in the warehouse instead?

**Comment by fahl17** [comment] 2023-06-05 15:06
I found a temporary fix for this. Fire and rehire the worker. You can also hire someone else and it'll work the same

**Comment by Raycoms** [comment] 2023-06-17 11:54
Does it have water bottles?

**Comment by Raycoms** [comment] 2023-06-17 13:15
I couldnt reproduce those issues

**Closed as completed** 2023-12-03 16:01 UTC
Labels: Bug
