### ISSUE TITLE
[BUG] <title>builder isnt finishing the warehouse, standard minecolonies pack

### ISSUE THREAD

**Issue by justfishingbruh** [ldtteam/minecolonies#9794] opened 2024-02-22 22:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20.1

### MineColonies Version

1.1.479-beta

### Structurize Version

1.1.479-beta

### Related Mods and their Versions

ATM9 - 0.2.51

### Reproduction Steps

i requested an upgrade to level 5 warehouse.
while he was building, he wants shingels that arent on the list, then he says
![image_2024-02-22_233221057](https://github.com/ldtteam/minecolonies/assets/160975029/22dbca04-a865-44ba-867a-80d57f97367a)

### Logs

https://pastebin.com/ALQHuHs3

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment] 2024-02-22 22:38
Duplicate of #9793

**Closed as not planned** 2024-02-22 22:51 UTC
Labels: Bug
