### ISSUE TITLE
Forge 36.2.22 breaks 1.16 minecolonies

### ISSUE THREAD

**Issue by WihdWiz** [ldtteam/minecolonies#7882] opened 2021-12-30 00:20 UTC
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16
- MineColonies Version: minecolonies-1.16.5-1.0.327-ALPHA
- Structurize Version: structurize-0.13.252-ALPHA-universal
- Related Mods and their Versions: Forge 36.2.22

## Expected behavior

Supply camp (or any building) blueprint showing
## Actual behavior

As soon as you right click with the supply camp in hand, the game crashes.
Whenever bypassing supply camp by manually crafting building tool and town hall, the same crash happens when right clicking with the building tool.

## Steps to reproduce the issue

1. Place any building/supply camp blueprint

### Logs

- latest.log: 
- crashlog: [] https://gist.github.com/WihdWiz/d520c1f1ed97f0c694d6e034b7d95d17

### Notes

When downgrading forge to 36.2.20, the issue is resolved.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by jeremiahwinsley** [comment] 2021-12-30 16:55
Looks like you are running ATM6 - this is probably a bug with Observable rather than Minecolonies. See https://github.com/tasgon/observable/issues/23

**Comment by tasgon** [comment] 2021-12-30 23:19
Sorry about that, it should be fixed in the newest version. I do find it interesting that downgrading Forge fixes the issue.

**Comment by PickleBurg** [comment] 2021-12-30 23:52
could you tell me which newest version this is? as experiencing same issue

**Comment by tasgon** [comment] 2021-12-31 00:00
https://www.curseforge.com/minecraft/mc-mods/observable/files/3586190

**Comment by PickleBurg** [comment] 2021-12-31 00:15
Solve the problem you smashed it!

**Comment by P-1000-ratte** [comment] 2021-12-31 01:32
I made sure that this issue is not a duplicate of any existing issue.
In version 1.12.2

**Closed as completed** 2021-12-31 07:07 UTC
Labels: Bug

**Comment by Moobien** [comment] 2022-01-01 09:08
> I made sure that this issue is not a duplicate of any existing issue. In version 1.12.2

1.12 is not supported in any way shape or form
