### ISSUE TITLE
[BUG] University Research crashes game

### ISSUE THREAD

**Issue by purpletiger6862** [ldtteam/minecolonies#9532] opened 2023-10-28 16:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.1.275-beta

### Structurize Version

1.0.661

### Reproduction Steps

1. open University block
2. click on research and choose a category
3. click anything, and the game will crash.

### Logs

https://gist.github.com/purpletiger6862/0b6a77394cf00c0b85d66df37861acec

### Anything else?

I'm using the official modpack through ATLauncher, and on the crash screen it claims that the crash was caused by 'UI library mod' which isn't in the mods list. 

I haven't had issues with any other building's blocks causing crashes, only the university. I just updated the modpack to the latest release.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment] 2023-10-28 16:22
Duplicate of #9531 
(UI library mod is another name of BlockUI)

**Closed as completed** 2023-10-28 16:34 UTC
Labels: Bug
