### ISSUE TITLE
Number of plantables in flowershop not working as intended

### ISSUE THREAD

**Issue by d34thii** [ldtteam/minecolonies#5062] opened 2020-05-23 13:21 UTC
Version: minecolonies-1.15.2-0.11.948-universal

### Expected behavior
Deactivate a number of plantables in relation to hut level.

### Actual behaviour

Currently my hut is lvl 3 (tho it was the same issue with hut lvl 2), but when I try to deactivate more than one plantable I get following error:
`"You can deactivate max 5 options. Upgrade to level 5 to restrict it further!"`

[Example image](https://imgur.com/a/a3oGgAU)

As seen in the image I only disabled sugar cane, tho when I try to disable anything else, I get the message mentioned above. It also happens, when I activate sugar cane again and diable something else.

### Steps to reproduce the problem

Deactivate more than 1 plantable in the flower shop

**Comment by Raycoms** [comment] 2020-05-23 13:25
yeah, its intended behavior, just the message is off. Someone has to fix the message to only say this at level 4 (at level 4 you can deactivate 5 options, before that only 1)

**Comment by PowerSchill** [comment] 2020-05-25 00:24
@Raycoms want to assign this to me and I will take a look at it.

**Comment by Asherslab** [comment] 2020-05-25 00:27
apparently i can't github

**Comment by d34thii** [comment] 2020-05-25 05:04
@PowerSchill If you don't mind, I started on it when I posted it and wanted to finish it today ^^

**Comment by Asherslab** [comment] 2020-05-25 05:31
probably a good idea to say that you're working on stuff in the future

**Comment by SirSmuggler** [comment] 2020-05-25 08:03
Would it be possible to dynamicaly adjust the number of dissables you can have relative to the number of avalible flower types? Would be usefull when playing with other mods that add a lot of new flowers. So you could disable a % of all avalible flowers instead of a fixed number?

**Comment by Raycoms** [comment] 2020-05-25 08:05
This amount is on purpose even with modded flower types =D

**Closed as completed** 2020-05-25 11:41 UTC
Labels: Good First Issue
