### ISSUE TITLE
[Feature] [$10] Rebuild Mineshafts

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#592] opened 2017-02-14 18:01 UTC
One of our players on the Prospercraft hosted version of the Elf Pack, had a fire break out in their mineshafts. Since there currently no way to get the Miner to rebuild those mineshafts, it was suggested that a feature be added the Miner to cause him to rebuild them when requested to do so.

**Comment by Raycoms** [comment] 2017-02-14 18:10
I think we can close this.
If you remove all the ladders but the upper 3 one will cause him to rebuild it completely.
(Will need a while but it will work)

**Comment by marvin-bitterlich** [comment] 2017-02-14 18:25
I think this could be a neat feature. Like a button: "Delete Level" and "Delete All"
there were multiple times where that would be needed.

**Comment by Wissi** [comment] 2019-02-13 05:15
@Raycoms @reggaemuffin Per your last comment:

> I think this could be a neat feature. Like a button: "Delete Level" and "Delete All"
there were multiple times where that would be needed.

Does this still need to be open?
I'll close and you guys decide if needed to be open and comment.

**Comment by Nightenom** [comment] 2019-02-13 07:52
This is a good idea, the problem is that it's a low priority feature

**Comment by Raycoms** [comment] 2020-03-30 14:11
Closed in favor of joint issue.

**Closed as completed by Raycoms** 2020-03-30 14:11 UTC
Labels: Bounty
