### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by Leppho** [ldtteam/minecolonies#8597] opened 2022-08-29 21:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.988

### Structurize Version

1.19.2-1.0.437

### Related Mods and their Versions

Forge ver. - 1.19.1
blockui-1.19-0.0.60-ALPHA
domum_ornamentum-1.19-1.0.59-ALPHA-universal
multi-piston-1.19-1.2.16-ALPHA

### Reproduction Steps

1. make a guard tower building
2. Hire a guard
3. give the guard a sword
4. guard AI breaks and asks me to send the latest.log
![image](https://user-images.githubusercontent.com/112436790/187303544-e7aa240d-a535-485e-b0de-7e883c07eab8.png)

### Logs

https://gist.github.com/Leppho/3902143514f61725f46f5d0d2378ff5a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment] 2022-08-29 21:49
Duplicate of #8589, not a minecolonies bug but one (that is supposedly fixed) in mahoutsukai.
Moreover, we cannot give support to users using cracked clients

**Closed as completed** 2022-08-30 16:39 UTC
Labels: Bug
