### ISSUE TITLE
/minecolonies resetsupplies, is not working

### ISSUE THREAD

**Issue by CriswellCodes** [ldtteam/minecolonies#4080] opened 2019-11-16 17:46 UTC
### Minecolonies version

Version:  Minecolonies	H3lay	minecolonies-0.10.547-ALPHA-universal.jar

### Expected behavior

I would expect that an Operator can reset the supply ship or camp of another player using the command appropriately.

### Actual behaviour

Join a game and Op yourself. Then try to reset the supply camp or ship of another player. Nothing occurs. Try as an Op to reset your own and it works successfully. At the moment a player can only reset their own camp while they are Op'd which would require Op permissions to be given to any player looking to reset their supplies.

Would love to see this command work where a Op can reset the camp/ship of any player on the server when needed.

### Steps to reproduce the problem

1. Join a server with 2 or more people online
2. Op yourself
3. Reset your supply camp (this will work)
4. Attempt to reset a different players supply camp (This won't work)
5. Mission complete, GG

**Comment by CriswellCodes** [comment] 2019-11-16 17:49
crosslinked to World of Dragons - New Age issue tracker
https://github.com/kreezxil/World-of-Dragons-A-New-Age/issues/63

**Comment by kreezxil** [comment] 2019-11-17 18:22
@Raycoms has this been addressed yet?

**Comment by someaddons** [comment] 2019-11-17 19:51
tested, can't reproduce it locally. One player is op, one isnt and I run the reset command and the nonop gets a message that his camp has been reset

**Comment by CriswellCodes** [comment] 2019-11-24 00:12
Any logs that I can provide from the server that might demonstrate the issue?

**Comment by Darkere** [comment] 2019-11-30 19:09
Seems like it does display the message but doesn't actually allow the player to set down a new camp

**Comment by Raycoms** [comment] 2020-01-06 20:51
Should be fixed

**Closed as completed by Raycoms** 2020-01-06 20:51 UTC
Labels: Bug: Can't Reproduce
