### ISSUE TITLE
Two problems without much consequence

### ISSUE THREAD

**Issue by ArturilloD** [ldtteam/minecolonies#6373] opened 2021-01-08 12:14 UTC
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.437-RELEASE-universal.jar
- Structurize Version: structurize-0.13.96-ALPHA-universal.jar
- Related Mods and their Versions: TerraForged-1.16.4-0.2.0-BETA-7.jar, OptiFine_1.16.4_HD_U_G5.jar and worldedit-forge-mc1.16.3-7.2.1-dist.jar

## What happens
<! - What's happening? ->
1.- What happens is that they go to sleep but you have to approach them so that they get up, otherwise they fall asleep.
2.- That the builders have tools in the inventory with a use or not used and they keep asking for a new one.

## Expected behavior

1.- That they get out of bed without having to go to all the houses in the village.
2.- That they did not ask for tools still having available in the inventory or in their cabin.

## Actual behavior

1.- Being about 50 blocks from the bed, the villager remains lying down and does not get up, unless one approaches about 15 blocks or less from the bed, then they get up and go to their work station.
2.- They go to their work station and ask for tools, they wait there until you take the tool from the inventory and give it to them again, when doing that it seems that they detect as if you gave them a new one, whether or not it is in perfect condition .

## Steps to reproduce the issue

1.- Villagers don't get up
     1. <! - Do this -> Stay about 50 blocks from a villager's bed, wait for daylight, sleep, or daylight command. You will see that or those villagers who are those 50 blocks away never get up and go to their work station.
     2. <! - And then this -> Now get closer to about 10 or 15 blocks from the bed / s of those villagers.
     3. <! - For this to happen -> And then they will get up and go to work.

2.- Builders ask for tools
     1. <! - Do this -> Give a tool to a builder when asked.
     2. <! - And then this -> Wait a while for the town or at the job of the builder.
     3. <! -For this to happen-> The builder will sometimes return to his job after a while and will ask him again for a tool without having consumed the previous one, sometimes when he only spent one use.

### Logs

- latest.log:  There is not
- crashlog:  There is not

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MatthiasMann** [comment] 2021-01-08 12:29
Issue 1 is caused by Optifine's chunkloading/entity optimization

**Comment by ArturilloD** [comment] 2021-01-08 12:50
Oh my, I didn't fall for that. Do you know if there are any settings that could fix it?

**Comment by Raycoms** [comment] 2021-01-08 12:51
And 2 is fixed in the latest alpha. It's lazy chunk loading the name of the setting

**Closed as completed by Raycoms** 2021-01-08 12:51 UTC
Labels: Bug
