### ISSUE TITLE
Schematic Issues

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#4536] opened 2020-03-30 15:02 UTC
This issue is for all schematic issues. If you have any issues with the schematics/building styles, please post them here.

- [ ] Update/Fix Medieval Alternate Styles

**Comment by PasixTheValkyrie** [comment] 2020-03-31 18:54
Hello, do excuse me if this is a wrong post, but I was told #4434 was fixed. I just happily logged on to try it (The server was updated prior) and I am still unable to upgrade walls. The same issue still persists

**Comment by Raycoms** [comment] 2020-03-31 18:58
Right place to post here. I'll undo the check. @lunadragnstar will take are of it as soon as she gets to it =)

**Comment by lunadragnstar** [comment] 2020-04-01 00:18
I am still running tests, and once everything is tested, I'll get them all rescanned and uploaded.

**Comment by basboy1743** [comment] 2020-04-02 12:42
what are the requirements for the custom buildings?
I have watched the videos but couldn't find a list

**Comment by lunadragnstar** [comment] 2020-04-02 15:52
I've added the requirements to the wiki https://wiki.minecolonies.com/source/tutorials/schematics

**Comment by basboy1743** [comment] 2020-04-02 16:30
> I've added the requirements to the wiki https://wiki.minecolonies.com/source/tutorials/schematics

but do the builds have specified block that they need

**Comment by lunadragnstar** [comment] 2020-04-02 21:34
custom huts need the required hut block and the required items from the list.

**Comment by basboy1743** [comment] 2020-04-03 10:26
but I can only find the names where is the list for te required items

**Comment by ToMe25** [comment] 2020-04-03 18:33
The medivaldarkoak type of some huts is the medivaloak type, meaning it uses oak wood for everything it uses wood for, instead of dark oak wood.

List of affected buildings(i didn't test all i just list the ones i noticed on in a survival world):
Citizens Hut,
Bakery,
Builders Hut,
Lumberjack,
Farm and 
Townhall.

**Comment by ToMe25** [comment] 2020-04-03 18:33
I suggest adding a Crafting Table to the Supply Camp either between the Composter and the closest Rack or in continuation of the line with the two double racks and the Furnace.
For the Supply Ship i would suggest adding a Crafting Table and a Furnace next to the Composter.

**Comment by lunadragnstar** [comment] 2020-04-03 19:26
we did not add a crafting table to the supply camp because you need a crafting table to make the supply camp so you already have one. Personally, I just move mine into the camp.

**Comment by lunadragnstar** [comment] 2020-04-03 19:26
@basboy1743 the list of requirements is below the names list

**Comment by ToMe25** [comment] 2020-04-03 19:35
I found myself moving the camp far away from a base i already had and always forgetting the crafting table when going there, making me walk a lot of time to my base and back, but maybe that's a rare thing and doesn't happen to many people.

**Comment by Akjosch** [comment] 2020-04-04 07:33
I'm not sure if I should make a separate issue for this or add this to "combined" one.

Version: 0.11.790-ALPHA for 1.15.2 (part of TechColonies 2.0 modpack)

A lot of schematics have leaves with `persistent: false` block state on them, leading to those parts decaying after a while. Affected schematics are at least:

* decorations: roads/fancy and roads/nice
* The "dark oak" style of buildings

**Comment by lunadragnstar** [comment] 2020-04-04 07:40
@Akjosch I will be updating the dark oak soon, hopefully that helps

**Comment by ToMe25** [comment] 2020-04-06 08:27
In version 0.11.810-BETA the "Spacewarssupplycamp" exists twice, once under that name and once with the name "Spacewarsupplycamp".

**Comment by gerb82** [comment] 2020-04-08 14:24
Dark Oak Barracks do not rotate their towers with them, leading to the towers building themselves into the barracks in any but one rotation.
Dark Oak Barracks also don't rotate their armor stands with them leading to some weird rotations with those.

**Comment by official-markus-maurer** [comment] 2020-04-11 00:45
> I'm not sure if I should make a separate issue for this or add this to "combined" one.
> 
> Version: 0.11.790-ALPHA for 1.15.2 (part of TechColonies 2.0 modpack)
> 
> A lot of schematics have leaves with `persistent: false` block state on them, leading to those parts decaying after a while. Affected schematics are at least:
> 
> * decorations: roads/fancy and roads/nice
> * The "dark oak" style of buildings

Had that issue with max lvl medieval spruce townhall & Oak Cook at max, refering to the leaves decaying.

**Comment by Charismara** [comment] 2020-04-12 10:07
The Nordic Florist schematic do some weird things.
![Download](https://user-images.githubusercontent.com/14293974/79066131-abb65700-7cb5-11ea-8f38-e75427caaf42.png)
![Screenshot_1](https://user-images.githubusercontent.com/14293974/79066174-12d40b80-7cb6-11ea-9dee-377bd1b74f52.png)
![Screenshot_2](https://user-images.githubusercontent.com/14293974/79066175-149dcf00-7cb6-11ea-864f-60cfc12af43e.png)

**Comment by Anesos** [comment] 2020-04-12 23:10
Just wanted to drop a note that I ran into the decoration controller block issue with
Decorations / walls / fortress / wall3 on minecolonies-0.11.810-BETA-universal. 

Wall 3 was requested, wall 1 was built. No upgrade or Repair button available on one of the wall sections, Repair, but no Upgrade option on the other one rotated 90 degrees.

**Comment by kd5crs** [comment] 2020-04-13 20:21
@lunadragnstar Dark Oak Guardtower Level 2 requires a Sea Lantern. Unless the intent is to make it super difficult, it would be in keeping with the other Level 2s and 3s if it was a redstone lantern instead. Thanks.

**Comment by lunadragnstar** [comment] 2020-04-14 03:41
@JNoppers the walls should be fixed

**Comment by lunadragnstar** [comment] 2020-04-14 04:03
@Charismara I've fixed the florist and it should be in the next update

**Comment by lunadragnstar** [comment] 2020-04-14 04:10
@kd5crs Fixed lantern issue

**Comment by lunadragnstar** [comment] 2020-04-14 04:39
@Anesos I think you have an old version of the mod that wasn't working at the time. it is setup properly now, or should be.

**Comment by ToMe25** [comment] 2020-04-14 16:48
The nordic citizen hut has one of the cobblestone stairs at the edge of the roof being upside down in all 5 levels of the building, as can be seen here:
![2020-04-14_18 46 03](https://user-images.githubusercontent.com/38815969/79251369-57130780-7e80-11ea-8d11-92b811da5058.png)

**Comment by ToMe25** [comment] 2020-04-14 18:07
also it seems like the nordic deliveryman building is missing the spruce slabs on the right(when looking at the building from the side with the door) top most part of the roof, in all 5 schematics.

**Comment by kd5crs** [comment] 2020-04-14 18:54
@lunadragnstar My apologies if you are already on it, but I see you fixed the Dark Oak Guardtower Level 2 in 1.12, but the Sea Lantern is in 1.15 too. Checked in minecolonies-0.11.827-ALPHA-universal. Thanks.

**Comment by ToMe25** [comment] 2020-04-14 19:03
I am not a 100% sure, but shouldn't there be two cobblestone blocks instead of spruce planks as part of the roof in the center of the image like on the other end of the roof?
![2020-04-14_21 01 51](https://user-images.githubusercontent.com/38815969/79263490-36a07880-7e93-11ea-90d7-9cbe302efc1b.png)
Edit: This is the level two nordic Warehouse.

**Comment by lunadragnstar** [comment] 2020-04-14 21:28
@ToMe25 I fixed the citizen, and warehouse, but I don't see an issue with the deliverymen, can you get me a screenshot?

**Comment by lunadragnstar** [comment] 2020-04-14 21:29
For anyone that is dealing with schematic issues, feel free to connect to our discord server, we also have a schematics channel on that where you can send me issues you find.

**Comment by ToMe25** [comment] 2020-04-15 08:15
First of, here is a screenshot if the problem, i did remove the two cobblestone stairs at the end to make this image possible with both ends visible, i didn't change anything else tho.
Second, i asked in the discord where to report bugs, and they told me on github was the prefered place for bug reports, so i just assumed the same is true for schmatic stuff.
![2020-04-15_10 06 09](https://user-images.githubusercontent.com/38815969/79314018-7e5de900-7f01-11ea-9cc8-7730f87fa8f9.png)
on this image its hard to see this small, but when scaling the image up its easy to see that one side has a row of spruce slabs at the top, and the other one doesn't.

**Comment by lunadragnstar** [comment] 2020-04-15 09:36
Oh ok, I'll get that fixed and you can absolutely post here, I was just saying that you can post in discord as well.

**Comment by GamertechAU** [comment] 2020-04-20 06:34
Starting an upgrade to the level 3 Fortress-type Barracks causes the builder to stop work and spam an error in the logs.

> [16:25:50] [Render thread/INFO]: [CHAT] Builder Gabriel J. Atherton Started building barracks3
> [16:26:18] [Render thread/ERROR]: ########## GL ERROR ##########
> [16:26:18] [Render thread/ERROR]: @ Render
> [16:26:18] [Render thread/ERROR]: 65539: Invalid key 0
> [16:26:22] [Render thread/ERROR]: ########## GL ERROR ##########
> [16:26:22] [Render thread/ERROR]: @ Render
> [16:26:22] [Render thread/ERROR]: 65539: Invalid key 0
> [16:26:25] [Render thread/ERROR]: ########## GL ERROR ##########
> [16:26:25] [Render thread/ERROR]: @ Render
> [16:26:25] [Render thread/ERROR]: 65539: Invalid key 0

Minecolonies: 0.11.840-BETA to 0.11.852-ALPHA

**Comment by Nightenom** [comment] 2020-04-20 07:22
@Gamertech 99.9% that isn't a schematic fault, it's something wrong with a keybinding from a completely different mod (since minecolonies nor structurize don't have any keybindings)

**Comment by GamertechAU** [comment] 2020-04-20 09:27
Thought so, but the error only started about the same time as I first tried to construct the fortress T3 barracks.

Either way, the builder still refuses to even leave his hut to start the upgrade. He just stands in front of his hut block until it's night time, then when day again he goes straight back to his hut.

He doesn't even pull out the blocks needed for the build which are all fulfilled and sitting in the hut racks.

The pack is Enigmatica 5 btw.

**Comment by Raycoms** [comment] 2020-04-20 09:28
Anything in the log?

**Comment by GamertechAU** [comment] 2020-04-20 09:39
Only the above. There's a whole lot of recipe exceptions and loot table errors in the logs, but all other mods. Nothing that affects Minecolonies or building blocks.

**Comment by kd5crs** [comment] 2020-04-21 02:25
Dark Oak Citizen Level 3 does not place the 3rd bed. You can find the bed entity floating to be picked up in the area, so I think it gets placed and then broken. Is this why some of my people are saying they haven't slept in 3 days? Thanks.

**Comment by lunadragnstar** [comment] 2020-04-23 07:29
All issues fixed,

**Comment by TheKrowi** [comment] 2020-04-23 15:15
### Minecolonies version
Version: minecolonies-1.12.2-0.11.811-BETA-universal
Modpack: MC Eternal 1.3.5.3

### Description
Is it possible the level 5 stone restaurant has a missing wall? Building it does indeed miss the wall so it's not only the preview.
![2020-04-23_15 33 25](https://user-images.githubusercontent.com/22818581/80105139-6ed14680-8578-11ea-9302-2e87d85c2a18.png)
![2020-04-23_15 37 11](https://user-images.githubusercontent.com/22818581/80105141-6f69dd00-8578-11ea-9297-425271c443d5.png)

**Comment by bbbower** [comment] 2020-04-24 20:24
Minecolonies version
Version: minecolonies-0.11.827-ALPHA-universal
Pack; Jnem2 .6.0 (1.15.2)

Expected behavior
Should use player head, or any head.
After research buildings should be build-able.

Trying to upgrade the university (fortress) to level 4 requires a player head.
Trying to build stone smelter / smeltery after researching appropriate research to unlock.

Actual behaviour
When given a head of any kind including player's builder continues to request it and does not reckognize it as the item he needs.
When trying to build buildings stone smeltery and smeltery after researching gives generic message to build university and unlock barracks.
![unknown](https://user-images.githubusercontent.com/15827105/80253885-21240f00-8648-11ea-88c3-ada3cdce3585.png)

**Comment by b52src** [comment] 2020-04-25 02:04
### Minecolonies version


Version: 
minecolonies-0.11.872-ALPHA-universal.
### Expected behavior


-  when you build on the barracks tower to the barrics that it matches up correctly they end up getting built rotated

### Actual behaviour


-  When you build the barracks towers they end up being rotated 90 degrees and do not match the build. I am using the Asian Style and the entrance of my Barracks is facing South. on my barracs for example the tower on my south west corner ends up having the entrance facing West Rather than North

- another issue i have seen on repositioning builds is when rotating the it dose not end up being built in the repositioned location  and puck a different orientation than what you selected, if needed i can open a separate issue ion that though


Will add a screen shot one i rebuild one of the towers.
### Steps to reproduce the problem


1.  hit build on one of the barracks towers 
2.  Once built the tower is facing 90 degrees in the wrong direction so the walls also do not align correctly as well.

screenshot: [https://i.imgur.com/nF0A0pz.jpg](https://i.imgur.com/nF0A0pz.jpg

**Comment by kd5crs** [comment] 2020-04-26 06:32
minecolonies-0.11.881-ALPHA-universal, Fortress style has at least 2 building rotation problems. I saw it on the Fisherman and the Restaurant. 

To reproduce: line up the Fisherman or Restaurant with how you want them built. Click the green check mark. The tape layout shows that the building has been rotated from its intended placement. I confirmed that it isn't just the tape layout that is wrong, the tape accurately shows the building location. It is like the rotation changes 90 degrees when the check mark is clicked.

This is new since the last time I tried a Fortress, which was around March 22nd.

**Comment by royalcw** [comment] 2020-04-26 06:53
It isn't just with those blocks.  The Dark Oak Cook has the issue, All the Asian style blocks as well.  They will orient North/South only but not East/West.  Manually placing the blocks without the tools still results in only North/South orientations.  The core block is rotated to the desired orientation, it is the rest of the building that doesn't orient.

**Comment by ToMe25** [comment] 2020-04-26 13:55
On the Nordic Warehouse level two there is a row of spruce slabs missing in the roof, on this image its on the left side.
![2020-04-26_15 43 47](https://user-images.githubusercontent.com/38815969/80309569-26af5f80-87d6-11ea-923c-f8fd508e4d7c.png)
Version: 0.11.886
in older versions it was missing on both sides, so it didn't look like an error, but the latest versions have added this row of slabs to the other side, so its probably just missing there.

**Comment by lunadragnstar** [comment] 2020-04-26 14:51
1.12 Stone Cook Fixed

**Comment by lunadragnstar** [comment] 2020-04-26 15:14
All Asian huts rescanned

**Comment by lunadragnstar** [comment] 2020-04-26 15:54
Nordic Warehouse fixed

**Comment by ToMe25** [comment] 2020-04-26 15:55
also it seems like th spacewarssupplycamp is duplicated again.

**Comment by lunadragnstar** [comment] 2020-04-26 16:14
Books and quills being removed from schematics

**Comment by lunadragnstar** [comment] 2020-04-26 16:14
Player heads being removed from schematics

**Comment by lunadragnstar** [comment] 2020-04-26 16:15
Rotation issue should be fixed, will be rescaning all schematics in

**Comment by lunadragnstar** [comment] 2020-04-26 16:16
@ToMe25 That should have been fixed but will double check.

Nope, ended up in there again, will fix

**Comment by Howman** [comment] 2020-04-26 18:15
#4757 (comment)

**Comment by lunadragnstar** [comment] 2020-04-27 09:33
Birch school hut block issue

**Comment by PowerSchill** [comment] 2020-04-29 13:47
The fortress wall corner decoration blocks don't have an upgrade option like the walls. Also when you try and just build any level above 1 when the builder actually starts building it it says building "corner1" and then actually builds level 1 only.

**Comment by benbenlaw** [comment] 2020-04-29 14:44
the miner breaking own blocks is on acacia and on mesa scematics

**Comment by AlMasque** [comment] 2020-04-29 15:18
Asian Barracks and guard towers are broken

When building each guard tower, every single one of them is off centered by 1 down and 1 across, (they're off by 1 block diagonally) This occurs in all levels of the structure

Proof/Examples
https://www.reddit.com/user/AlMasque/comments/ga0phq/alignment_problems_with_the_barracks_in_the_asian/

**Comment by Kao713** [comment] 2020-04-29 17:05
Jungle barracks are broken and place barracks towers in the wrong place and wrongly rotated

**Comment by lunadragnstar** [comment] 2020-04-29 21:49
@AlMasque what version are you on? I think you have an old version as I just tested this and it is working properly.

**Comment by lunadragnstar** [comment] 2020-04-29 22:02
Upgradable oak walls fixed

**Comment by AlMasque** [comment] 2020-04-30 00:07
> @AlMasque what version are you on? I think you have an old version as I just tested this and it is working properly.
was on 0.11.888, will try with the newest version

**Comment by AlMasque** [comment] 2020-04-30 01:13
> Asian Barracks and guard towers are broken
> 
> When building each guard tower, every single one of them is off centered by 1 down and 1 across, (they're off by 1 block diagonally) This occurs in all levels of the structure
> 
> Proof/Examples
> https://www.reddit.com/user/AlMasque/comments/ga0phq/alignment_problems_with_the_barracks_in_the_asian/



Have now tested on the latest build. As of 0.11.894, 3 of the 4 towers have been fixed. however the front right tower is still misaligned, attached below is an example, of the problem

https://www.reddit.com/user/AlMasque/comments/gam1dt/minecolonies_asian_barracks_alignment_log_part_2/

**Comment by AlMasque** [comment] 2020-05-02 02:12
> > Asian Barracks and guard towers are broken
> > When building each guard tower, every single one of them is off centered by 1 down and 1 across, (they're off by 1 block diagonally) This occurs in all levels of the structure
> > Proof/Examples
> > https://www.reddit.com/user/AlMasque/comments/ga0phq/alignment_problems_with_the_barracks_in_the_asian/
> 
> Have now tested on the latest build. As of 0.11.894, 3 of the 4 towers have been fixed. however the front right tower is still misaligned, attached below is an example, of the problem
> 
> https://www.reddit.com/user/AlMasque/comments/gam1dt/minecolonies_asian_barracks_alignment_log_part_2/

sorry for the slight spam but issue still unresolved as of 0.11.907-ALPHA

**Comment by b52src** [comment] 2020-05-07 12:48
Cant upgrade Road/Asian Bridges the upgrade option is not given in the GUI
Version: minecolonies-0.11.928-ALPHA-universal
note: wall/Asian upgrades are working, also would love to see some kind of Asian Road design and a Asian Dyer design

**Comment by Kao713** [comment] 2020-05-09 10:58
Fortress fletcher doesn't have fletcher block

**Comment by b52src** [comment] 2020-05-11 15:49
most of the Asian decoration upgrades are not working now including the wall which was previously working. on  minecolonies-0.11.939-ALPHA-universal

**Comment by Obbay2** [comment] 2020-05-11 17:11
Issue
Wooden1 house has no upgrade button.

Minecolonies version
minecolonies-0.11.936-ALPHA

Expected behavior
Upgrade button to build to wooden2 template

Actual behaviour
No upgrade button

Steps to reproduce the problem
1. Build wooden1 player housing template
2. Open build menu and no upgrade button exists

**Comment by badacsonyigorenyember** [comment] 2020-05-13 14:39
minecolonies-0.11.936-ALPHA-universal the miner keeps dieing because he can't build up the ceiling when he is in an open area in a mine and there monsters can jump in and kill him.

**Comment by badacsonyigorenyember** [comment] 2020-05-13 14:42
minecolonies-0.11.936-ALPHA-universal I have a mediavel city and my barracks is a total mess. The towers are not matching with the barrack's building and if I repair the barrack then I have to repair the tower next and started all over again.

**Comment by Obbay2** [comment] 2020-05-14 04:11
minecolonies-0.11.936-ALPHA-universal
Nordic university level 3 top level allows monsters to spawn indoors.

![image](https://user-images.githubusercontent.com/4176173/81892054-036b0b00-955f-11ea-9d00-37329eeb5ba3.png)

![image](https://user-images.githubusercontent.com/4176173/81891823-55f7f780-955e-11ea-8409-42105f0fd82c.png)

**Comment by lunadragnstar** [comment] 2020-05-14 18:53
Fixed Nordic University

**Comment by PowerSchill** [comment] 2020-05-14 19:04
> The fortress wall corner decoration blocks don't have an upgrade option like the walls. Also when you try and just build any level above 1 when the builder actually starts building it it says building "corner1" and then actually builds level 1 only.

**Update:** I just tested in a single player creative world and the correct schematic gets pasted so I think the issue is what the builder is building and not the schematic itself?

**Comment by ToMe25** [comment] 2020-05-15 08:57
The nordic warehouse level 3 seems to have some issues:
![2020-05-15_10 55 14](https://user-images.githubusercontent.com/38815969/82031882-c5730180-969a-11ea-9296-c7e0f70e5479.png)
![2020-05-15_10 55 19](https://user-images.githubusercontent.com/38815969/82031890-c73cc500-969a-11ea-961b-a6f1823ef707.png)
This are screenshots of the two ends of the middle roof.
I also let the builder repair it a few times, but that doesn't solve it either.

**Comment by svnrex2019** [comment] 2020-05-15 09:05
I'm unable to build Fortress L3 farmer as it requires composted dirt but research to build composter requires a L3 farmer.
Using the Fortress schematics the level 3 farmer requires composted dirt to be built, the composter requires a level 3 farmer in order to be researched at the university.

**Comment by lunadragnstar** [comment] 2020-05-15 16:49
@svnrex2019 You can make compost yourself for the schematic. Check JEI for the recipe but you can use our barrels to make the compost, then combine it with dirt or something for the composted dirt you need.

**Comment by lunadragnstar** [comment] 2020-05-15 17:02
Fixed Nordic warehouse level 3

**Comment by lunadragnstar** [comment] 2020-05-15 17:09
Rescanned fortress corners

**Comment by lunadragnstar** [comment] 2020-05-15 17:10
Opened new issue for barracks/barrack towers

**Comment by lunadragnstar** [comment] 2020-05-15 17:10
Opened new issue for miners

**Comment by lunadragnstar** [comment] 2020-05-15 17:41
Fixed Asian deco

**Closed as completed** 2020-05-15 17:48 UTC

**Comment by svnrex2019** [comment] 2020-05-16 04:42
> @svnrex2019 You can make compost yourself for the schematic. Check JEI for the recipe but you can use our barrels to make the compost, then combine it with dirt or something for the composted dirt you need.

Thanks for the info I'll use that, but the JEI in the Valhelsia does not show a recipe for compost

**Comment by lunadragnstar** [comment] 2020-05-16 18:35
@svnrex2019 you have to use our barrel block used in the composter to make compost, same as the barrel for vanilla villagers but ours makes compost not bonemeal. Ours however needs time to work, you add your material to the barrel, then wait for it to compost, when it is done you collect he compost, which is an item not a block, then combine the compost with 8 dirt and you get a composted dirt block

**Comment by ShaneCourtrille** [comment] 2021-01-14 19:26
Fortress Level 1 Townhall and Level 2 signs differ on recommendations for what buildings to place around the townhall.  Specifically level 1 recommended a University but level 2 recommended a Cook and another building.

**Comment by ravenbuilder934** [comment] 2021-01-14 19:43
#5006 for all new schematic issues
