### ISSUE TITLE
Teleport Crash server

### ISSUE THREAD

**Issue by Seilican** [ldtteam/minecolonies#4025] opened 2019-11-03 00:52 UTC
### Minecolonies version

Minecraft Version: 1.14.4

(modded) forge-28.1.76

Version: 

minecolonies-0.10.497-ALPHA-universal.jar

### Expected behavior

be able to teleport with townhall to ally colony

### Actual behaviour

use the ally teleport still move around for about 5 mins than server crash's and roll back to just before teleport

https://pastebin.com/hatMtkQP

### Steps to reproduce the problem
play on the Minecolonies Getting Started server

1. use townhall to port to ally colony
2. and look back at townhall block you just showed up at and see ally is gone
3. your crashed
4. ... Profit

**Comment by someaddons** [comment] 2019-11-03 00:57
your server crashed from lag, which according to the log was caused by the campfire mod loading some chunks :) Closing this since unrelated to minecolonies

**Comment by Raycoms** [comment] 2019-11-03 00:57
at com.natamus.nohostilesaroundcampfire.events.CampfireEvent.onEntityJoin(CampfireEvent.java:59) ~[?:1.0] {re:classloading}

not our mod

**Closed as completed by someaddons** 2019-11-03 00:57 UTC

**Comment by Seilican** [comment] 2019-11-03 00:59
Thank you

**Comment by someaddons** [comment] 2019-11-03 00:59
you can set the max server tick time in the server.properties higher, so it doesnt crash that fast on lag
