### ISSUE TITLE
Nordic Blacksmith won't upgrade

### ISSUE THREAD

**Issue by IceRavenNL** [ldtteam/minecolonies#6650] opened 2021-03-03 10:20 UTC
I won't to upgrade the nordic blacksmith building it is at level 3 but if you want to upgrade it to level 4 it did something but it gets stuck. I waited a whole day but it doens't go further with building

**Comment by Nightenom** [comment] 2021-03-03 10:22
Use issue template next time and probably dupe of #6649

**Closed as completed by Nightenom** 2021-03-03 10:22 UTC
Labels: Bug
