### ISSUE TITLE
Deco block doesn't allow for upgrade

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#4434] opened 2020-03-15 02:48 UTC
I can build the first level of the deco with the deco block, however the builder sees it like a regular deco, no "block" shows up for me to click on to tell the builder to build it, they just automatically start building. 

However, when I click on the deco block to upgrade it, it doesn't give me the option

![image](https://user-images.githubusercontent.com/29446488/76694161-dde88080-6645-11ea-9853-4c43e7bfd148.png)

**Comment by Raycoms** [comment] 2020-03-15 09:27
is there a level 2 with exactly the same name and a "2" behind it?

**Comment by lunadragnstar** [comment] 2020-03-15 16:11
![image](https://user-images.githubusercontent.com/29446488/76705395-28094a80-66b6-11ea-882e-b49dd885bd97.png)

**Comment by Raycoms** [comment] 2020-03-16 19:32
@lunadragnstar can you send me those 3?

**Comment by PasixTheValkyrie** [comment] 2020-03-16 19:38
Can confirm this counts for medievaloak wall segments aswell

![afbeelding](https://user-images.githubusercontent.com/43132310/76793860-23cc5280-67c6-11ea-97bc-1ceb5e785e34.png)

**Comment by Raycoms** [comment] 2020-03-16 20:43
Okay @lunadragnstar I found out what the problem is:

You reorganized the folders and now the folder structure doesn't matter the string that you entered in the field:

Example: 

In the controller: schematics/medievaloak/walls/segment
Actually:schematics/walls/medievaloak/segment

**Comment by PasixTheValkyrie** [comment] 2020-03-16 20:47
Is this fixable on our end or should we wait for a fix?

**Comment by Raycoms** [comment] 2020-03-16 20:48
You have to wait for a fix. But now that we know what the problem is, that should be relatively fast

**Comment by PasixTheValkyrie** [comment] 2020-03-16 20:50
Thanks a lot! 👍

**Comment by lunadragnstar** [comment] 2020-03-16 22:15
Ok, the walls, I haven't edited yet. I started with the housing and I know I got the folder right.

**Comment by PasixTheValkyrie** [comment] 2020-03-21 00:51
Hiya, just wondering if there's any update on this issue. Looking quite forward to upgrading walls by now.

Cheers and thanks!

**Comment by Raycoms** [comment] 2020-03-30 15:02
Closed in favor of joint issue.

**Closed as completed by Raycoms** 2020-03-30 15:02 UTC
