### ISSUE TITLE
Craftment not at they work station.

### ISSUE THREAD

**Issue by Wetz1990** [ldtteam/minecolonies#3333] opened 2019-02-08 11:18 UTC
### Minecolonies version
1.12.2-0.10.159-Alpha

Version: 

### Expected behavior
The crafters, Stone mason, sawmill, stone smelter, blacksmith would go to their respective building in the morning and wait for a task.

- 

### Actual behaviour
In the morning after the crafters have slep in their beds they almost never go to their work station. 
And, it seem, becaues they are not ar their wokr station they do not process requests from the request system.

### Steps to reproduce the problem
1. Let the game run.
2. let the craftmen sleep in a house/bed a night.
2. Sleep after it has turned night time to turn in day, or wait till day comes by itself.
3. Craftmen will now stay in their house and not return to their work station.

I suspect that this may "break" the request system since they wont process the request.

However, when i make sure the request system triggers when they are a ttheir work station everything works just fine.

**Comment by Wetz1990** [comment] 2019-02-09 00:28
noticed that the cook does the same where he/she just stays in the hut she slept in all day. So no one gets food.
https://imgur.com/ovw1kXU

**Comment by Raycoms** [comment] 2019-02-09 01:30
I got some code which only needs some testing ready for it.

Am Fr., 8. Feb. 2019 um 22:28 Uhr schrieb Wetz1990 <notifications@github.com

**Comment by Raycoms** [comment] 2019-02-09 02:15
Can you try if it works well in this:
https://teamcity.minecolonies.com/guestAuth/repository/download/LetSDevTogether_Minecolonies_Branches_Build/25004:id/build/libs/minecolonies-1.12.2-0.10.665-PERSONAL-universal.jar

Including the other workers like the builder etc.

Am Fr., 8. Feb. 2019 um 23:30 Uhr schrieb Ray Neiheiser <
ray.neiheiser@gmail.com>:

**Comment by Wetz1990** [comment] 2019-02-09 10:02
It seems to work better.
Without looking in to the code, it seems like that whenever a request is send to the crafter, the deliveryman delivers the materials and the crafter comes running.
Seems to work very well.

**Comment by Wetz1990** [comment] 2019-02-09 11:21
It however seems that if the crafter recieves other requests while he is furfilling one, they dont get processed, or queued up.

**Comment by Grummelkater** [comment] 2019-02-09 15:16
I can confirm this behavior. I’m also quite sure that there’s some kind of glitch when requests would have to queue up. It seems as if requests are simply ignored if the workers are busy.

**Comment by Wetz1990** [comment] 2019-02-10 12:07
I have also noticed that the requests does not carry over to the next day. 
So if the crafter is in the middle of crafting something and sunset/ night comes, the crafter will not continue the crafting the next day

**Comment by Raycoms** [comment] 2019-02-10 12:26
Couldn't reproduce this, it worked fine for me.

Am So., 10. Feb. 2019 um 10:07 Uhr schrieb Wetz1990 <
notifications@github.com>:

**Comment by Wetz1990** [comment] 2019-02-10 12:45
I will update to the latest Alpha and investigate agin

**Comment by Wetz1990** [comment] 2019-02-10 16:50
so, i am now using the latest version 164-alpha.

And i am still getting the problems with not all the requests getting to the crafter.
The builder in the image has had the requst up for a few in game days, and nothing has happend.
The crafter has previously made racks for him, but the it turned to night time and request kind a stranded.

https://imgur.com/a/u4ju6Y6

For the crafter to get the request again, i would have to cancle the builders request, and have him request it one more time.

**Comment by Raycoms** [comment] 2019-02-10 17:04
Yeah it's another bug we're investigating

**Comment by nick-johnson** [comment] 2019-02-17 16:36
Not sure if it's related, but my server logs show a ton of these error messages when the crafters 'forget' their tasks. This is using 172-ALPHA

17.02 11:28:15 [Server] Server thread/ERROR [minecolonies]: Parent cancellation failed! Unknown request: StandardToken{id=4ca28580-1827-4d37-bddb-e3ed3419463e}

**Comment by marchermans** [comment] 2019-02-17 17:03
Probably
I am digging into it.

**Comment by nick-johnson** [comment] 2019-02-26 15:27
More errors that seem to be occurring around the parent cancellation failures. 198-RELEASE

26.02 10:17:58 [Server] Server thread/WARN [minecolonies]: Statemachine for transition com.minecolonies.coremod.entity.ai.statemachine.AITarget@2933091c threw an exception:
26.02 10:17:58 [Server] INFO java.lang.NullPointerException: null
26.02 10:17:58 [Server] INFO at com.minecolonies.coremod.colony.requestsystem.requests.AbstractRequest.setState(AbstractRequest.java:146) ~[AbstractRequest.class:?]
26.02 10:17:58 [Server] INFO at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:271) ~[StandardRequestManager.class:?]
26.02 10:17:58 [Server] INFO at com.minecolonies.coremod.colony.jobs.AbstractJobCrafter.finishRequest(AbstractJobCrafter.java:161) ~[AbstractJobCrafter.class:?]
26.02 10:17:58 [Server] INFO at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAICrafting.afterDump(AbstractEntityAICrafting.java:275) ~[AbstractEntityAICrafting.class:?]
26.02 10:17:58 [Server] INFO at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic.dumpInventory(AbstractEntityAIBasic.java:1011) ~[AbstractEntityAIBasic.class:?]
26.02 10:17:58 [Server] INFO at com.minecolonies.coremod.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:77) ~[BasicTransition.class:?]
26.02 10:17:58 [Server] INFO at com.minecolonies.coremod.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148) ~[BasicStateMachine.class:?]
26.02 10:17:58 [Server] INFO at com.minecolonies.coremod.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:131) ~[BasicStateMachine.class:?]
26.02 10:17:58 [Server] INFO at com.minecolonies.coremod.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:79) ~[TickRateStateMachine.class:?]
26.02 10:17:58 [Server] INFO at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) [?:1.8.0_191]
26.02 10:17:58 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359) [?:1.8.0_191]
26.02 10:17:58 [Server] INFO at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) [?:1.8.0_191]
26.02 10:17:58 [Server] INFO at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) [?:1.8.0_191]
26.02 10:17:58 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) [?:1.8.0_191]
26.02 10:17:58 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) [?:1.8.0_191]
26.02 10:17:58 [Server] INFO at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) [?:1.8.0_191]
26.02 10:17:58 [Server] INFO at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) [?:1.8.0_191]
26.02 10:17:58 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_191]
26.02 10:17:58 [Server] INFO at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449) [?:1.8.0_191]
26.02 10:17:58 [Server] INFO at com.minecolonies.coremod.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:61) [TickRateStateMachine.class:?]
26.02 10:17:58 [Server] INFO at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:150) [AbstractAISkeleton.class:?]
26.02 10:17:58 [Server] INFO at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) [xf.class:?]
26.02 10:17:58 [Server] INFO at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) [vq.class:?]
26.02 10:17:58 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359) [vp.class:?]
26.02 10:17:58 [Server] INFO at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) [vq.class:?]
26.02 10:17:58 [Server] INFO at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178) [vd.class:?]
26.02 10:17:58 [Server] INFO at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:585) [EntityCitizen.class:?]
26.02 10:17:58 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179) [vp.class:?]

**Comment by someaddons** [comment] 2019-02-26 15:55
Could you instead upload the whole log to sth like https://paste.dimdev.org ? makes it easier to relate errors to other errors

**Comment by Raycoms** [comment] 2019-10-14 17:31
closed in favor of other issue

Can you test the dman and crafters here:

https://teamcity.minecolonies.com/guestAuth/repository/download/LetSDevTogether_Minecolonies_Branches_Build/31486:id/build/libs/minecolonies-1.12.2-0.10.1270-PERSONAL-universal.jar

**Closed as completed by Raycoms** 2019-10-14 17:31 UTC
