### ISSUE TITLE
Stone Citizen's Hut level 2 bug

### ISSUE THREAD

**Issue by Egrof** [ldtteam/minecolonies#1655] opened 2017-11-18 13:13 UTC
### Minecolonies version : 1.12.2-0.8.4280

Ordered the construction for a stone Citizen's Hut level 2 but the Builder can't finish : he needs a "tile.minecolonies.blockconstructiontape.name"
In his hands I can see that yellow conctruction fence. Maybe it was scanned with the schematic.

**Comment by Justen-N** [comment] 2017-11-18 23:08
You actually have to craft the tape for that building. I do not remember
the schematic at the moment. Not a bug.

On Nov 18, 2017 6:13 AM, "Egrof" <notifications@github.com> wrote:

Minecolonies version : 1.12.2-0.8.4280

Ordered the construction for a stone Citizen's Hut level 2 bur the Builder
can't finish : he needs a "tile.minecolonies.blockconstructiontape.name"
In his hands I can see that yellow conctruction fence. Maybe it was scanned
with the schematic.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Minecolonies/minecolonies/issues/1655>, or mute the
thread

**Comment by MineShadow7** [comment] 2017-11-19 07:08
Fixed in the future release.
@Raycoms can we close this?

**Closed as completed** 2017-11-19 07:25 UTC
