### ISSUE TITLE
Guard mimicking Vampire - Unable to enter or exit huts

### ISSUE THREAD

**Issue by Poojawa** [ldtteam/minecolonies#6093] opened 2020-11-16 16:30 UTC
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.448-ALPHA Universal
- Structurize Version: 0.13.94-ALPHA
- Related Mods and their Versions: Endless Frontier 5.9, manually updated Minecolonies

## Expected behavior

Guard able to cure flu at hospital and return to patrol.

## Actual behavior

Guard is unable to cross boundary line of any doorway. Destroying doors doesn't help, he just constantly opens, then closes the door. Healer walks out to attempt to drag him inside, however he's too far from the beds, and thus, no treatment.

![2020-11-16_10 11 08](https://user-images.githubusercontent.com/6293118/99278754-1358f580-27f5-11eb-82cc-c0530bb1e6cc.png)

## Steps to reproduce the issue

Hospital is Asian style tier 3
Guard tower is Asian alt style Tier 1

### Logs

- latest.log: 
- crashlog: 

n/a no crash or log issues. found. 

### Notes

he's the only guard affected by this issue, all other guards are pathing correctly, have been treated correctly. Recalling to guard post allows him to path to the door of the hospital, but he cannot get inside. Recalling to town hall prevents him from pathing out of the building. Using a lead will move him around *inside* of the space, or outside, but he just can't cross doorways. 
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment] 2020-11-16 16:32
it looks like this armour is preventing this for me

**Comment by Poojawa** [comment] 2020-11-16 16:36
All guards are wearing Mekanism Osmium armor without issue.

**Comment by Raycoms** [comment] 2020-11-17 20:10
Is there a way to reproduce this for us?

**Comment by Poojawa** [comment] 2020-11-18 14:56
I'm thinking it's 99% edge case. 

Might be weird interaction with one or more other mods.

I've noticed that path finding for Ice and Fire raptors is sketchy as well. Happens both in Lan mode and regular. but it was just weird because not even firing/rehiring, resetting worked. He then died to a raider before I could do anything more.

Sorry I can't provide more help!

**Comment by Raycoms** [comment] 2020-11-18 14:58
Let's close this for now then. If you're ever able to reproduce this please reopen it then.

**Closed as completed by Raycoms** 2020-11-18 14:58 UTC
Labels: Bug, Awaiting Response
