### ISSUE TITLE
Racks Should Work with Inventory Tweaks [1.12.2]

### ISSUE THREAD

**Issue by WPaul15** [ldtteam/minecolonies#2364] opened 2018-04-07 08:50 UTC
### Minecolonies Version
- 1.12.2-0.8.8008

### Forge Version
- 14.23.2.2651

### Proposed Feature
At the moment, the new Rack inventory used in the Warehouse is not sortable. It would be cool if compatibility with the [Inventory Tweaks mod](https://minecraft.curseforge.com/projects/inventory-tweaks) could be added so that one could sort the items in the racks.

### Potential Improvements
- Easier to locate items
- Easier to organize the Warehouse according to your own schema (I like being organized).
- The Deliveryman/-woman doesn't check to see if an item he/she is depositing is already in the Rack, but simply deposits it in the first available slot. This leads to a lot of unnecessary clutter. Inventory Tweaks sorting automatically collects unfinished stacks and combines them, often leading to an increase in empty slots.

**Comment by marchermans** [comment] 2018-04-07 08:58
Duplicate of: #2278

**Closed as completed by marchermans** 2018-04-07 08:58 UTC

**Comment by Sandriell** [comment] 2018-04-07 14:08
Any reason why you could not generate the Inventory Tweaks xml file like you do any other config file?

**Comment by marchermans** [comment] 2018-04-07 15:11
Well we could. But we have limited man power, and this is something a user can do himself, as stated by InvTweaks (hence the existence of the file). We have to prioritize, if we are Feature complete then we might consider adding this, but for right now, we have simply have other Things on our Task list that have a higher priority.
