### ISSUE TITLE
[BUG] Some UI's error on other LAN players

### ISSUE THREAD

**Issue by Fantasycho** [ldtteam/minecolonies#8318] opened 2022-05-01 09:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.635-BETA

### Structurize Version

1.0.378-BETA

### Related Mods and their Versions

1.Forge: 39.1.2
2.BlockUI: 0.0.47-ALPHA
3.domum_ornamentum: 1.0.39-ALPHA-universal

### Current Behavior

1.All players except host can't see some critical buttons of advanced settings at the main block of buildings, that includes fuel setting(all buildings be involved)and research of university.
![HQGS8C PIS7K(%QS8T{_PYI](https://user-images.githubusercontent.com/49608407/166139771-6a03e30a-1e62-4cab-a8be-2873e5bd2674.png)
![5}X@6{OQN@GXCKFHIPK7Q0Q](https://user-images.githubusercontent.com/49608407/166139774-6458b461-57a4-4ac1-8de4-c1ff6fb44916.png)

2.Plantation and beekeeper can't set the button of harvesting both products on the side of other players, only host can do it.

Host:
![17-41-32-5-1-10505](https://user-images.githubusercontent.com/49608407/166140533-8c1c5f45-b6ec-4070-899c-af0ea0126c00.gif)

other LAN players: 
![4MWO@`K3W_XJC9)B CJXGPD](https://user-images.githubusercontent.com/49608407/166140567-3bd1c250-375f-4145-8203-057917776413.gif)

And these two bugs not happened at early release version (1.0.428).

### Expected Behavior

All buttons can be set normally at other players of LAN games.

### Reproduction Steps

Play games with friends by using LAN

### Logs

https://gist.github.com/Fantasycho/c3ee83846479cd9b5433fe0bec0c03da

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment] 2022-05-01 10:16
The research screen bug is a duplicate of #8301 by the way

**Comment by Raycoms** [comment] 2022-05-01 10:58
duplicate

**Closed as completed by Raycoms** 2022-05-01 10:58 UTC
Labels: Bug
