### ISSUE TITLE
[BUG] Mine signs don't work right upon repair

### ISSUE THREAD

**Issue by Shadizar** [ldtteam/minecolonies#9588] opened 2023-11-22 04:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.321-BETA

### Structurize Version

1.20.1-1.0.662-BETA

### Related Mods and their Versions

forge 47.2.0
blockui-1.20.1-1.0.125-BETA.jar
domum_ornamentum-1.20-1.0.147-BETA-universal.jar
multipiston-1.20-1.2.31-ALPHA.jar

### Current Behavior

If you repair a mine level and the sign is replaced, the mine level is listed as -1
additionally it seems if you repair (and sign gets replaced) on a level that had nodes, nodes starts at 0
and, it is not looking like it updates the nodes value either when they make new ones

### Expected Behavior

Signs to have correct level and node count on repair.
Even if node count has issue on repair, for it to update to correct count upon new nodes being mined

### Reproduction Steps

For me, I had a mine that had modded blank signs at some levels, then I uploaded my schematic that used vanilla signs and repaired a level.

I suspect but have not tested that repairing any level where the sign gets replaced will hit it but have not confirmed.

### Logs

none

### Anything else?

![image](https://github.com/ldtteam/minecolonies/assets/94550408/c77f0431-6e8c-4daf-83ce-8f469ed34adf)
above: repaired sign

![image](https://github.com/ldtteam/minecolonies/assets/94550408/280e25d8-2d16-4f5e-a94c-fdea3215c6fa)
above: a new sign (correct) after a new level is built

![image](https://github.com/ldtteam/minecolonies/assets/94550408/9b24e7da-1d13-4cf2-b684-e7db511493ef)
Above, nodes wrong for existing nodes on level (and does not update upon new nodes)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment] 2023-12-03 16:05
duplicate of https://github.com/ldtteam/minecolonies/issues/8215

**Closed as completed by Raycoms** 2023-12-03 16:05 UTC
Labels: Bug

**Comment by Shadizar** [comment] 2023-12-03 16:23
Not entirely duplicate 
Their report claimed nodes data is correct...in mine, nodes data is also incorrect
