### ISSUE TITLE
Dman not dumping at warehouse

### ISSUE THREAD

**Issue by Wetz1990** [ldtteam/minecolonies#3617] opened 2019-05-18 06:28 UTC
### Minecolonies version
Version: minecolonies-1.12.2-0.10.231-ALPHA-universal.jar

### Expected behavior
The D-man would perform his Gather task, pick up items from other inventories, then he would perfrom his Dumping task, where he would go to the warehouse and dum his inventory. 

### Actual behaviour
The D-man performs his Gather task, pick up items from other inventories, then he perfrom his Dumping task, where he would go to the warehouse and does nothing. He just goes to the warehouse block, does not dump anything, and continues to gather.
It seems like this also keeps him from furfilling requests from the request system.

### Steps to reproduce the problem

1. Build a Dman
2. build a Warehouse
3. Let him collect things
4. Watch him not dump his inventory in the warehouse.

**Comment by marchermans** [comment] 2019-05-18 07:10
Please update to a newer version.

**Comment by Wetz1990** [comment] 2019-05-18 07:36
Updated to minecolonies-1.12.2-0.10.283-ALPHA-universal.jar

Still happening. I kept an eye on the dman using the "/mc citizens info colony: 1 citizen: 1". They do perform the dumping action, but dosnt actually dump anything.

https://imgur.com/149ZF0d

**Comment by Raycoms** [comment] 2019-05-18 11:59
Any log?

**Comment by Wetz1990** [comment] 2019-05-18 13:54
Sorry about that.
Here is the latest:
https://pastebin.com/JYkVwMst

Hope that is what you need.

**Comment by marchermans** [comment] 2019-05-18 14:12
`[09:46:48] [Netty Server IO #1/WARN]: Error: Block at BlockPos{x=143, y=72, z=258} (Class: com.minecolonies.coremod.tileentities.TileEntityRack Te: com.minecolonies.coremod.tileentities.TileEntityRack@19eb64bb Block: Block{minecolonies:blockminecoloniesrack}) returned null after indicating the capability is available.`

Is probably the cause of the issue.......

**Comment by marchermans** [comment] 2019-05-18 14:12
@Raycoms

**Comment by Raycoms** [comment] 2019-05-18 14:16
Yeah, it seems like all the racks of the warehouse are broken. Which is
weird.

Am Sa., 18. Mai 2019 um 11:12 Uhr schrieb Marc Hermans <
notifications@github.com>:

**Comment by Wetz1990** [comment] 2019-05-18 14:25
Anything I can do in my end to try and get around/fix this?

**Comment by Raycoms** [comment] 2019-05-18 14:32
do the racks in the warehouse work for you?

Am Sa., 18. Mai 2019 um 11:25 Uhr schrieb Wetz1990 <notifications@github.com

**Comment by Wetz1990** [comment] 2019-05-18 19:48
Yes. I am able to place resources in the racks.
I have tried placing tools in the racks, but the Dman won’t pick them up upon requested.

**Comment by Raycoms** [comment] 2019-05-18 19:56
Weird, is the world heavily modded? Could you send it to us?

Am Sa., 18. Mai 2019 um 16:48 Uhr schrieb Wetz1990 <notifications@github.com

**Comment by Wetz1990** [comment] 2019-05-18 20:40
It’s the official minecolonies pack from twitch.
How would you want me to send it to you? Over discord?

**Comment by fr3akb0y** [comment] 2019-05-19 01:25
This is a thing i said in a previous issue I opened: in the newest versions the Racks are not connecting to each other if newly placed and that seems to break the dman. Converting from an older version where Racks were connecting to the newer version keeps them connected to each other until you break them while also letting the dman dump stuff in there (at least when I tested it). There is definitely something going on with Racks :/

**Comment by Wetz1990** [comment] 2019-05-19 09:59
https://drive.google.com/drive/folders/1bjvxxkPS6eC6Dr2t-xhJwgH9G5XOWBZQ

This should be the world. Its just called New World

**Comment by bookerthegeek** [comment] 2019-05-19 13:37
@fr3akb0y Can you try this:

1. Break all te racks in the warehouse
2. Select the option to rebuild the warehouse

Does that make it work?

**Comment by fr3akb0y** [comment] 2019-05-19 14:23
@bookerthegeek 
I've now gone ahead and tried this. Only breaking the Racks and requesting a repair didnt work. It seems the Warehouse block saved an older blueprint of the house where Racks werent connected because after breaking the Warehouse block itself and rebuilding it they are connecting as they should. So my problem is now solved ^^

**Comment by Raycoms** [comment] 2019-05-19 14:24
I created a fix which is going to be merged today =)

Am So., 19. Mai 2019 um 11:23 Uhr schrieb fr3akb0y <notifications@github.com

**Closed as completed** 2019-05-19 18:40 UTC
