### ISSUE TITLE
Minecolonies, Aternos, Tickling Entity, Dirt and Forge

### ISSUE THREAD

**Issue by kobango** [ldtteam/minecolonies#7938] opened 2022-01-14 17:34 UTC
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: minecolonies-1.18.1-1.0.347-ALPHA.jar 
- Forge Version: forge-1.18.1-39.0.20-universal.jar    

### Logs

log
https://gist.github.com/kobango/aa41539414d2e68f2e5fe1abc0816585
## Steps to reproduce the issue / details

Just Run Game with minecolonie son aternos and wait

Just reporting the AI issue. 

### Notes

I'm almost sure the forge version is a problem but i have no idea what to do
---
## Viewers
[crash-2022-01-14_17_25_33-server.txt](https://github.com/ldtteam/minecolonies/files/7872198/crash-2022-01-14_17_25_33-server.txt)

**Comment by uecasm** [comment] 2022-01-14 17:43
Duplicate of ldtteam/Structurize#473

Either downgrade Forge to 39.0.17 or upgrade MineColonies to 1.18.1-1.0.349-ALPHA.

**Closed as completed by uecasm** 2022-01-14 17:43 UTC
Labels: Bug, AI Log
