### ISSUE TITLE
Crash on Dark Oak Barracks lvl 2 or Higher

### ISSUE THREAD

**Issue by Kisonu** [ldtteam/minecolonies#2493] opened 2018-05-28 23:04 UTC
### Minecolonies version

version -1.12.2-0.8.8277

### Expected behavior

no crash

### Actual behaviour

crash

### Steps to reproduce the problem

Open level 2 or higher Dark Oak barracks
Select any option
[crash-2018-05-28_17.02.30-client.txt](https://github.com/Minecolonies/minecolonies/files/2046291/crash-2018-05-28_17.02.30-client.txt)

**Comment by Nightenom** [comment] 2018-05-29 10:49
Duplicate of #2447?

**Comment by PoroUsedSnax** [comment] 2018-05-29 17:25
I would consider this a duplicate. May be worth testing with an updated version, we're now up to 8402, not sure if it's an issue that may have been fixed, comment on #2447 if it isn't.

**Closed as completed by PoroUsedSnax** 2018-05-29 17:25 UTC

**Comment by Kisonu** [comment] 2018-05-30 07:09
This issue is also being recreated with the current updated version and the level 3 smelter. Selecting upgrade is causing the crash below.
[crash-2018-05-30_01.04.45-client.txt](https://github.com/Minecolonies/minecolonies/files/2052730/crash-2018-05-30_01.04.45-client.txt)
