### ISSUE TITLE
White items (Beds, Quartz blocks) showing up Gray in Clipboard 

### ISSUE THREAD

**Issue by ShaneCourtrille** [ldtteam/minecolonies#6565] opened 2021-02-17 04:21 UTC
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.13.620-ALPHA-universal
- Structurize Version: structurize-0.13.134-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

White items should show up correctly in the clipboard

## Actual behavior

Items such as White Beds/Chiseled Quartz Block are appearing with a grayish color as shown below.  Interestingly enough the banner in the same screenshot does not have this color issue.

![2021-02-16_21 16 20](https://user-images.githubusercontent.com/121610/108155716-9f044b80-709c-11eb-9753-43e51b8a8cd7.png)

## Steps to reproduce the issue

Not sure if this will reproduce for anyone else and I don't have another game far enough in to test against.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ShaneCourtrille** [comment] 2021-02-17 05:42
Also happening in the Builder Required Resources list and for non-white things like Cobblestone.

**Comment by Nightenom** [comment] 2021-02-17 11:16
I know about this and the fix is kinda super hard, it's problem with lighting the block during rendering it into the icon, low priority fix

**Comment by Raycoms** [comment] 2021-02-17 11:18
Was this always a problem, or only recently?

**Comment by Nightenom** [comment] 2021-02-17 11:20
I know the cause (recent thing) but vanilla lacks rendering item icons using matrixstack, so nope from me until they fix it or I will learn how to persuade lighting to shift with the matrixstack

**Comment by Raycoms** [comment] 2021-02-17 11:26
Could we theoretically render item entities?

**Comment by Nightenom** [comment] 2021-02-17 11:28
? 3d rendering in 2d? :D and the lighting issue probably won't go that easily

**Comment by Raycoms** [comment] 2021-02-17 11:31
Nah, render them in 3d =D

**Comment by Nightenom** [comment] 2021-02-17 11:44
Yep, ok, go set this up, enjoy having pain for like week before you manage to get code so good it handles all the possible rotations based on itemstack

**Comment by Raycoms** [comment] 2021-02-17 11:46
xD

**Comment by uecasm** [comment] 2021-02-17 12:03
Can you "borrow" the method that JEI or TOP use?  They don't seem to have the issue.

**Comment by marchermans** [comment] 2021-02-17 14:50
There is a method in the Render utils that mc provides

Both to enable and disable it
See new bo for examples by also mc itself EG slots

**Comment by Nightenom** [comment] 2021-02-17 15:28
It's not enough, the lighting source is simply shifted, you can't fix that by vanilla things only, partial fix incoming
edit: and new bo is still not matrixstack based

**Comment by ShaneCourtrille** [comment] 2021-02-17 16:08
One thing to mention is that I recently upgraded from an earlier version (603 maybe?) and this problem didn't exist in that version.  Would it be helpful if I did a version bisect to see at what version it starts appearing?

**Comment by Raycoms** [comment] 2021-02-17 16:09
Not to worry, we know what the problem is

**Comment by Nightenom** [comment] 2021-02-20 13:21
Closed by ldtteam/structurize#292

**Closed as completed by Nightenom** 2021-02-20 13:21 UTC
Labels: Bug, System: GUI
