### ISSUE TITLE
Request/Suggestion: Food and Hunger enhancements

### ISSUE THREAD

**Issue by drgerard** [ldtteam/minecolonies#4075] opened 2019-11-12 23:42 UTC
1. Ability in a config or other method to choose which food the Citizens eat.  I noticed that even though I had set rotten flesh as as a compostable item my composter was eating them instead of composting them. 
2. A config setting for hunger levels and consumption. I would love to be able to control how fast the villagers hunger levels increase during the day as it seems right now the farmer makes more food than they can ever eat!

**Comment by Raycoms** [comment] 2019-11-16 09:22
We thought a lot about this, but it's not so easy, the problem is, if we add this config, the code which checks this runs exponentially slower.

**Comment by marchermans** [comment] 2019-11-29 13:54
@Raycoms This is right now a simple constant, is it not?
Could we not simply introduce a constant that modifies the amount that gets consumed. And for 1.14 possibly a custom tag to control what he can eat and what not?

**Comment by Raycoms** [comment] 2019-11-29 14:51
I think we got a config value for hunger already, if not, yes, it is a simple constant.

In terms of tags, that's also difficult, because we'd have to tag a ton of stuff, would be easier then to just tag things as not edible.

**Comment by Raycoms** [comment] 2020-03-30 14:45
Closed in favor of joint issue.

**Closed as completed by Raycoms** 2020-03-30 14:45 UTC
Labels: Good First Issue
