### ISSUE TITLE
Game crash when interacting with certain citizens

### ISSUE THREAD

**Issue by RangerArden** [ldtteam/minecolonies#7269] opened 2021-06-20 07:20 UTC
- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.221-BETA-universal
- Structurize Version: 0.13.177-ALPHA-universal
- Related Mods and their Versions: Tinker's construct 1.16.5-3.0.4.197, tinker's better compat 0.2-1.16.5-36.1.0

## Expected behavior
I'd right-click on the citizen in question (knight-type guard) and be able to fill their request from their menu as usual.

## Actual behavior
When I right-click on a knight-type guard who has a request open asking for a sword, my game crashes in short order. 

## Steps to reproduce the issue

1. 
2. 
3. 
[crash-2021-06-20_15.32.30-client.txt](https://github.com/ldtteam/minecolonies/files/6681864/crash-2021-06-20_15.32.30-client.txt)

### Logs

- latest.log: https://gist.github.com/RangerArden/3ac284894ca1f2c376e81fa5410318b9
- crashlog: https://gist.github.com/RangerArden/35d075ba13991d5912c8cbaddc3cc033

### Notes
I am using an old version of structurise because newer versions give me the 'i want THIS version not the version you have installed' error. I am not an expert in debugging stuff, I took this to the Curseforge discord for debug help and they said report it to you all so here I am. 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment] 2021-06-20 07:21
Duplicate of #7267

**Closed as completed by uecasm** 2021-06-20 07:21 UTC
Labels: Bug
