### ISSUE TITLE
Updating the Russian language (ru_ru.lang)

### ISSUE THREAD

**Issue by gri3229** [ldtteam/minecolonies#1312] opened 2017-07-23 13:53 UTC
### Minecolonies version

minecolonies-universal-1.11.2-0.8.3185

### Updating the Russian language

A translation was made based on the existing and on the basis of the Angi language. I ask you to pay attention to the developers! From myself I will say that I have been following the development of fashion for a long time and I want to contribute to its further development. **gri3229**

[ru_ru.zip](https://github.com/Minecolonies/minecolonies/files/1168107/ru_ru.zip)

**Comment by MineShadow7** [comment] 2017-07-23 15:45
We translate only strings that avaible in POEditor.

**Comment by gri3229** [comment] 2017-07-23 16:33
I've heard about this (POEditor), but in this case, the achievements and information about the collection of resources by residents as an option with English are translated. Not much is not enough :) I would like to attract more Russian-speaking players and make the translation more friendly for them.

**Comment by scriptsengineer** [comment] 2017-07-26 15:21
I'm seeing that the problem is happening with my language (Portguese - BR), I do not know how the tool works, but the translation is horrible! I translated and asked for a PR but it was not accepted, I want only as Gri3229 said: more user in my language using the modification

**Comment by scriptsengineer** [comment] 2017-07-26 15:28
Another problem I can point out are about Achievements which has some "jokes" and most of the time an automatic translation does not work at all well ... example would be the line where the phrase from bugsbunny is described, I suggest creating something where users can quickly help In translation.

**Comment by Raycoms** [comment] 2017-07-26 16:11
I will invite you to the tool Rafael, just some patience please I'm
currently traveling.
I translated the Portuguese versions myself

Am Mittwoch, 26. Juli 2017 schrieb Rafael Correa :

**Comment by scriptsengineer** [comment] 2017-07-26 18:20
Thanks for your patience Raycoms!

**Comment by marchermans** [comment] 2017-07-26 22:03
Please use POEditor for, you are getting your invites from their as soon as @Raycoms gets some time to send the link. For now closing this.

**Closed as completed by marchermans** 2017-07-26 22:03 UTC
