### ISSUE TITLE
Cannot go Online 

### ISSUE THREAD

**Issue by Dylanm64** [ldtteam/minecolonies#7666] opened 2021-10-14 16:28 UTC
MineConlonies Official 
Minecraft v.1.16.5
v3.4.zip

Your Mod does not support Microsoft logins. Anyone who bought Minecraft after December 2020 does not have access to a Mojang account, and is not able to login online. This means that anyone who recently bought Minecraft or will buy it in the future is currently unable to play online with friends. Hopefully you have already realized this and are working on it.

**Comment by Raycoms** [comment] 2021-10-14 16:36
I'll just close this right away. For future reference:
a) Avoid a demanding tone when reporting bugs to an open source project
b) Completely describe what the problem is instead of only the result of the problem
c) Fill in the template and add log.
d) This is MOD support not Modpack support. v3.4 is NOT a mod version.

**Closed as completed by Raycoms** 2021-10-14 16:36 UTC
