### ISSUE TITLE
Miners won't work

### ISSUE THREAD

**Issue by Thanaen** [ldtteam/minecolonies#570] opened 2017-02-09 20:03 UTC
1.10.2-0.6.2724 Minecolonies version

version X.X.XXXX or curse 7.1.6249.2188 Beta

### Expected behavior

- Go mining

### Actual behaviour

- Stay afk near the townhall

### Steps to reproduce the problem

1. Build a mine
2. Hire a miner
3. Cry
4. Profit

**Comment by Raycoms** [comment] 2017-02-09 20:14
Does he has all his tools?

2017-02-09 18:03 GMT-02:00 Thanaen <notifications@github.com>:

**Comment by Thanaen** [comment] 2017-02-09 21:00
Yeah, all tools. I killed the dude, and another took his job, and his was stuck again. I had to destroy the mining block to stop them from being a miner, and being stuck :(

**Comment by Raycoms** [comment] 2017-02-09 21:33
Does the log show anything?

**Comment by Thanaen** [comment] 2017-02-09 21:44
The log...? I can't access any server log!

**Comment by Raycoms** [comment] 2017-02-09 21:47
it does happen on our server?

2017-02-09 19:44 GMT-02:00 Thanaen <notifications@github.com>:

**Comment by Thanaen** [comment] 2017-02-10 12:22
Yep, i only play there!

**Comment by Raycoms** [comment] 2017-02-10 12:25
Hmm i can't reproduce this, does it rain or something similar?
Is he stuck at his chest?

2017-02-10 10:22 GMT-02:00 Thanaen <notifications@github.com>:

**Comment by Thanaen** [comment] 2017-02-10 12:31
It doesn't seem to be weather related, it stays near his chest all day long, and goes at the townhall at night, but never work / ask for anything!

**Comment by Raycoms** [comment] 2017-02-10 12:36
and he never worked? from the beginning on?

2017-02-10 10:31 GMT-02:00 Thanaen <notifications@github.com>:

**Comment by Raycoms** [comment] 2017-02-10 12:36
does the mineshaft has ladders?

2017-02-10 10:36 GMT-02:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by Thanaen** [comment] 2017-02-10 13:00
He started to dig the mine, then definitely stop !
There are ladders, yes

**Comment by Raycoms** [comment] 2017-02-10 19:34
He dug a few levels and then stopped?
Firing and re hiring causes him to stop immediately again?

**Comment by Thanaen** [comment] 2017-02-11 11:03
Looks like they did 1 level.
I can't fire them, even if i spam the button.
I killed the miner, but another person spawned and took the job, with the exact same issue :(
I had to break the miner block, and i haven't rebuilt it yet

**Comment by Raycoms** [comment] 2017-02-11 11:48
You need to turn manual hiring on in the townhall.

Am Samstag, 11. Februar 2017 schrieb Thanaen :

**Comment by Raycoms** [comment] 2017-02-11 11:49
Can you tell me your in-game name?  I'll give your colony a visit

Am Samstag, 11. Februar 2017 schrieb Ray Neiheiser :

**Comment by Thanaen** [comment] 2017-02-11 11:53
My in-game name is Clem0970!
Sadly i destroyed the placer miners were supposed to go (i need that afk villager), but you'll see the old mine the way my miner left it!

**Comment by marchermans** [comment] 2017-02-20 21:41
As per request I started merging Issues that are related to things I found while going through the source code. One of these is the request system. Closing this in favor of #638

**Closed as completed by marchermans** 2017-02-20 21:41 UTC
