### ISSUE TITLE
You have no permission to do this in this colony!

### ISSUE THREAD

**Issue by JeoLy** [ldtteam/minecolonies#1523] opened 2017-10-11 09:07 UTC
Hey guys,

build the colony base and exit the game, 
![colony](https://user-images.githubusercontent.com/32701652/31431734-31d25f46-ae7d-11e7-9e39-7c661d8d5a76.JPG)
after that i cant do anything close area

**Comment by Raycoms** [comment] 2017-10-11 11:02
Can't see what the problem is, no description?

**Comment by JeoLy** [comment] 2017-10-11 19:10
problem is, i cant doing anything
example i cant sleed, I click the bad and say same thing. you have no permission on this colony

**Comment by Justen-N** [comment] 2017-10-11 19:14
Are you ssp or smp, and  have you checked the permissions tab in the town
hall?

**Comment by Raycoms** [comment] 2017-10-26 13:50
Did you try /mc colony refresh?

**Comment by Raycoms** [comment] 2017-10-26 13:51
I'll close this, if this comes up again, please reopen

**Closed as completed by Raycoms** 2017-10-26 13:51 UTC

**Comment by YadiSuryahadi** [comment] 2017-10-26 18:49
I've tried it but it did not work. got error colony ID -1 not found

**Comment by Raycoms** [comment] 2017-10-26 18:54
do /mc colonies list and then /mc colony refresh idyou'vefound

2017-10-26 19:49 GMT+01:00 YadiSuryahadi <notifications@github.com>:

**Comment by YadiSuryahadi** [comment] 2017-10-27 17:29
![image](https://user-images.githubusercontent.com/33133865/32116999-f717a972-bb76-11e7-94dc-cd9aa150b70d.png)
It says refresh succesful but still have no permision :(

**Comment by Raycoms** [comment] 2017-10-27 17:30
Have yout ried restarting?

2017-10-27 18:29 GMT+01:00 YadiSuryahadi <notifications@github.com>:

**Comment by YadiSuryahadi** [comment] 2017-10-27 17:31
Restart the minecraft ?

**Comment by Raycoms** [comment] 2017-10-27 17:31
Yes, restarting the world.

2017-10-27 18:31 GMT+01:00 YadiSuryahadi <notifications@github.com>:

**Comment by YadiSuryahadi** [comment] 2017-10-27 17:38
i have restarted but still error

**Comment by Raycoms** [comment] 2017-10-27 17:38
can you try /mc colony info yourcolonyid

so we can see the info of it?

2017-10-27 18:38 GMT+01:00 YadiSuryahadi <notifications@github.com>:

**Comment by YadiSuryahadi** [comment] 2017-10-27 17:42
![image](https://user-images.githubusercontent.com/33133865/32117491-c27bb5e4-bb78-11e7-85bf-b335ca81556f.png)
please

**Comment by Raycoms** [comment] 2017-10-27 17:43
This is very strange and seems to happen very rarely, in most cases it went
away after restarting until now.
You could try /mc colony addOfficer 1 that might give you the rights. But
besides that, after refresh didn't work, I'm out of ideas.

2017-10-27 18:42 GMT+01:00 YadiSuryahadi <notifications@github.com>:

**Comment by YadiSuryahadi** [comment] 2017-10-27 17:46
OK worked, at least i can continue my colony
Thanks

**Comment by FirzenDark** [comment] 2017-12-16 05:42
I experienced the same issue but realise only after I applied the command /mc colony addOfficer 1 that I'm logged in with the wrong minecraft profile.

**Comment by Bedrok4** [comment] 2018-06-03 10:53
I have the same problem, but I play with sister at LAN. We tried this tutorial , but only the sister have the permision (she made the colonie).

**Comment by twipz333** [comment] 2020-02-06 23:12
same issue on LAN

**Comment by Pietinguy** [comment] 2020-05-30 23:02
I have a similar problem but is seems to have counted me as a neutral when previously I had been the Owner. I am playing on a LAN world with friends.
