### ISSUE TITLE
[BUG] <Builders break hut for constructions>

### ISSUE THREAD

**Issue by Iksayne** [ldtteam/minecolonies#8781] opened 2022-11-22 18:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1088

### Structurize Version

1.0.1088

### Related Mods and their Versions

All the mod 8-0.1.10

### Current Behavior

Try to build a restaurent in my serv. I place the bloc and lauch the construction, afford all materials needed in the builder hut rack but they go break the hut for ressources. 
I'll try with diffrerent builder or to fire and hire or recall them but nothing.

When i want them to construct restaurant they break hut. 
And for other construction like guard tower, i don't have the problem 

### Expected Behavior

Normaly then pickup all block in the hut rack ante go build the construction without breaking others 

### Reproduction Steps

1. construct a hut 
2. place a restaurant 
3. chose a builder for the construction 
4. Let him go break his hut 

### Logs

no log for this the game don't crash

**Comment by MotionlessTrain** [comment] 2022-11-22 18:24
Where did you place the restaurant relative to the builder's hut?

**Comment by Raycoms** [comment] 2022-11-22 18:24
Which style?

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by MotionlessTrain** [comment] 2022-11-22 18:24
And did you by accident click "Deconstruct" in the build options?

**Comment by Iksayne** [comment] 2022-11-22 18:28
1 I'ts at 26 blocks from the hut 
2 in nordic style 
3 I'll try 5 or 6 time wither different builders because it seemed absurd to me, so no i don't think i click on deconstruct

**Comment by MotionlessTrain** [comment] 2022-11-22 18:44
Did you use the build tool to place the restaurant, and did you look at the preview?

**Comment by Iksayne** [comment] 2022-11-22 18:49
yes i do it for all my construction to avoid overlap, and where i prefrer to place it

**Comment by Raycoms** [comment] 2022-11-22 20:10
Canyou make a screenshot?

**Comment by Iksayne** [comment] 2022-11-22 20:38
![2022-11-22_21 32 15](https://user-images.githubusercontent.com/118845285/203415910-0f097146-664d-4ecf-9334-f5d14367c0b1.png)
![2022-11-22_21 32 53](https://user-images.githubusercontent.com/118845285/203415929-470b55a3-eb39-491d-9483-975c4841b55d.png)
![2022-11-22_21 32 56](https://user-images.githubusercontent.com/118845285/203415942-be6a680b-9b57-425a-b996-360b1cea9ea2.png)
![2022-11-22_21 34 19](https://user-images.githubusercontent.com/118845285/203415965-4a9a5041-0920-451a-a03b-30cd8a00bcc8.png)
![2022-11-22_21 33 45](https://user-images.githubusercontent.com/118845285/203415950-bdbad4d3-e756-45a4-98d0-14566323bf69.png)
![2022-11-22_21 33 59](https://user-images.githubusercontent.com/118845285/203415952-d86c2ed0-0343-4744-ae08-8b3560cc52cd.png)
![2022-11-22_21 34 08](https://user-images.githubusercontent.com/118845285/203415956-6e8577cf-74cf-407f-b600-192d2e8d5bb7.png)
![2022-11-22_21 34 12](https://user-images.githubusercontent.com/118845285/203415960-f71d0f3b-954a-4f52-8218-30980e251780.png)

Here i'll try to build town hall and same problem 

In screens shot we can see in hut rack's and il build hut options all ressourcres are afford. but he don't take them he go outside and break the roof of his hut

**Comment by Iksayne** [comment] 2022-11-22 20:40
i'll try to give him directly in his inventory all ressources but he continue to take it on other constructions

**Comment by Talyda** [comment] 2022-11-22 20:44
What level town hall and builder is that in the screenshot?

**Comment by Iksayne** [comment] 2022-11-22 20:47
town hall it level one and builder level 2

**Comment by Iksayne** [comment] 2022-11-22 20:49
oh wait ! can you explain me how we can escape of the schematic and see all the preview of the construction and next to return on it ? I think something is wrong with

**Comment by Talyda** [comment] 2022-11-22 20:50
I think you have the buildings too close together, I am trying to recreate this image:
https://user-images.githubusercontent.com/118845285/203415929-470b55a3-eb39-491d-9483-975c4841b55d.png
in a game, but I can't figure out what the building is that they are tearing apart.

**Comment by Talyda** [comment] 2022-11-22 20:52
If you use the build tool and bring up a preview of any other building, and move it close to the ones you have placed already it will bring up the preview of the ones you have placed. You can then see the white and blue lines that designate the outer edges of those buildings

**Comment by Iksayne** [comment] 2022-11-22 20:55
i think the restaurant is too close of the hut but i can't verificate, now when i click on the restaurant block my game crash x)

**Comment by Talyda** [comment] 2022-11-22 20:56
You're not using optifine are you? If so disable it and try again =)

**Comment by Iksayne** [comment] 2022-11-22 21:00
it's not optifine i'll try to do two preview in the same time and i'll place a construction bloc in same time. i think the game don't like it. 
I will try do break the block istead of picked it up

**Comment by Raycoms** [comment] 2022-11-22 21:04
Probably easiest to move this to discord.minecolonies.com for the support chat and I'll close this in the meanwhile as the problem is the overlap between the two buildings (way too close)

**Closed as completed by Raycoms** 2022-11-22 21:04 UTC
Labels: Bug
