### ISSUE TITLE
Supply ship BUG in version 0.13.456

### ISSUE THREAD

**Issue by Bart-Roels** [ldtteam/minecolonies#6125] opened 2020-11-20 19:26 UTC
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.456-ALPHA-universal
- Structurize Version:  0.13.69
- Related Mods and their Versions: /

## Expected behavior

That the ship is placed correctly

## Actual behavior

m trying to land my ship in the middle of the sea but this doesn't work. Me and my friends already noticed this at the beginning of the game, but then we thought our place was too small. The game continuously says that there are blocks in the way. Also I have every bit of kelp deletes in the environment but this still doesn't work. On the screenshot you can see that the ship is placed around the beach. I have also tried this in the middle of the sea, but it doesn't work.
![image](https://user-images.githubusercontent.com/55732964/99840713-5b697680-2b6d-11eb-936f-7cba4f7ca347.png)
![image](https://user-images.githubusercontent.com/55732964/99840777-763beb00-2b6d-11eb-8495-0cfb89d90262.png)
![fdsfds](https://user-images.githubusercontent.com/55732964/99840875-9d92b800-2b6d-11eb-816f-06d3a2a2b817.png)
![image](https://user-images.githubusercontent.com/55732964/99841103-ef3b4280-2b6d-11eb-9271-f4ecace289e4.png)
![image](https://user-images.githubusercontent.com/55732964/99841181-0d08a780-2b6e-11eb-8d3b-625030f3a734.png)

## Steps to reproduce the issue

You can try to place a ship. I am unable to place the ship. While running the latest versions
1. Find or get a supply ship 
2. Remove the kelp and place the ship 
3. You will see that the ship is not being placed 

### Logs

- latest.log: /
- crashlog: /

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Justen-N** [comment] 2020-11-20 19:53
I was prepared to close this because your listed version on the title is way off, but we'll take a look.

**Comment by Justen-N** [comment] 2020-11-20 19:55
Actually, will you update your structurize version? It looks like its behind.

**Comment by Bart-Roels** [comment] 2020-11-20 21:59
Sorry man I made a typo, I typed 69 instead of 96. I DO have version 0.13.96. for structurize and for mine colonies 0.13.456

**Comment by Justen-N** [comment] 2020-11-20 22:42
Okay, can you post a latest.log that has the attempt to place recorded in it?

**Comment by Raycoms** [comment] 2020-11-21 11:36
![2020-11-21_08 35 35](https://user-images.githubusercontent.com/6438347/99876290-b6db4900-2bed-11eb-8d7c-7effadd7b135.png)

100% sure that this is not a bug of us. I placed numerous ships and it worked fine, did you double check if all those blocks it says in the message are vanilla water?

**Comment by Bart-Roels** [comment] 2020-11-21 11:45
Yes I am sure. Didn't change or modify any modpack, add or edit extra mods. Also tried with different resource packs. But does not work. I have already removed modpack and updated it again, but still not working.
![image](https://user-images.githubusercontent.com/55732964/99876521-7ed90380-2bf7-11eb-9ede-46123ca4becb.png)

**Comment by Bart-Roels** [comment] 2020-11-21 11:47
> Okay, can you post a latest.log that has the attempt to place recorded in it?

[latest.log](https://github.com/ldtteam/minecolonies/files/5577548/latest.log)

**Comment by Bart-Roels** [comment] 2020-11-21 11:53
This works perfectly on single player! Only at the server side level does everyone from our server receive an error. The server is also running the latest version, so I wouldn't, I  know what to do.
![image](https://user-images.githubusercontent.com/55732964/99876648-69180e00-2bf8-11eb-9468-88c7a5b17b62.png)

**Comment by Raycoms** [comment] 2020-11-21 11:55
Server/client are running the same version?

**Comment by Bart-Roels** [comment] 2020-11-21 12:19
Yes! 
![image](https://user-images.githubusercontent.com/55732964/99877084-f4df6980-2bfb-11eb-8a59-2fdf3556c3fc.png)

**Me:** Running server and client he same version
**Friend:** Yes
**Me:** alright!

They both also get this error.

**Comment by Raycoms** [comment] 2020-11-21 13:37
fixed....

**Closed as completed by Raycoms** 2020-11-21 13:37 UTC
Labels: Bug, Awaiting Response
