### ISSUE TITLE
Library - automatic hiring mode

### ISSUE THREAD

**Issue by Nightenom** [ldtteam/minecolonies#2792] opened 2018-08-16 09:19 UTC
From discord:

> fake dreams:
> plz can you make auto hire to jobs to work like if no work go to library .. if new build create take 1 from library automatic to work

I.e. use the library as a stack for workers, if a new job gets created take a citizen from library instead of unemployed list

**Comment by marchermans** [comment] 2018-08-16 11:37
As of now this is impossible by design. The library is not ment to be used in this fassion neither is the Automatic assigning of jobs. The library is a later stage building, as such any player should already be manually assigning citizens to jobs anyway, and the building can then be used to train useless citizen before they are assigned a job.

It requires some planning ahead of time which citizen should visit the library and which should not.

I can see the appeal for it to automatically grab all citizens, the problem is that the auto assigning mechanism does not autofire. Meaning once assigned to the library by the system, there is no way for it to hand the citizen off to a building were the worker is needed. This would confuse a lot of people, hence the decision was made to keep the library in manual mode.

**Comment by Raycoms** [comment] 2018-08-16 11:39
Actually I think it's not even difficult, but I believe the library is
really a building for manual assigning

**Comment by Nightenom** [comment] 2018-08-16 11:42
Yeah, that makes sense, but there will be lazy ppl and it will be something like: Colony.has(library) && !manualHiring -> remove one worker from the library and assign it to the new building, and assign one unemployed to fill the library

**Comment by Nightenom** [comment] 2018-08-16 11:43
Also now in automatic mode library works as a bin since you can't do anything with it

**Comment by Nightenom** [comment] 2018-08-16 11:54
Or just disable automatic hiring for the library and try to explain the system in wiki/guidebook

**Comment by Degonsky** [comment] 2018-12-23 12:29
Because of that desicion, library essentialy breacks auto-hiring mode for colony, since it can host a large amount of colonists. Because of the raid I once lost a deliveryman, cook and a farmer, and instead of taking normal worker's place or guard's towers, all new citizens were filling library, town were paralyzed and defenceless untill I came back and discovered this.

At least disable auto-hiring ctitzens in to library.

**Comment by Raycoms** [comment] 2018-12-23 13:08
Yeah we got it planned to be able to select auto hiring per building. (The
mode) instead of global in the townhall.

Am So., 23. Dez. 2018 um 10:29 Uhr schrieb Jinn <notifications@github.com>:

**Closed as completed** 2019-03-24 11:54 UTC
