### ISSUE TITLE
Scanning a Large Area Disconnects the Player

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#723] opened 2017-03-21 06:22 UTC
### Minecolonies version

version 0.6.3125-1.10.2

### Expected Behavior

- To be able to scan a large area

### Actual Behavior

- After scanning a large area, I was sent to a '_disconnected from world_' screen from my singleplayer world.

### Steps to reproduce the problem

1. Scan a large area
2. Confirm the scan and then get disconnected from the world.

**Comment by Raycoms** [comment] 2017-03-21 11:53
That's a known bug due to the message size limit. We're already working on that.

**Comment by WenXin20** [comment] 2017-03-21 12:51
Ok, thanks

**Comment by xavierh** [comment] 2017-03-24 09:02
@Raycoms Are you referring to my branch ?
I haven't touch the scanning part. Also as it is in single player, I am not sure what is causing this.

I don't think the issue should have been closed.

**Comment by Raycoms** [comment] 2017-03-24 12:52
I thought you worked on the transfer between to the client as well?

2017-03-24 6:02 GMT-03:00 xavierh <notifications@github.com>:

**Comment by Raycoms** [comment] 2017-03-24 13:21
Could you then use the compression and way you transfer it to the server as well to transfer it from server to client side on the single player?
This is where the crash happens atm.

**Comment by xavierh** [comment] 2017-03-24 13:27
Only working on transferring schematics from client to server and server to client, not on the scan part. However I can add the same compression to it.
I will reopen the issue and assign it to me as a reminder.

However in the present case, the error occurred in SP which AFAIK does not use any network transfer. Not too sure why it is crashing here.

@WenXin20 could you submit the log file ?

**Comment by Raycoms** [comment] 2017-03-24 13:28
It is crashing because it still has to transfer things from server to client side even in singlePlayer. (The creation of the nbt happens on the server and we have to send it to the client)

**Comment by marchermans** [comment] 2017-03-24 15:58
Their is virtually no limit to the packet size in SSP
The packet size limit in SMP comes from the packet type Minecraft configures Netty with.
 It is something around 32 kB if i am not mistaken. However for SSP that packet type is not used, and no limit is actually implemented

**Comment by Raycoms** [comment] 2017-03-24 17:48
Yeah but we send messages in ssp. We could detect if we are in a ssp game
and then simple directly store it but the forge guys said there is no
reliable way for this

2017-03-24 12:58 GMT-03:00 Orion <notifications@github.com>:

**Comment by Raycoms** [comment] 2017-03-24 17:48
because of lan games etc

2017-03-24 14:48 GMT-03:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by xavierh** [comment] 2017-03-24 18:39
I thought we had a isDedicatedServer method or  something like that.
Regardless of that we can avoid the crash at least.

**Comment by Raycoms** [comment] 2017-03-24 18:44
The problem is that in the case of lan games that doesn't work very well ,
regarding forge.

2017-03-24 15:39 GMT-03:00 xavierh <notifications@github.com>:

> I thought we had a isDedicatedServer method or something like that.
> Regardless of that we can avoid the crash at least.
>

**Comment by marvin-bitterlich** [comment] 2017-04-18 09:42
closing this as not currently possible

**Closed as completed by marvin-bitterlich** 2017-04-18 09:42 UTC
