### ISSUE TITLE
[BUG] Builder AI broke after he finished a deco building

### ISSUE THREAD

**Issue by ShinyNeko** [ldtteam/minecolonies#8705] opened 2022-10-12 19:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1068-ALPHA

### Structurize Version

1.19.2-1.0.457-ALPHA

### Related Mods and their Versions

Forge: 43.1.27
BlockUI: 1.19-0.0.64-ALPHA
Domum Ornamentum: 1.19-1.0.60-ALPHA
Multi Piston: 1.19-1.2.16-ALPHA

### Reproduction Steps

Builder finished the player housing Asian1
then the builder said this (see image)
![javaw_DwQxNlLSbW](https://user-images.githubusercontent.com/42703578/195429309-ca897ded-f912-48d1-b42b-27f8940a1f5c.png)

### Logs

https://pastebin.com/gLfnaKZ5

### Anything else?

This are all the other mods i use in the same pack i made myself on curseforge: https://pastebin.com/UgiAnUiW

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment] 2022-10-12 20:02
It looks like the decoration controller assumed older decorations always had four (or more) component in their path. That is not the case for player houses (as they didn't have a style before the build tool changes. Asian was just named after a style as the only one), and so it tries to find the upgraded schematic in Minecolonies Original instead

**Comment by ShinyNeko** [comment] 2022-10-13 16:36
> It looks like the decoration controller assumed older decorations always had four (or more) component in their path. That is not the case for player houses (as they didn't have a style before the build tool changes. Asian was just named after a style as the only one), and so it tries to find the upgraded schematic in Minecolonies Original instead

So canceling the build temporarily fixes it i guess?

**Comment by MotionlessTrain** [comment] 2022-10-13 18:05
No, this must be fixed in the code. The problem is that the builder can't complete the build right now, so cancelling and restarting will lead to the same error again

**Comment by MotionlessTrain** [comment] 2022-10-15 13:51
Another, tangentially related bug with decoration controllers in older schematics: When a style has multiple decorations with the same name, the decoration controller may find the wrong one: Building the Fortress -> walls -> corner1 will make the decoration controller think it needs to upgrade to the level 2 corner road instead, while it could know the right path already

**Comment by Raycoms** [comment] 2022-10-15 13:52
it should default to the same folder unless it's backwards compat

**Comment by MotionlessTrain** [comment] 2022-10-15 13:53
Both the player house and fortress corner wall are backwards compat

**Comment by Raycoms** [comment] 2022-10-15 13:54
I  mean backwards in regards to, controller already existing in world

**Comment by MotionlessTrain** [comment] 2022-10-15 13:56
Ah, then it triggers that piece of code too often now

**Comment by Raycoms** [comment] 2022-10-15 13:58
Yes, sth must be wrong in the load function of the controller then

**Comment by MotionlessTrain** [comment] 2022-10-15 14:00
In case it detects the schematic hasn't rescanned, it parses the path it already had. I tried to change it to use the new code in that case, but I noticed that `this.schematicName` may have the old path in it. So that part may need to be changed to take the last part of the path instead of just the name.

I'm not sure whether the compat code gets triggered at all for schematics already in the world

**Comment by ZRunner** [comment] 2022-10-29 22:16
I just ran into the same issue (with the fortress park decoration, `minecolonies-1.19.2-1.0.1077-BETA`), if you want more info feel free to ask. Always happy to help :)

**Comment by DragoBoy50555** [comment] 2022-12-09 04:54
In the new 1.19 update after building up the Builders Hut to max and upgrading the Town Hall, with the Dark Oak Medieval. The A.I seem to break and start to walk back and forward and not do anything.

**Comment by Hp1ayer** [comment] 2023-01-31 02:55
[latest.log](https://github.com/ldtteam/minecolonies/files/10542231/latest.log)

**Closed as completed** 2023-01-31 19:17 UTC
Labels: Bug
