### ISSUE TITLE
Tavern unassigning residents

### ISSUE THREAD

**Issue by the0ryofeverything** [ldtteam/minecolonies#7777] opened 2021-11-17 03:50 UTC
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.133 Alpha
- Structurize Version: 0.13.252 Alpha
- Related Mods and their Versions:

## Expected behavior
 Citizens would remain in tavern without being automatically unassigned

## Actual behavior
 Citizens can be assigned too tavern, but after about 5 minutes two citizens are automatically unassigned from tavern even while housing assignment is set to manual. 

## Steps to reproduce the issue

1.  Assign citizens to tavern
2.  wait 5 minutes
3.  two citizens are unassigned

### Logs

- latest.log:  https://gist.github.com/the0ryofeverything/68b188a707094ecaa132877352843476
- crashlog: 

### Notes
 Tavern is level two. Does not matter which citizens are assigned, as issue happens to any citizens assigned. Also is a server.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment] 2021-11-17 10:34
Are they removed from it, or assigned to other housing?

**Comment by the0ryofeverything** [comment] 2021-11-17 19:30
They are removed from it. They sit in town hall complaining they don’t have a house.

**Comment by Raycoms** [comment] 2021-11-17 19:56
I can't reproduce this, can you send me your world/export your colony with mc colony export

**Comment by the0ryofeverything** [comment] 2021-11-17 22:36
https://drive.google.com/file/d/1FVkkIEEV5_vMPBJFwTy47gldZvPQa0pz/view?usp=sharing

Not sure if it matters but I am also playing on a modpack, I just manually update mine colonies when new versions release.

**Closed as completed** 2021-11-17 23:14 UTC
Labels: Bug
