### ISSUE TITLE
[BUG] minecolonies-server.toml changes keeps resetting upon loading of the save

### ISSUE THREAD

**Issue by xarkore** [ldtteam/minecolonies#9514] opened 2023-10-22 22:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.265-BETA

### Structurize Version

structurize-1.20.1-1.0.648-BETA

### Related Mods and their Versions

![modlist_2023](https://github.com/ldtteam/minecolonies/assets/69495758/03adea92-273f-4a53-adc7-63c02643ef58)

### Current Behavior

Making changes to minecolonies-server.toml gets reverted to the default numbers after loading a save.

### Expected Behavior

The changes made to minecolonies-server.toml doesn't get reverted to default after loading a save.

### Reproduction Steps

1. Install forge and the mods from the modlist
2. Make changes to minecolonies-server.toml, minimumnumberofnightsbetweenraids is this case 
3. Launch the game and load a previously played save
4. Close the game
5. Open minecolonies-server.toml and observe the changes reverted to the default values
![minecolonies_before](https://github.com/ldtteam/minecolonies/assets/69495758/ccfcfc7f-7073-4589-9bad-ff37002afaa8)
![minecolonies_after](https://github.com/ldtteam/minecolonies/assets/69495758/45996495-65ca-459e-b9de-5f1b5c39eb54)

### Logs

https://pastebin.com/TgArG7UA

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment] 2023-10-22 22:43
Just adding to this, I tested with the same versions of minecol + dependencies, and it worked fine.
I think they also tested with just minecol + dependencies, and it still changed their file. I sent them my correctly changed config, and it set it back to default.
And they are using vanilla launcher

**Comment by Raycoms** [comment] 2023-10-23 05:46
We use the default config system, something on forge side must be amiss then, I will close this as cant reproduce for now. And maybe check different forge versions?

**Closed as completed by Raycoms** 2023-10-23 05:46 UTC
Labels: Bug
