### ISSUE TITLE
client crash when placing supply camp or ship

### ISSUE THREAD

**Issue by TheMrCaveman** [ldtteam/minecolonies#7907] opened 2022-01-05 19:18 UTC
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.16.5-1.0.309-release
- Structurize Version: 0.13.252-ALPHA
- Related Mods and their Versions: 

## Actual behavior

As soon as anyone tries to place any supply camp or ship their client crashes

## Steps to reproduce the issue
make a supply ship or camp and try to place it.

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

This is all the mods 6  modpack

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment] 2022-01-05 19:27
https://github.com/ldtteam/minecolonies/issues/7885


"This is caused by tasgon/observable#23 and can be fixed by updating Observable."

**Closed as completed by Raycoms** 2022-01-05 19:27 UTC
Labels: Bug
