### ISSUE TITLE
[BUG] Warehouse's minimum stock menu is completely messed up

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies#8144] opened 2022-03-13 09:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.1-1.0.494-ALPHA

### Structurize Version

structurize-1.18.1-1.0.352-ALPHA

### Related Mods and their Versions

no

### Current Behavior

Cannot delete these slots, furthermore, you cannot register new stacks, and when the new slot appeared, it cannot be deleted either.
Here's my attempt to ask for 10 stacks of fishing rods, andesite blocks showed up instead.
![2022-03-13_08 32 18](https://user-images.githubusercontent.com/92203672/158053629-2fd2dcd9-dff6-4f8b-9c88-e90aaccbb368.png)
![2022-03-13_08 33 16](https://user-images.githubusercontent.com/92203672/158053632-788141cb-faf5-45c2-ae8f-6f74ea7ee401.png)

### Expected Behavior

The menu works as normal like every other buildings

### Reproduction Steps

Build any warehouse I guess, mine was Nordic

### Logs

https://gist.github.com/pantsguyapp/839634055c6a2d156ff0e06d865d4132

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment] 2022-03-13 09:40
Duplicate of #8140

**Closed** 2022-03-13 09:42 UTC
Labels: Bug
