### ISSUE TITLE
Builder STILL Not building

### ISSUE THREAD

**Issue by Logicless36** [ldtteam/minecolonies#7051] opened 2021-05-01 02:39 UTC
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context  0.14.134

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.134

### Logs

- latest.log: https://gist.github.com/Logicless36/bf1bcfec16190bf3591294e46cb28254

## Steps to reproduce the issue / details

 Build Town hall 1 with MedSpruce Alternative. Builder acts like its off duty, doesn't request...

Just reporting the AI/building issue. 

### Notes

Only time I've had this issue is with MedSpruceAlt Town Hall. I have restarted the server. fired then hired, cancelled and requeued, manually finished it myself, fed them, gotten their tools repaired. Nothing worked

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment] 2021-05-01 02:40
did it say in chat they started building?

**Comment by Logicless36** [comment] 2021-05-01 02:41
> did it say in chat they started building?

yes, however they sat at their station for 2 minutes, and wandered off

**Comment by ravenbuilder934** [comment] 2021-05-01 02:41
are others working?

**Comment by Logicless36** [comment] 2021-05-01 02:42
> are others working?

Hes the only one I have with a job so far, but the other AI are doing the usual, sleeping, eating, complaining etc.

**Comment by ravenbuilder934** [comment] 2021-05-01 02:43
if you right-click him and hover over the icon, does it say Working?

**Comment by Logicless36** [comment] 2021-05-01 02:44
yes

**Comment by Logicless36** [comment] 2021-05-01 02:45
My only idea is theres some kind of item that she is unable to request. 
Ex. In the old version I used to play they couldn't request torches
Possible new thing could be an outdated item from the schematic, like a removed/changed block?

**Comment by Logicless36** [comment] 2021-05-01 02:47
Sometimes on a build requeue they will go on a spree of cutting items down, like doors or the campfire (not every block just those)

**Comment by ravenbuilder934** [comment] 2021-05-01 02:48
eh, those schematics *just* got rescanned so I doubt that's it.
can you try a different build order? e.g. upgrading her hut?

**Comment by Logicless36** [comment] 2021-05-01 02:50
She immediately went to start, and is now landscaping

**Comment by ravenbuilder934** [comment] 2021-05-01 02:51
okay, wait and see if she finished that

**Comment by Logicless36** [comment] 2021-05-01 03:04
> okay, wait and see if she finished that

As soon as the breaking of blocks was done, she stopped working, and began doing the same thing  -- Fired and rehired and she got back to work

**Comment by Logicless36** [comment] 2021-05-01 03:14
She successfully built the whole thing with only that one freeze up

**Comment by ravenbuilder934** [comment] 2021-05-01 03:15
what if you restart the previous build order now?

**Comment by Logicless36** [comment] 2021-05-01 03:17
She says she has started the build, and it says the one block missing: Campfire 1/1 (I put it in there after she broke it) and then she wanders off
(if I leave the doors open, she breaks them, and doesn't pick them up unless I give it to her, she will replace them eventually)

**Comment by Logicless36** [comment] 2021-05-01 03:18
The only reason the campfire, ladder, carpets and torches were placed was because I did it manually after this issue started

**Comment by Raycoms** [comment] 2021-05-01 12:14
Any error showing up in the log?

**Comment by Logicless36** [comment] 2021-05-01 15:23
> Any error showing up in the log?

Nothing My new server only shows stuff like posted in the githut above

**Comment by ghost** [comment] 2021-05-03 05:26
maybe you did not setup it properly the first step is to place bulding next is build options in the building and at the side there is a builder: click that and select builder and it will start or maybe they are hungry or there need someting

**Comment by Coraline77447** [comment] 2021-05-16 07:01
I have the same issue but it's happening with my second builder, I have more than one builder but my second one ain't doing anything and he ain't accepting the build request for Swineherd's Hut - Birch while my first builder is doing what he's supposed to do and is currently upgrading Cowhand Hut - Wooden from 2 to 3 but my second builder ain't building Swineherd's Hut - Birch. I've literally tried everything to get him to work and he's refusing to work...
Tried to downgrade both MineColonies and Structurize but I can't get Structurize 0.13.167 since I can't find it in the files section...
So I won't be playing with MineColonies till the builders (probably as of their AI) gets fixed....
Haven't been playing with MineColonies for at least 2 weeks since my issue started and I really want to keep playing with the mod but without a second builder to get things done quicker then I don't want to keep playing till the issue is fixed, doubt that hiring a third builder would help things any and what if the third builder does nothing just like my second builder? I'm not takin that chance....

**Comment by Talyda** [comment] 2021-05-16 10:29
There was a fix to the builder in the past day or so. You need to click the "view all" button on the files page on curseforge to get them to show them all

**Comment by Coraline77447** [comment] 2021-05-21 09:40
Davion (My second builder) is still doing nothing in MineColonies 0.14.167...
I can't really remember what version it was that I've tried to see if the builder was fixed but that's not the case for me since my issue is still on going... 
If the builder was fixed in 167 or between 167 and the latest version (169) but I'm still experiencing technical difficulties with Davion the builder then that might mean that I'll have to make a new world and start all over...
Even tho I've made so much progress already and haven't constructed a university yet (since I wanna construct/build all of the structures that doesn't require the university and research at a university first)...
I doubt that the latest version would fix my second builder whether my second builder is male or female and what if my first builder starts doing the same then I won't be able to do anything at all except for upgrading I guess...
If I were to continue to play on the world that has MineCalonies on it then I'll be stuck with my one and only builder, Allister...
So I think I may have no choice but to restart and make a new world so that my issue would be resolved but I'm not gonna do so for now since I'm currently doing other things in a different modded world/adventure...
Sorry for continuing to comment on this even tho the issue may have already been fixed in general and for how long my message is....

**Comment by marchermans** [comment] 2021-05-21 11:11
@Coraline77447 Send us your logs. Make screenshots of your builders UI. Including the request
Also make screenshots of his building. Especially the second page.

Then run the status command (more info on this in the wiki) and screenshot that too.

Then upload all of that here.

**Comment by Coraline77447** [comment] 2021-05-22 10:02
Ok but as I've said above that I'm currently doing other things in another modded world atm but when I feel like coming back to MineColonies then I'll do all of that. 
I'm also suspicious with Allister my first builder that he could be affected as well.
If I were to try to get him to build a structure but the last time I was on that world Allister is upgrading a structure and is requesting building materials but on the second page in the builder's GUI is blank with 50% at the top but when I talk to him he's still requesting the items that he needs to complete his task. 
But I could try to find the log that was created when I came back to that world but I think it would be best if I pay that world a visit once more but when I feel like doin so since like I've said that I'm busy with my Chaos Awakens world atm. 
Btw I won't make yall wait forever for me to provide my important info about this problem so that yall can to fix this mess. Ok

**Comment by Coraline77447** [comment] 2021-05-23 10:06
Alright, I'm gonna pay that world a visit to get the log and some in-game screenshots as of both Davion the second builder and his builder GUI. Btw after that I'm gonna make another world thats similar to the one that I'm visiting and will have the same seed as my Chaos Awakens world in a nice spot next to a river in a savanna biome (if the land mass is large enough for a large scale colony that is...) while I'm keeping the current world I have now so that I dont really have to delete it if you guys manage to get the builder fixed.

Heres the log and screenshots (NOTE: the world "Coraline World 1.16.5 (Modded)" which has this mod in it was created before 0.14.132 and before the latest version):

Screenshots:
![2021-05-23_04 12 48](https://user-images.githubusercontent.com/72243304/119258535-52427c00-bb87-11eb-8983-cb523bf64399.png)
![2021-05-23_04 13 51](https://user-images.githubusercontent.com/72243304/119258537-540c3f80-bb87-11eb-8fa2-1d43d9b638b7.png)
![2021-05-23_04 15 04](https://user-images.githubusercontent.com/72243304/119258548-61c1c500-bb87-11eb-8f9e-37cfa094cbce.png)
![2021-05-23_05 23 43](https://user-images.githubusercontent.com/72243304/119258549-638b8880-bb87-11eb-9e16-85a6ce82ad01.png)
![2021-05-23_05 23 57](https://user-images.githubusercontent.com/72243304/119258551-66867900-bb87-11eb-8968-1a4273434ff1.png)
![2021-05-23_04 14 42](https://user-images.githubusercontent.com/72243304/119258554-68e8d300-bb87-11eb-94f7-2032201f53e0.png)

log:
[2021-05-23-1.log](https://github.com/ldtteam/minecolonies/files/6528011/2021-05-23-1.log)

(btw I have night vision going which is why it seems like it's day time but it's actually night time in some of the screenshots, also the first one is the town hall work tasks, second one is the second builder's hut second page GUI, and the third is Davion's request GUI, also I looked on the wiki for how to see the status but couldn't find what you were talking about so the next best thing that I did was lookin up the commands to see Davion's info, if those two screenshots that shows Davion's info for when he was asleep and awake that's not what you need/asked for then please tell me how to get what you asked me for so that I can provide it to you, please...)

**Comment by Raycoms** [comment] 2021-06-07 11:47
Should also be fixed by now.

**Closed as completed by Raycoms** 2021-06-07 11:47 UTC
Labels: Bug
