### ISSUE TITLE
[BUG]Quarrier isn't working saying "I finished the current quarry I'm assigned to, I need more!"

### ISSUE THREAD

**Issue by minnie1089** [ldtteam/minecolonies#10026] opened 2024-07-11 12:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.605-BETA

### Structurize Version

1.20.1-1.0.742-RELEASE

### Related Mods and their Versions

Forge 47.3.0
Domum Ornamentum 1.20.1-1.0.188-BETA

### Current Behavior

![2024-07-11_12 20 53](https://github.com/ldtteam/minecolonies/assets/67824161/4e21cd5d-ebd7-4cd4-a93b-198eede563f4)
The quarrier just stands at their bed and complains

### Expected Behavior

The quarrier should do their job

### Reproduction Steps

First the quarrier was working fine, then they just stopped, so i tried lots of things, i restarted the npc, i tried switching my miner and quarrier around I tried just firing the quarrier, none of this worked. I then broke the quarry block and replaced it with the build tool in the same place and location. The quarrier mined a bit more, then said that the quarry was finished.
![image](https://github.com/ldtteam/minecolonies/assets/67824161/75a9f78e-3d03-4638-b2b1-5e2d40b845db)

### Logs

Attached on the previous field because I can't remember my ip

### Anything else?

I have lots and lots of log files if you need them but I find cli hard, not sure why I manage a Minecraft server on a VPS.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment] 2024-07-11 12:32
@MotionlessTrain sth must be off with the iterator

**Comment by MotionlessTrain** [comment] 2024-07-11 12:52
Did the quarrier start with the quarry before you updated?

**Comment by minnie1089** [comment] 2024-07-12 08:42
yes, I did update the mod and dependencies on the client and server to try and fix the stopped quarrier, I think this was before I replaced the quarry although I am not entirely sure

**Comment by MotionlessTrain** [comment] 2024-07-12 08:57
Do you remember the version you were on, or updated from, when the quarrier stopped working?
(I'm wondering whether it could be that the version that changed the quarrier logic broke a quarry that was already being worked on)

**Comment by minnie1089** [comment] 2024-07-12 09:38
1.20.1-1.1.591-BETA

**Comment by SensualAvocado** [comment] 2024-07-13 03:01
I'm having a near identical issue. My quarrier just stands at the job block holding an oak trapdoor. Whenever I interacted with them, they complained they couldn't work, or asked when the courier would arrive. I checked and there were 0 active requests for any resource. I fired them, and hired a new colonist. They didn't complain when I interacted with them, but the rest of their behavior was the same, simply standing at the quarry block holding an oak trapdoor.

With the builders goggles equipped, I could hold shift and see where they were trying to place the oak trap door, and they had already placed one in that position, but that's where they were stuck. 

I tried deleting it and letting them place it again, doing so for a few different colonists and nothing changed. I tried building out the quarry blocks myself, or supplying the resources in creative mode (although never 100% because there's not enough storage at the mine). No change.

Some kind moderator and builder in the discord server suggested I update the a handful of mods with link to curseforge for the up to date versions. The following are the mod versions I was using :

- minecolonies-1.20.1-1.1.581-BETA.jar
- structurize-1.20.1-1.0.733-RELEASE.jar
- domum_ornamentum-1.20.1-1.0.186-RELEASE-universal.jar
- blockui-1.20.1-1.0.156-RELEASE.jar
- multipiston-1.20-1.2.43-RELEASE.jar

I replaced the above mods with the following:

- minecolonies-1.20.1-1.1.603-RELEASE.jar
- structurize-1.20.1-1.0.742-RELEASE.jar
- domum_ornamentum (no change)
- blockui (no change)
- multipiston (no change)

After updating, I repeated my previous attempts to solving the issue. No changes.

**Comment by minnie1089** [comment] 2024-07-15 23:15
If it is any help I can send a copy of the world along with a modlist

**Comment by MotionlessTrain** [comment] 2024-07-16 06:44
I haven't been able to reproduce it yet, unfortunately, but I will try again tonight. Building a medium quarry takes a while 😅

**Comment by MotionlessTrain** [comment] 2024-07-16 06:46
A mod list could maybe help. Maybe I can see another mod that conflicts with it in there (the dev environment I'm testing in only has JEI installed)
And/or if you (or someone else) knows how to reproduce this with only minecolonies installed, I would be glad to hear that as well

**Comment by minnie1089** [comment] 2024-07-16 09:14
![image](https://github.com/user-attachments/assets/0c581ce1-5a84-4473-b872-26ee82f3224c)

**Comment by minnie1089** [comment] 2024-07-16 09:15
Can't you use creative to just paste down a quarry?

**Comment by MotionlessTrain** [comment] 2024-07-16 09:18
> Can't you use creative to just paste down a quarry?

I can do the building part, yes, but not the shaft part (because in that case, the quarry would actually be finished). I need to let the quarrier build that part and try to figure out why they suddenly think the quarry is finished whilst they're only on the fifth layer

**Comment by minnie1089** [comment] 2024-07-16 10:17
They did stop originally without saying that the quarry wasn't finished in the old version, they only said it was finished when I updated

**Comment by MotionlessTrain** [comment] 2024-07-16 20:22
I've tried again, going back to version 1.1.593, and creating a medium quarry. I let the quarrier dig half of the first level (as I'm low on time, I don't have time to let them dig to where they are in the screenshot above), and went back to 1.0.607
After recalculating the needed materials, the quarrier happily continued where they left off on the old version

None of the mods in the mod list look suspicious unfortunately

**Comment by minnie1089** [comment] 2024-07-17 00:13
If it would help, I can whitelist you on the server to see the quarrier that is broken, although it wouldn't show how they got to that state.

**Comment by MotionlessTrain** [comment] 2024-07-17 06:29
I don't think that would help. I want to see what exactly happens when it gets in that state, and I can't login from the dev environment (where I have added extra logging) to the server (and the logging wouldn't work anyway when it is not on the server)

**Comment by Raycoms** [comment] 2024-07-17 06:35
> If it would help, I can whitelist you on the server to see the quarrier that is broken, although it wouldn't show how they got to that state.

Could you do a mc colony export of the colony in question?

**Comment by minnie1089** [comment] 2024-07-17 07:55
How would I go about doing that?

**Comment by Raycoms** [comment] 2024-07-17 08:05
It's a command to run in the server console which exports the colony chunks

**Comment by minnie1089** [comment] 2024-07-17 11:50
[colony1Export.zip](https://github.com/user-attachments/files/16264952/colony1Export.zip)
The quarry is at -461 65 -810
The quarrier's mine is at -425 69 -781
The quarrier's residence is at -488 64 -799
The quarrier is called Esme C. Corbett
The quarrier's colony is "hah a balls"
hopefully this helps

**Comment by MotionlessTrain** [comment] 2024-07-17 20:51
> I then broke the quarry block and replaced it with the build tool in the same place and location. The quarrier mined a bit more, then said that the quarry was finished.

How much did they mine more? A couple of blocks, half of a layer, one layer, a couple of layers?

**Comment by minnie1089** [comment] 2024-07-17 22:32
half a layer

**Comment by MotionlessTrain** [comment] 2024-07-18 19:41
I'm starting to get really confused about this.
I opened the world, and replaced the quarry that was reported as done, by constructed pasting a new one over it. I reassigned Esme to it (firing her from the other quarry she wanted to start working at), and let her continue for a while. She built one and a half layers without any issue (before I closed out of the world)

![2024-07-18_21 38 21](https://github.com/user-attachments/assets/3f3a8885-ec14-4a79-b577-5c01411e3908)

So either the small fixes I made along the way (I noticed some things that could be optimised) apparently fixed the issue, or it is a very weird mod issue

**Comment by minnie1089** [comment] 2024-07-27 20:02
Issue still seems to be problematic, am on the latest version and updating caused the quarrier to do a bit more and then stop
![2024-07-27_20 00 01](https://github.com/user-attachments/assets/7121555a-f7a8-4fbd-b8bd-36f8d39adfca)
Could it be related to it running on a server, with all the issues that would entail?

**Comment by Raycoms** [comment] 2024-08-09 10:56
solved

**Closed as completed by Raycoms** 2024-08-09 10:56 UTC
Labels: Bug
