### ISSUE TITLE
[BUG] Can't build Composter in Prominence II modpack

### ISSUE THREAD

**Issue by w3ricardo** [ldtteam/minecolonies#9511] opened 2023-10-22 00:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.265-BETA

### Structurize Version

1.20.1-1.0.655-BETA

### Related Mods and their Versions

[modpack] Prominence II Forge 1.3.6
I get the same error with the version of MineColonies in tghe modpack, the latest release version and the latest beta version.

### Current Behavior

Game crashes when I try to build a Composter Building from MineColonies. I can craft the item and place it, but when I click on Build Options it crashes, before showing the materials for the building, before I click on Build. I am using the Caledonia layout pack.

### Expected Behavior

It should show the blocks needed to build the Composter.

### Reproduction Steps

1. Change the layout to Caledonia.
2. Place a Composter.
3. Right click on the block.
4. Click on Build Options.

### Logs

https://gist.github.com/w3ricardo/9b6931768a17d6a95e272803544e02ec

### Anything else?

Link to bug at Prominence II:
https://github.com/LunaPixelStudios/Prominence/issues/235

**Comment by IOFortune** [comment] 2023-10-22 07:23
I found a fix for this update ffapi 😏😂, the creator of the mod pack knows about the issue and the fix but hasn’t said anything for some reason 😵‍💫

**Comment by IOFortune** [comment] 2023-10-22 07:24
Ffap = fortified fabric API, the issue is linked to that mod so if you update it the issue goes

**Comment by Thodor12** [comment] 2023-10-22 07:29
You cannot use Forge and Fabric mods at the same time, tell the author to fix that. We are a Forge mod, not a Fabric mod.

**Closed as not planned by Thodor12** 2023-10-22 07:29 UTC
Labels: Bug

**Comment by IOFortune** [comment] 2023-10-22 07:34
Yh but literally updating FFAPI fixes this issue

**Comment by Thodor12** [comment] 2023-10-22 07:36
Still, we do not support any kind of usage with Fabric since we're a Forge mod, hence why I closed the issue.

We can't and will not do anything about this.
