### ISSUE TITLE
Miner stuck in state loop - Caused by mod Improved Mobs

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#3069] opened 2018-11-16 02:13 UTC
### Minecolonies version
Version: minecolonies-1.12.2-0.10.43-ALPHA-universal

### Expected behavior
The miner stays down in the mine and mines

### Actual behaviour
The miner is unable to path correctly, caused by the mod Improved Mobs, and thus gets stuck cycling through all posible states it can be in.

### Steps to reproduce the problem

1. Have Minecolonies
2. Have the mod Improved Mobs https://minecraft.curseforge.com/projects/improved-mobs
3. Observe the miner getting freaked out.

**Comment by sylcai** [comment] 2018-11-16 14:03
![2018-11-16_14 59 43](https://user-images.githubusercontent.com/5037244/48625867-b2ea1000-e9b0-11e8-8bda-a40d46d3f170.png)
![2018-11-16_14 59 44](https://user-images.githubusercontent.com/5037244/48625868-b2ea1000-e9b0-11e8-8203-9fa451f483f0.png)
![2018-11-16_14 59 46](https://user-images.githubusercontent.com/5037244/48625870-b2ea1000-e9b0-11e8-85c6-cc6720437017.png)
![2018-11-16_14 59 47_2](https://user-images.githubusercontent.com/5037244/48625872-b2ea1000-e9b0-11e8-86da-b5da5627c4ed.png)

He also idles sometimes, all this switching happens within 20 ticks. Screenshotting it was very difficult. There are more states in there that he switches in between.

**Comment by sylcai** [comment] 2018-11-16 14:10
It's one of my other mods causing this behaviour.

I am now doing an I/O check to see which one. I have 44 mods, so it might be a while - slowly enabling them all till the miner freaks out.

**Comment by Raycoms** [comment] 2018-11-28 18:11
Is this caused by the amount of mobs down in the mines?

**Comment by SulpherStaer** [comment] 2018-11-28 18:16
This also happened on passive - without any hostile mobs present. I think the mod itself taints the pathfinding, because it allows certain mobs to break blocks to reach their destination.

**Comment by Raycoms** [comment] 2018-11-28 18:20
That's weird, but does it influence other mobs? Does it add any special blocks?

**Comment by SulpherStaer** [comment] 2018-11-28 18:23
No blocks added if I recall - but it alters pathfinding for zombies I think, and several other mobs. I've had it disabled for a while, so I would need to test it out again to find out exactly what it did.

All I know is that when I enabled the mod, the miner got confused.

**Comment by Raycoms** [comment] 2018-11-28 18:26
Are other workers also confused?

Am Mi., 28. Nov. 2018 um 16:23 Uhr schrieb Silvester <
notifications@github.com>:

**Comment by Raycoms** [comment] 2018-11-28 18:27
Okay, I just checked her code and it seems like she overrides all existing pathfinders for this.
Basically killing mod compatibility.
That would have to be fixed on her side, we can't do anything here.

**Comment by SulpherStaer** [comment] 2018-11-28 18:28
That explains it. Thanks for checking it out.

**Closed as completed by Raycoms** 2018-11-28 18:27 UTC
Labels: Bug
