### ISSUE TITLE
[BUG] Request system appears broken 

### ISSUE THREAD

**Issue by Estyria** [ldtteam/minecolonies#8904] opened 2023-01-17 22:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1198

### Structurize Version

1.19.2-1.0.476

### Related Mods and their Versions

Holiday server

### Current Behavior

The clipboard shows a request from the carpenter for paper extra. 
![2023-01-17_13 19 18](https://user-images.githubusercontent.com/95879042/213023822-b1af18e6-72a9-452e-91d7-e3703c3a56e9.png)

The bottom of the request lists the player as the resolver. However, I have a planter, they have a recipe for paper extra, and there was abundant sugar cane in the warehouse. I canceled the request. It came back! I put as much sugar cane in the rack at the plantation as the planter would need and she made the first round of paper extra. The build required more, and again, the carpenter is asking me for it. I tried the same workaround and no luck. The carpenter will not put the request to the planter no matter what I try. I tried taking everything out of her inventory, putting stuff back in, restarting her, punched her in the face, restarted my computer! Nothing worked. Carpenter only wants paper extra from me. 

Now the carpenter is insisting that I make oak planks for them despite them having the recipe for oak planks from oak logs and there being nearly a stack of oak logs in the warehouse.

In the attached log, this was after restarting my computer. I let the request show up, canceled it, then waited for it to pop up again. Hopefully this will include the information you need.

### Expected Behavior

I would expect when a crafter asks for an item, and the other crafters know how to make all of the required items for the end product, that the request would go through to them rather than get stuck on me.

### Reproduction Steps

I'm honestly not sure beyond have a carpenter request a two step item (DO item that needs to be processed from something else first, like plank from log etc) in the request system. 

### Logs

https://pastebin.com/6nWitUcx

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by iFlaxo** [comment] 2023-01-17 22:48
I am also having this issue with the carpenter requesting oak planks to make other things like slabs, fences, etc when he knows how to turn oak logs into planks, and the warehouse has oak logs

I also have this issue with brick extra shingles, my mason knows how to make brick extra, and his custom recipe tab has the correct recipe, but the clipboard says hes requesting brick with the player as the resolver when the warehouse has brick

Ive found that this issue fixes itself(most of the time) if i hit cancel in the clipboard on the request, but it has to be done every time and works about 90% of the time

All the mods 8
minecolonies-1.19.2-1.0.1198-ALPHA
Structurize-1.19.2-1.0.472-BETA
Domum_ornamentum-1.19-1.0.76-ALPHA-universal
BlockUI-1.19-0.0.64-ALPHA
multipison-1.19.2-1.2.21-ALPHA

**Comment by Estyria** [comment] 2023-01-17 22:54
Cancel worked the first time for me, but now it's not.

**Comment by Shadizar** [comment] 2023-01-17 23:04
I hit this a lot nowadays (minecolonies-1.19.2-1.0.1196-ALPHA.jar and for a week or so prior at minimum). Sometimes it is the mason (like deepslate tiles), others the carpenter (planks etc.).
If I cancel it enough (usually 2-5 times) it clears up (not negating Estyria's comment, my experience may not apply to them...but it does work for me (eventually))

**Comment by Raycoms** [comment] 2023-01-18 07:50
Does anyone have a "minimal modded world" where there is a reproduction example?

**Comment by IvanLeviathan** [comment] 2023-01-18 12:32
> Does anyone have a "minimal modded world" where there is a reproduction example?

[original.zip](https://github.com/ldtteam/minecolonies/files/10446207/original.zip)

- Minecolonies minecolonies-1.19.2-1.0.1185-ALPHA.jar
- JourneyMap, FallingTree.
Have the same bug with carpenter, he knows how to make oak planks from oak logs but requesting planks from player resolver.
Cancel request fixing it sometime.

Colony at -91 -30 72

upd:
![image](https://user-images.githubusercontent.com/12871338/213173034-2df5bcb5-9229-412c-97e0-44c7cf0a0d36.png)
Catch it right now

**Comment by Shadizar** [comment] 2023-01-18 16:49
I have a blueprint I put together for a building if you want it feel free to DM me on discord.
* Creative paste in the following huts. I doubt level matters but I picked 5 for builders and 2-3 for forester, stonemason, and sawmill. Townhall and some residential pasted too but probably not relevant to repro. I did this on the newer acacia rework (don't recall the name)
* I then pasted in a warehouse and some couriers (all L3 I think).
* Make sure everyone is hired and working (but, I did tell the forester to zone and set the zone to a treeless area so they'd focus on log stripping only)
* in the simple repro I did not teach any recipes to anyone until they come up in the clipboard...but when I hit the bug in my real playthrough they knew almost all the recipes other than the end DO recipe when it happened to me.
* Using build tool, Assign to Builder the test blueprint (a modified courier with assorted DO blocks). As each request comes to clipboard: If it is a tool, fulfill as you see fit; if it is anything craftable, go and teach it to the relevant crafter (but I did not teach anything to the builders). I taught things containing wood to the sawmill (even when the stonemason could also do it)


For me, canceling 3-4 times when they get confused, they eventually figure it out. 
I probably also have the world save if you want it.
Tested a while ago (when minecol 1196 was the newest avail) on Forge 43.2.0, MC 1.19.2, 
minecolonies-1.19.2-1.0.1196-ALPHA.jar
blockui-1.19-0.0.64-ALPHA.jar
domum_ornamentum-1.19-1.0.76-ALPHA-universal.jar
multipiston-1.19.2-1.2.21-ALPHA.jar
structurize-1.19.2-1.0.476-ALPHA.jar

**Comment by Shadizar** [comment] 2023-01-18 16:51
Notice I did not have JEI in this one, so  recipes were taught via block dragging (a speculation folks had was JEI / mod interactions).

when I hit it in real playthrough, I used JEI to teach. I think that hypothesis is disproven therefore.

**Comment by myKrins** [comment] 2023-01-19 19:10
I can also tell that I'm having this bug at the christmas event server.
Had it with requesting planks, although the carpenter knows the recipe. Now I also have it with stone.
![image](https://user-images.githubusercontent.com/79685815/213537969-d04afadc-3584-49eb-a3a9-3276f0fcfa2e.png)

**Closed as completed** 2023-01-22 12:19 UTC
Labels: Bug

**Comment by Estyria** [comment] 2023-01-24 21:55
This issue is still happening on the holiday server. 

![image](https://user-images.githubusercontent.com/95879042/214429636-c7459eee-a253-49ab-8ba6-e91a82c75f5e.png)

It's always the carpenter! I don't know what their problem is, but they get hung up not forwarding requests to the proper crafter.

**Comment by Estyria** [comment] 2023-01-24 21:56
I have over 2k dark oak logs in the warehouse, and the carpenter has the recipe for planks and makes them all the time for other stuff. But the framed blocks with several steps... not so good.

**Comment by Shadizar** [comment] 2023-01-27 23:52
Still hitting this too, on minecolonies-1.19.2-1.0.1207-ALPHA
Doesn't seem fixed

**Comment by Raycoms** [comment] 2023-01-28 08:30
Only do blocks or all blocks? I might need a

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Raycoms** [comment] 2023-01-28 14:47
I cant reproduce any issues anymore now

**Comment by Shadizar** [comment] 2023-01-28 16:29
Weird...still happening for me...seems less frequent but in playing I'll still hit now and then
1207 alpha

**Comment by Estyria** [comment] 2023-01-29 04:22
Same Shad, same. Less frequent, but still happening.

**Comment by Shadizar** [comment] 2023-01-29 20:18
it even occurs on simple items (rarely)
![image](https://user-images.githubusercontent.com/94550408/215353575-1e92089c-7e59-4584-a868-43edcf5d2a2b.png)

I have 3 builders all of which are doing builds that hit the carpenter, maybe that is a factor? I just can't figure it
