### ISSUE TITLE
Random Observations in 1.14.4 and 1.12.2 versions

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#3923] opened 2019-10-10 04:01 UTC
Hey guys, you MAY be aware of some of these but then again its possible you are not. I have left out things I have seen that have already been reported.

Versions I am working with:

minecolonies-0.10.359-ALPHA-universal
minecolonies-1.12.2-0.10.348-RELEASE-universal

Imgur Gallery:

https://imgur.com/a/4GzQ4zp

1) I am noticing that most of the crafters (blacksmith, stone mason, stone smelter and saw miller) don't seem to want to show up for work at all and haven't seen them do any work when I call them to their buildings.

2) I am seeing a lot of buildings being built with blocks completely missing, most of these seem to be stairs and shingles that turn corners. (1.14.4 version) Please refer to imgur link.

3) I have 4 guards running around my colony and even when I spawn mobs near them they just continue to run around and completely ignore the mobs (1.14.4)

4) I tried to teach the sawmill the recipe to turn logs into planks and the building flat out refused to accept the recipe stating that it was either wrong profession or recipe list was full (1.14.4)

5) Minor glitch in the mod reporting that a citizen has grown up, please refer to imgur link (1.14.4)

6) Barracks will NOT build towers, insists that I upgrade the barracks first and it seems that the towers themselves are defaulting to acacia instead of what the barracks is made from (1.14.4) refer to imgur link.

7) Unable to find WHO can make bows in both 1.12.2 and 1.14.4 versions. tried blacksmith and sawmill and both buildings refused the recipe.

8) this is more a mod compatibility issue perhaps but I taught the cook the recipe for pizza slices in 1.12.2 (Pams 1 cutting board and 1 artichoke) the cook simply stores the cutting board and hands out the artichokes to colonists.

9) DMen stop working completely after a period of time, COULD be related to previous issues but I have observed them simply stop and stand still,

**Comment by fr3akb0y** [comment] 2019-10-10 06:08
1. They are aware of these issues and are currently testing fixes on a non-official version with some testers.
2. Porting to 1.14.4 did something to schematics they need to rescan them once its ready again.
3. Also noticed that don't know about that one.
4. Reportet that myself before and they fixed it. Just Update Minecolonies.
5. I've seen them chatting in discord about it, don't know why nobody fixed it by now >.<
6. They fixed it at some point. Again, just update.
7. Its because there is only 50% wood used in the recipe. I am sure they somehow will include the recipe of a bow in the future, just don't know yet.
8. Probably, but don't know either
9. Never encountered that, so again don't know :P

**Comment by Moobien** [comment] 2019-10-10 06:41
Oh and I forgo to mention EVERYONE runs around waving their left hand.

Fortunately for 4 the dman accepts the recipe

**Comment by Moobien** [comment] 2019-10-10 09:42
Literally just watched a dman stand in the same spot for 5 minutes. Only way to get them working again for a while is to fire and rehire

**Comment by fr3akb0y** [comment] 2019-10-10 10:19
Did you try updating?
Newest Version for 1.14.4: 0.10.424-ALPHA
Newest Version for 1.12.2: 1.12.2-0.10.422-ALPHA
You are a fair amount of updates behind ^^ and if the dman doesn't change that behavior then I don't know the cause (never had that in the last 2 weeks playing straight minecolonies on 1.14.4)

**Comment by Raycoms** [comment] 2019-10-10 10:20
Dman is getting fixed at the moment, most other things should be fixed
already.

Am Do., 10. Okt. 2019 um 07:19 Uhr schrieb fr3akb0y <
notifications@github.com>:

**Comment by Moobien** [comment] 2019-10-10 10:22
@fr3akb0y  - yep. using minecolonies-0.10.415-ALPHA-universal

Are the colonists supposed to avoid roads made with path blocks like the plague? they seem to want to go the long way around cross country to get from one end of town to the other instead of using the paths I put in for them

**Comment by fr3akb0y** [comment] 2019-10-10 10:40
They should still use them, hmm. Maybe something to do with path blocks having a different height? I normally use gravel anyway since they go faster on that. Or maybe if you didnt 'just' placed the waypoints and have them near buildings they got removed by a construction tape(since block placing removes them)? (which is actually kind of annoying >.<)

**Comment by Aelhan** [comment] 2019-10-10 19:01
Concerning your 9th point, i noticed that Dmen systematically stuck when they have some items in their inventory. The bugger items i noticed are : treasure map, suspicious stew and enchanted books. I don't know if other van stuck him, but i am afraid most of 1.13 ans 1.14 items stuck them, i couldn't try with others (it is ok with bamboo anyway)

**Comment by Moobien** [comment] 2019-10-11 05:51
has anyone else noticing that the latest update "minecolonies-0.10.424-ALPHA-universal" turns your colony into 'neverland' where your children NEVER grow up into adults? 3 hours played today and not one of my 4 children have grown up.


On an amusing note. Within 10 mins of me posting this 3 of them decided not to be peter pan anymore lol

**Comment by kreezxil** [comment] 2019-10-11 21:32
i've been reporting this issue, in private, thankfully someone else has it. To that end I posted a feature request with #3928 

Found out from a fellow player that the children must be well fed and well protected for their entire gestation period which appears to be 7 days. Therefore it might be a good idea to corral them (pen them up) so that no pesky hostile and cause them bodily harm. IE, MIGHT AS well make a nursery with beds in it for them to sleep on and make sure the kids have stacks of food on them.

**Comment by kreezxil** [comment] 2019-10-11 21:34
Apparently getting raided resets this. @Raycoms I dont' think that's right have these preconditions on children growing up. War and famine never stopped a child from growing up. It changes their stats tho, like wisdom, intelligence, stamina, charisma. You can imagine the ways, if you can not talk to some people in real life that grew up in wars.

**Comment by Raycoms** [comment] 2019-10-14 17:30
Can you test the dman here:

https://teamcity.minecolonies.com/guestAuth/repository/download/LetSDevTogether_Minecolonies_Branches_Build/31486:id/build/libs/minecolonies-1.12.2-0.10.1270-PERSONAL-universal.jar

**Comment by Moobien** [comment] 2019-10-14 17:40
Will do tomorrow. Btw is there a reason the alt medieval oak cit hut requires 11 beds when upgrading from 2 to 3?

**Comment by Raycoms** [comment] 2019-10-14 17:42
that's another bug, it says more than it needs. =D

**Comment by Moobien** [comment] 2019-10-14 17:43
Lol

**Comment by Moobien** [comment] 2019-10-15 03:24
@Raycoms tried your new jar file and the 1.12.2 dmen seem fine now. However in this version and the latest versions the guards dont go to get food anymore, once they lose 3 drumsticks they stop wherever they are and just stand there. The stonemason appears to be doing his job now too

**Comment by Raycoms** [comment] 2019-10-15 06:15
Food fix in next version

**Comment by Moobien** [comment] 2019-10-15 06:46
I think I found a work around for it though. I built a second cook at the other end of town and they seem to be ok now

EDIT: nope, I was wrong.

EDIT2: working on something for you guys as a way of saying thanks. https://imgur.com/a/Sr6pU0L

**Comment by Raycoms** [comment] 2019-10-18 15:14
Will close this now, we merged a lot of the fixes.

**Closed as completed by Raycoms** 2019-10-18 15:14 UTC
