### ISSUE TITLE
Incorrect display of the Interface on Mac

### ISSUE THREAD

**Issue by vashcheulov** [ldtteam/minecolonies#4119] opened 2019-12-03 15:12 UTC
### Minecolonies version

Version: 0.10.569-ALPHA-universal
Minecraft Version: 1.14.4
Mac Version (if necessary): macOS Catalina 10.15.1

### Expected behavior

- GUI of mod expected to display correctly with visible "Build options", "Citizens " etc.

### Actual behaviour

- Necessary building blocks in townhal, in other buildings and in citizens info don's displayed correctly.  I think, that something cover this interface, because when I change "GUI Scale" options, this invisible cover scales and I can see some "Build options" blocks. 

<img width="1440" alt="Zrzut ekranu 2019-12-3 o 11 20 59" src="https://user-images.githubusercontent.com/42419891/70062996-65563a80-15e7-11ea-8b7d-b804a39b2178.png">
<img width="1440" alt="Zrzut ekranu 2019-12-3 o 11 21 37" src="https://user-images.githubusercontent.com/42419891/70062997-65eed100-15e7-11ea-93cb-dfe1b154468e.png">
<img width="1440" alt="Zrzut ekranu 2019-12-3 o 11 21 56" src="https://user-images.githubusercontent.com/42419891/70062999-65eed100-15e7-11ea-96a7-3ca6541f89a5.png">
<img width="1440" alt="Zrzut ekranu 2019-12-3 o 16 05 42" src="https://user-images.githubusercontent.com/42419891/70063001-65eed100-15e7-11ea-801a-7d328b4e6c51.png">
<img width="1440" alt="Zrzut ekranu 2019-12-3 o 16 06 00" src="https://user-images.githubusercontent.com/42419891/70063004-66876780-15e7-11ea-8440-3d525489c131.png">

### Steps to reproduce the problem

1. Creating a new colony
2. Building a townhall
3. Can't see necessary blocks in "Build options" and amount of citizens in "Citizens" tab of townhall

**Comment by Asherslab** [comment] 2019-12-03 18:48
Duplicate of #3993

**Closed as completed by Asherslab** 2019-12-03 18:48 UTC
