### ISSUE TITLE
Upgrade from mediavaloakalternative town hall 3 to 4 broken

### ISSUE THREAD

**Issue by TheMerced** [ldtteam/minecolonies#5244] opened 2020-06-17 20:33 UTC
Version: mc 0.11.958, 959, 960, structurize 0.10.324

### Expected behavior
Builder finishes placing all blocks and pieces to upgrade the town hall (mediavaloakalternative) from level 3 to 4.

### Actual behaviour
It will pretty much stall when it has 2 complete sets of iron armor, 2 armor stands, 1 sword and 2 item frames left. When I give him everything he sometimes loses the armor pieces, request them again, other times he has them in his inventory and still marks them as missing and still other times he actually builds two armor stands with the whole armor sets behind the throne and still mark them as missing. At that point he runs around the town hall acting as if he was building something with seemingly random blocks from the production but never finishes. I tried, canceling and redoing the build, firing and rehiring even switched between 3 different builders. For new builders I've also seen the built percentage at different levels. The first one had it at 100 % but never completed the build, others I have seen where at 98%, 66%, 0% (as seen on the screenshot) and some even managed to go to negative percentages. I'm guessing it has something to do with the armor stand or armor pieces, the item frames and sword are never used or complained about unless actually missing. So they probably would be built after the armor stands.

### Steps to reproduce the problem
1. Start a new world
2. Place or build a town hall level 3 of the style mediavaloakalternative and a builder, lvl 4 or higher
3. Let the builder upgrade the town hall from lvl 3 to 4
4. Watch as he builds and runs into above problems shortly before the end

I have reproduced this problem in a test world with just MC and structurize and no other mods, it appeared again. However I demolished the town hall hut block and placed a new one in both cases (you need to create a colony before you can place a complete townhall in creative). Not sure if this has anything to do with it.

**Comment by lunadragnstar** [comment] 2020-06-20 05:53
I am getting the same issue, but I'm trying to see if I can force it to work.

**Comment by Raycoms** [comment] 2020-06-20 16:30
Short question, is it possible that you have some banners that are not "plain" ?

**Comment by lunadragnstar** [comment] 2020-06-20 17:04
There are banners on mine, but after I cancelled the build order, and had him build other stuff, when he came back to do the townhall, he placed the banners but seems to be getting stuck on the item frames, armor stands and/or armor. I'll let him go for a bit to see what he does.

**Comment by lunadragnstar** [comment] 2020-06-20 17:10
the problem is, when you try to fulfill the armor, it just comes back to requesting it. I did manage to get him to place it in the barracks by transferring it directly to his inventory when he was close to placing it

**Comment by TheMerced** [comment] 2020-06-20 18:12
> 
> 
> Short question, is it possible that you have some banners that are not "plain" ?

There are some of those in the schematic, yes. But usually he will request yellow ones and change them to the required pattern himself. I've also build and upgraded this exact same town hall in an older game to level 5 without these issues.

I have also tried to make a schematic featuring a simple room with just an armor stand and the same iron armor on it as in the town hall schematic. The builders build this without issues.

**Comment by Raycoms** [comment] 2020-06-21 10:00
@carlansor @lunadragnstar I double checked on this, it seems that the item stands in this scan have old data (probably data from 1.12). That's why they get kinda stuck on this because the data doesn't fit.
So it's #5006

**Closed as completed by Raycoms** 2020-06-21 10:00 UTC
Labels: Awaiting Response

**Comment by carlansor** [comment] 2020-06-22 00:57
i recently modified and rescanned all medieval buildings, main and alternative. Should do it again then
