### ISSUE TITLE
[BUG] Research bug

### ISSUE THREAD

**Issue by Dav1d3011** [ldtteam/minecolonies#8674] opened 2022-09-25 15:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1032-ALPHA

### Structurize Version

1.0.1032-ALPHA

### Current Behavior

I cant start a research when I have all what needed to start it
![Screenshot 2022-09-25 180736](https://user-images.githubusercontent.com/114350241/192151053-b1f4f242-39dd-4807-af9a-d3bb3f776956.png)

### Expected Behavior

how can i fix it?

### Reproduction Steps

idk i do nothing special

### Logs

https://gist.githubusercontent.com/Prometey99/e7dab6ddfc1fb41d617fec0378e7ee62/raw/30bbca77ae68c5817f657b873bd1096a329b16d1/gistfile1.txt

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment] 2022-09-25 15:34
If you are playing the Colony Venture/Minecolonies Official modpack, this is caused by an incompatibility with another mod.
That mod adds NBT data to all tools and armour in your inventory, which makes them different than what the university expects.

Hopefully, in the next modpack update, there will be a fix for this incompatibility

**Comment by Raycoms** [comment] 2022-09-25 15:45
Latest release of the pack fixes this

**Closed as completed by Raycoms** 2022-09-25 15:45 UTC
Labels: Bug
