### ISSUE TITLE
Farmer / Request bug

### ISSUE THREAD

**Issue by Lejoni** [ldtteam/minecolonies#6230] opened 2020-12-10 19:36 UTC
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.510-ALPHA
- Structurize Version: 0.13.102-ALPHA
- Related Mods and their Versions: Minecolonies Official Modpack 2.1

## Expected behavior

Expect Farmer 1 worker to be able to use wood and stone hoe.
And only request up to stone level Hoe.

## Actual behavior

Farmer1 worker requests tools up to level diamond.
And in this case revived iron hoes that he could not use.
Farmer also keept requesting more hoes when given Stone hoes by player.
Only Wood hoe would work.

## Steps to reproduce the issue

1. Build Farmer1 (in my case Medival Spruce)
2. Make sure to have only iron or higher level hoes in warehouse.
3. After farmer recives hoes he can not use. Give Stone hoe he should be able to use.
4. Watch him keep requesting until he gets wood hoe.

### Logs

- [latest.log:](https://pastebin.com/3s9vxsW9) 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Lejoni** [comment] 2020-12-10 19:44
Forgot I was to "make sure to note that you don't have the extended nether backport mod"
No idea what it is. But I have not installed it. So if its not a part of the Official modpack I don't have it.

**Comment by Raycoms** [comment] 2020-12-12 19:05
I just checked into this. But I can't reproduce this. Those diamond etc hoes they are requesting, are those modded hoes? Do you have a mod that adds a lot of modded hoes?

**Comment by Lejoni** [comment] 2020-12-13 04:29
> I just checked into this. But I can't reproduce this. Those diamond etc hoes they are requesting, are those modded hoes? Do you have a mod that adds a lot of modded hoes?

No, I'm using Minecolonies Official Modpack 2.1.
Only added: FTB Backups, FTB Ultimine (Ore excavate mod)

**Comment by Raycoms** [comment] 2020-12-13 08:51
Okay, that includes Tetra then.

**Comment by Lejoni** [comment] 2020-12-13 17:53
> Okay, that includes Tetra then.

There is a mod called Tetra installed. But I did not manually install it. So must be a part of the official modpack.
It does not show any hoes in it tho.

**Comment by Raycoms** [comment] 2020-12-26 09:18
Still happening?

**Comment by ravenbuilder934** [comment] 2021-01-03 00:16
Fixed

**Closed as completed by ravenbuilder934** 2021-01-03 00:16 UTC
Labels: Bug, Bug: Can't Reproduce
