### ISSUE TITLE
[BUG] Select recipe crash

### ISSUE THREAD

**Issue by janisl** [ldtteam/minecolonies#9498] opened 2023-10-20 02:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.247-BETA

### Structurize Version

1.20.1-1.0.653-BETA

### Related Mods and their Versions

1. blockui-1.20.1-0.0.98-ALPHA
2. domum_ornamentum-1.20-1.0.139-BETA-universal

### Current Behavior

Game crashes

### Expected Behavior

Game does not crash

### Reproduction Steps

1. Open UI of sawmill
2. Go to Custom Recipes
3. Go to Teach Recipe
4. Go to Requests
5. Click Select

### Logs

https://gist.github.com/janisl/a1ba7a9df2a75895fc30f8fb8731f76f

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment] 2023-10-20 04:54
Duplicate of #9492

**Closed as completed** 2023-10-20 05:54 UTC
Labels: Bug
