### ISSUE TITLE
Builder confusing items with similar IDs

### ISSUE THREAD

**Issue by OlWeigand** [ldtteam/minecolonies#4414] opened 2020-03-10 21:53 UTC
### Minecolonies version
Version: 1.12.2-0.10.714-RELEASE

### Expected behavior
- The Builder should take the items it needs out of its building chest, then proceed to place them.

### Actual behaviour
- The Builder seems rather dumb when it comes to items that share a numeric ID value, such as different colored banners or slabs made of different wood types. Instead of taking the correct one it needs out of the building chest, it seems to pick one at random, goes to the building site, discovers that it's not carrying the correct item to place, returns to the building chest and picks another one at random. By random chance, it will get things right eventually, but it wastes a lot of time in the process.

### Steps to reproduce the problem
1: Tested on modpack M.C.Eternal version 1.3.4.
2: The issue was most notable when constructing the Medieval Oak Town Hall stage 4 and 5, since it has multiple banners of different colors and also uses multiple different wooden slab types.
3: The issue presumably only occurs when multiple items with similar ID have actually been provided in the building chest. It can (most likely) be bypassed by only providing the builder with what it needs at that moment exactly.

**Comment by Raycoms** [comment] 2020-03-10 23:09
Wondering if it is worth fixing it, since in 1.15.2 those blocks are separate and it doesn't matter anymore =D

**Comment by Raycoms** [comment] 2020-03-10 23:10
Are you sure that he doesn't have the block he needs for the next one to place?

**Comment by OlWeigand** [comment] 2020-03-10 23:28
He does in fact have the correct item, it's just completely random whether he'll grab it or not.

**Comment by Raycoms** [comment] 2020-03-10 23:33
It's because there are two things
1) Specific item grab just when he needs it
2) Random pre item grab for the remaining items

**Comment by OlWeigand** [comment] 2020-03-10 23:37
That's not what I observed, though. Even when the next item in line was a dark oak slab (as could be observed after the fact and by the builder looking like he's holding a dark oak slab), he went back and forth between his hut and the building site multiple times, only to come back with spruce slabs or oak slabs.

**Comment by Raycoms** [comment] 2020-03-11 12:14
Kk, I should be able to check into this tomorrow.

**Comment by OlWeigand** [comment] 2020-03-11 12:16
Thanks. In the mean time I'll do some more testing and see if I can reproduce the issue / give a better report.

**Comment by Raycoms** [comment] 2020-03-11 12:17
Minimal reproduction example is always appreciated.

**Comment by OlWeigand** [comment] 2020-03-11 18:25
Upon re-examination, I suspect that the issue was being caused by server problems. The server I was playing on was having some kind of memory leak problem at the time of reporting, but I can't seem to reproduce the issue in SSP.

**Comment by Raycoms** [comment] 2020-03-11 21:49
this should also not happen anymore in 1.15.2 because blocks are now separated ids. So I think we can close this.

**Closed as completed by Raycoms** 2020-03-11 21:49 UTC
