### ISSUE TITLE
Incapable of creating a second colony

### ISSUE THREAD

**Issue by jakethehit** [ldtteam/minecolonies#6229] opened 2020-12-10 18:42 UTC
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.4
- MineColonies Version:0.13.510-ALPHA
- Structurize Version:0.13.102-ALPHA
- Related Mods and their Versions:AllTheMods6 Modpack version 1.3.3

## Expected behavior

I would expect for my friend to be bale to create a colony on our server after I have created one.

## Actual behavior

We have a small server hosted by Bisect Hosting to play together with one other friend. I created a colony, and then when my friend goes to place his town hall with the builder tool, it crashes the server. If he places the town hall block manually and then hits "create colony" it crashes the server. This is reproducible 100% of the time. He is attempting to create his new colony ~193k blocks from my town hall. Below is the latest crash report.

## Steps to reproduce the issue
Attempt to place a town hall with a build tool after a colony has been created by someone else, or place a town hall manually and try to create a colony after a different colony has been created by someone else.

1. Download AllTheMods6 version 1.3.3
2. Have one person create a colony.
3. Have a different person attempt to create a new colony.

### Logs

- latest.log: 
- crashlog: https://gist.github.com/jakethehit/994cf674bc54d7fb0fa8867e30e044e2#file-crash-2020-12-10_11-58-14-server-txt-L77

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment] 2020-12-10 18:44
This is crashing because creating the colony has to load some chunks and the server doesn't have enough power to support that apparently. How big is the instance? How much RAM does it have?

**Comment by jakethehit** [comment] 2020-12-10 18:50
> This is crashing because creating the colony has to load some chunks and the server doesn't have enough power to support that apparently. How big is the instance? How much RAM does it have?

Not sure about instance size, how do I check that? And we have 10gb of ram. We will try closer together

**Comment by Raycoms** [comment] 2020-12-10 18:51
Oh very strange, might be a problem of ATM being too huge. I think there is a timeout value you can increase in the server to avoid it to crash so fast @someaddons knows I think.

**Comment by jakethehit** [comment] 2020-12-10 18:53
Interesting I hadn't thought of that. If we place them closer together it will not take as long to load the chunks and check for colony boundaries? Increasing the timeout limit so the server has time to do that would be helpful.

**Comment by Raycoms** [comment] 2020-12-10 18:55
Closer together doesn't help a whole lot, you can try to load the chunks around you before placing manually.

**Comment by jakethehit** [comment] 2020-12-10 18:57
We will try loading the chunks before placing the town hall manually.

**Comment by jakethehit** [comment] 2020-12-10 19:07
We tried loading some of the chunks around the area first before my friend placed down his town hall. The server crashes immediately unfortunately.

**Comment by jakethehit** [comment] 2020-12-10 19:09
> Oh very strange, might be a problem of ATM being too huge. I think there is a timeout value you can increase in the server to avoid it to crash so fast @someaddons knows I think.

When you say that ATM might be too huge, how do you mean? And is there anything we can do to mitigate that if that's the issue, other than just using a smaller modpack?

**Comment by someaddons** [comment] 2020-12-10 19:35
server.properties has that timeout setting, its simply crashing because the worldgen of chunks is super slow

> We tried loading some of the chunks around the area first before my friend placed down his town hall. The server crashes immediately unfortunately.

Thats likely the cause then, for some reason those specific chunks take super long to generate, probably world gen/structure mods doing sth slow. Try upping the value in the server properties to like 5mins.
anyway not a minecolonies issues, so gonna close this

**Closed as completed by someaddons** 2020-12-10 19:35 UTC
Labels: Bug

**Comment by jakethehit** [comment] 2020-12-10 19:40
@Raycoms @someaddons so here's what we did: changed the server max tick time from 60000 to 600000. When he placed the town hall down, the server stopped to think and kicked us 90 seconds later due to connection time out, but the server itself did not crash. We both rejoined, and his town hall block was still on the ground where he placed it, and he was able to successfully create his own colony. So far now, everything looks to be working as expected. Thank you for help and suggestions.

**Comment by someaddons** [comment] 2020-12-10 19:52
yea its actually not that uncommon for world generation to be very slow these days, so sometimes the 60s isnt even enough for that specific chunk :D glad its working now
