### ISSUE TITLE
1.15 Builder AI error

### ISSUE THREAD

**Issue by McKitten** [ldtteam/minecolonies#5176] opened 2020-06-08 19:18 UTC
Version: 1.15.2-0.11.957

Expected behavior : Next task loaded in and returning to hut for supplies.
Actual behaviour : Birch Warehouse 2 completed, builder became stationary and an alert was posted above her head, mentioning AI error and reporting it.

Only partial log file posted https://gist.github.com/McKitten/0e838b5233bf74d655bde55a3f8f4310

Original latest.log has multiple loads and mod is not standalone. 
Likely cannot reproduce.

**Comment by Raycoms** [comment] 2020-06-08 19:26
I need a tag for weirdest AI error reported so far.

**Comment by McKitten** [comment] 2020-06-08 19:29
Yeah that builder is essentially dead. She has gone to sleep for the night and not returned to her post the next morning.

**Comment by jan-golda** [comment] 2020-06-08 21:53
Oh, I was about to create issue for exactly the same version. And the problem is similar (kinda?):

My miner went to sleep and there is no way I can wake him up, he is essentially dead.
He has low health and food, but is not eating. 
He has the message that he lacks the sleep despite being in bed for over 4 days.

When I run `/mc citizens info` with his id I get:
```
Desired activity: WORK Current Activity:  Task: EntityAISickTask
```
Should `Current Activity` be empty?

I did not seen any AI error reports from his side, but I had some weird things happening with other citizens. Maybe its connected maybe not, no idea.

**Comment by MatthiasMann** [comment] 2020-06-08 22:15
@Regzand try giving him a carrot and a potato - that might heal him (or a poppy, dandelion and kelp if the carrot/potato didn't help)

**Comment by jan-golda** [comment] 2020-06-08 22:31
> @Regzand try giving him a carrot and a potato - that might heal him (or a poppy, dandelion and kelp if the carrot/potato didn't help)

I tried potato, carrot, poppy, dandelion, kelp and every type of food I have. I there is no reaction what so ever.

I tried to reassign him to the mine, and he moved next to mine block while still laying on his back, and now is laying there instead of in bed

**Comment by Raycoms** [comment] 2020-06-08 23:39
Sick task means the worker is sick and you need a cure

**Comment by ravenbuilder934** [comment] 2020-06-09 13:48
Try honeycomb and golden apple.

**Comment by Raycoms** [comment] 2020-06-20 22:15
Shouldn't happen again.

**Closed as completed by Raycoms** 2020-06-20 22:15 UTC
