### ISSUE TITLE
Builder won't upgrade town hall

### ISSUE THREAD

**Issue by Sweddy** [ldtteam/minecolonies#1848] opened 2017-12-15 13:21 UTC
### Minecolonies version

version 0.8.4908 or curse 1.10.2

### Expected behavior

- Builder upgrades townhall.

### Actual behaviour

- Builder walks over to Builder's Hut and stands still, saying "Waiting for". Pushing Builder away and teleporting her back does not work. Firing and re-hiring Builder does not work. Restarting does not work. Cancelling and requesting upgrade request does not work.
More Info:
- A build request IS present in the town hall, the Builder's name claims she is working on it (but of course not), and I built the town hall in an older version of MineColonies but I did the same with a Miner's Hut and that was upgradable.

### Steps to reproduce the problem

1. Be me.
2. Play with MineColonies in Minecraft.
3. ...
4. Profit

**Comment by marchermans** [comment] 2017-12-15 14:24
Check if he is requesting two beds
That is broken right now. Try a different colony style.

**Comment by Sweddy** [comment] 2017-12-15 16:53
Gave her two beds and nothing happened. Put two beds in the Builder's Hut inventory and nothing happened.
And if I have to pick a different location I'd also have to move the town hall. What happens to all my citizens and huts if I break the town hall block?

**Comment by marchermans** [comment] 2017-12-15 17:10
Found the bug. Will be fixed.

**Comment by Sweddy** [comment] 2017-12-15 17:57
Nicely done.
So when can it be expected? And is 1.10.2 still supported?

**Comment by Raycoms** [comment] 2017-12-15 17:58
Yes, it is, and I think around this weekend.

2017-12-15 17:57 GMT+00:00 Sweddy <notifications@github.com>:

**Comment by Moobien** [comment] 2017-12-17 03:26
@raycoms i am suspecting the issues i am having with armor stands and item frames are linked to this bug.

**Comment by Raycoms** [comment] 2017-12-17 19:41
Should be fixed in the newest version, should be on curse in a few minutes

**Closed as completed by Raycoms** 2017-12-17 19:41 UTC

**Comment by JRAT24** [comment] 2018-08-25 18:44
Experiencing this exact same issue right now.  Will build other buildings and will upgrade other buildings but wont request anything or even start removing any of the blocks from the level 1 building.  Has all the tools needed too.  Using the medieval oak town hall going from level 1 to level 2.  I am in the most recent update for 1.12.1.

**Comment by Raycoms** [comment] 2018-08-25 18:45
Hi, the creator of the medieval townhall updated it, so it's different, so
the upgrade will move a lot of blocks underground, that's why it seems like
that

**Comment by JRAT24** [comment] 2018-08-28 02:44
So my builder pacing back and forth with a Windy Garden (from Pam’s Harvestcraft) in his hand for 10 in game days is okay?

**Comment by arough007** [comment] 2020-04-05 09:36
I have the same problem.
The builder announces, that he is doing the upgrade to medieavaloakalternative_townhall3 and walks to the builders hut.
He stands there until the day is over doing nothing. Every day.
He doesn't have any requests, isn't hungry, I tried to punch some sense into him, I tried `/mc colony requestsystem-reset 1` (which is the right ID), fire and rehire, cancel upgrade, pause builders hut and I even fired him all together and replaced him, because I thought he just might me an a**hole (maybe his name is worrez) 😀 
I leveled the new builder with other buildings, because I thought the problem was that he was to unexperienced but he's level 15 now and my builders hut is lvl 4.

I'm at the end of my rope here.

**Comment by Raycoms** [comment] 2020-04-05 09:59
What version are you on?

**Comment by arough007** [comment] 2020-04-05 10:08
I'm on 0.10.771-RELEASE for 1.15.2

**Comment by Raycoms** [comment] 2020-04-05 10:13
Please try the newest alpha first.

**Comment by arough007** [comment] 2020-04-05 12:40
I updated and the problem is still the same.

**Comment by Raycoms** [comment] 2020-04-05 12:45
How long are you waiting for him standing? Depending on the schematic etc this might need a bit.
There is also the problem when the schematic changes, then it might need a while for the worker to scan the environment.

**Comment by arough007** [comment] 2020-04-05 12:48
He's standing in his builders hut for an ingame day now.
I fired him, waited a day and than rehired him.
Restarted him via the gui and reset the request system.
I'll wait some more and in the meantime check if the upgrade is significantly different from the previous one.
EDIT: Oh well I just noticed I can't craft a new town hall

**Comment by Raycoms** [comment] 2020-04-05 12:52
Any log?

(you can, buildtool middle and top, rest planks)

**Comment by arough007** [comment] 2020-04-05 14:27
Apparently I was to impatient.
I did smth else IRL for an hour, came back and he finally requested stuff.
Is there some kind of info about this things taking so long in game?
If not maybe it can be added?

Anyway, thanks for the help and sorry for this selfmade problem 😅

**Comment by Raycoms** [comment] 2020-04-05 14:30
Yeah, we're always working on improving these things.
