### ISSUE TITLE
Visitor requiring 'air' to hire.

### ISSUE THREAD

**Issue by AVFD** [ldtteam/minecolonies#6477] opened 2021-02-01 12:12 UTC
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.566-ALPHA-universal
- Structurize Version: structurize-0.13.104-ALPHA-universal

## Expected behavior

Expected to tavern visitors to require stuff like: honeycomb, diamond, emerald, cake...

## Actual behavior

Tavern visitor required 'air'.
Print of the requiring: https://imgur.com/K8iIIUD

## Steps to reproduce the issue

1. Build tavern lvl 3.
2. Wait until one of the visitors require 'air' to hire. (in my case this happened after hours of game)
3. That's it.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Relap-O2** [comment] 2021-02-01 18:42
Same happened to me and my friend, we we're playing multiplayer on the lastest release BETA, and we got the same error, we can't hire that person who demands "Air".

**Comment by ravenbuilder934** [comment] 2021-02-01 18:43
Just a fyi, both of you are out of date - 566 is about 30 versions behind, and we recommend using the alphas, not the betas.

**Comment by Raycoms** [comment] 2021-02-03 00:40
Did any of you two adjust the cost of visitors in the config?

**Comment by AVFD** [comment] 2021-02-03 11:37
> Did any of you two adjust the cost of visitors in the config?

Nop, I didnt't change anything

**Comment by AVFD** [comment] 2021-02-10 00:24
![image](https://user-images.githubusercontent.com/18308993/107446365-0f4f2200-6b1d-11eb-8d90-115f137e9177.png)
Still requiring 'air'... same case, build tavern and w8 till someone require air

**Comment by Raycoms** [comment] 2021-02-10 01:59
can you send us the log for when this visitor spawned?

**Comment by AVFD** [comment] 2021-02-13 02:32
> can you send us the log for when this visitor spawned?

I will do it next time...

**Comment by ArrantSea77** [comment] 2021-03-23 19:46
I had this exact problem with the exception that all visitors, regardless of the tavern level, required air to recruit. I changed from many different versions of Minecolonies and Structurize to no avail. I found out the problem is the GUI being too large that it somehow zooms in too close and makes the recruitment item not display. I hope this helps.

**Comment by robbinsmitje** [comment] 2021-03-25 18:56
Hello i have also the same problem is there a fix for? here a screenshot
![20210325_194452](https://user-images.githubusercontent.com/80795014/112528190-22077880-8da4-11eb-867a-6eb5b5e47750.jpg)

**Comment by Talyda** [comment] 2021-03-25 21:20
> Hello i have also the same problem is there a fix for? here a screenshot

Are you on the latest alpha? You on a 4k monitor? A work around for it is to make your UI smaller in minecraft menu (options - video options - GUI scale to something smaller)

**Comment by Talyda** [comment] 2021-03-25 21:21
Pretty sure this isn't the same problem as the original one BTW - your visitor isn't requiring air - you just can't see what they do want - same as the person above you said

**Comment by Raycoms** [comment] 2021-05-12 23:09
Will close this as this is related to the UI scaling issues. Which an issue already exists for.

**Closed as completed by Raycoms** 2021-05-12 23:09 UTC
Labels: Bug
