### ISSUE TITLE
House assign citizes doesn't show current distance

### ISSUE THREAD

**Issue by EverettSummer** [ldtteam/minecolonies#7911] opened 2022-01-06 15:09 UTC
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.16.5-1.0.327-ALPHA
- Structurize Version: 0.13.252-ALPHA
- Related Mods and their Versions:

## Expected behavior

Should display a distance of their current house distance to hut as several versions ago.

## Actual behavior

They display some java class name that name is too long I cannot see the distance.

<img width="617" alt="javaw_2022-01-06-235519-361" src="https://user-images.githubusercontent.com/55684557/148404180-2ba11ad3-4b38-43d1-8ca4-3c3b221d57c7.png">

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment] 2022-01-06 15:10
Duplicate of #7905

**Comment by Raycoms** [comment] 2022-01-06 15:10
duplicate

**Closed as completed** 2022-01-06 15:10 UTC
Labels: Bug
