### ISSUE TITLE
Barbarians don't spawn.

### ISSUE THREAD

**Issue by Rosomah** [ldtteam/minecolonies#1350] opened 2017-08-10 11:53 UTC
### Minecolonies version

minecolonies-universal-1.10.2-0.8.3321

### Expected behavior

- Barbarians should spawn after the message "Get ready cowboy. Barbarians are going to raid you tonight (or something like that)."

### Actual behaviour

- Barbarians don't actually spawn after the message even though I waited the whole night, 2 nights in a row.

### Steps to reproduce the problem

1. Well
2. You
3. Know
4. How
5. Just wait for the night I guess.

**Comment by Asherslab** [comment] 2017-08-11 00:44
Yep thanks, I've been trying to work out why this is happening for the past 4 days. I have been 100% unable to reproduce it. May I ask if you're on a server?

**Comment by Rosomah** [comment] 2017-08-11 08:14
No, single player. I have the difficulty on normal, all other hostile mobs are spawning. I'll give it some more tries and report back if it starts working.

**Comment by Asherslab** [comment] 2017-08-11 10:16
okay, now that's extremely weird. what's your colony border range set as? and are the borders loaded?

**Comment by Rosomah** [comment] 2017-08-11 19:53
[minecolonies.txt](https://github.com/Minecolonies/minecolonies/files/1218820/minecolonies.txt)
There, I hope you can open the file.
I have a chunkloader which should keep the chunks around the borders loaded. And I've just tried playing it on a LAN world with my brother where the barbarians did spawn, so I'm not sure what's causing them not to spawn on the other world.

**Comment by Asherslab** [comment] 2017-08-13 02:05
Hi, can i get you to run This version: http://teamcity.smithsmodding.com/guestAuth/repository/download/Minecolonies_Branches/3389:id/minecolonies-universal-1.10.2-0.8.3389.jar 

and then go through a couple of nights without the barbs spawning. then can you send me the logs (.minecraft/logs/<latest.log>)

**Comment by Rosomah** [comment] 2017-08-16 19:28
OK, I'll post the logs as soon as I have time to test it out.

**Comment by Rosomah** [comment] 2017-08-17 00:34
Well this time, the world crashed when I got the message "Buckle up cowboy..."
Here's the file:
[latest.zip](https://github.com/Minecolonies/minecolonies/files/1229825/latest.zip)

**Comment by Asherslab** [comment] 2017-08-17 01:03
Yeah, I've got a new version for you when I get home. It should have it completely fixed. Thanks

**Comment by Asherslab** [comment] 2017-08-17 06:43
here's a new version, this should FIX it =D http://teamcity.smithsmodding.com/guestAuth/repository/download/Minecolonies_Branches/3474:id/minecolonies-universal-1.10.2-0.8.3474.jar

**Comment by Rosomah** [comment] 2017-08-17 09:23
Thanks, I'll give it a try and report back. :)

**Comment by Asherslab** [comment] 2017-08-17 09:26
thanks mate :smile:

**Comment by marchermans** [comment] 2017-08-17 16:33
@Asherslab how did you fix this?

**Comment by Asherslab** [comment] 2017-08-17 22:28
I changed the getTopBlock method I was using (the vanilla one) to the one made in BlockPosUtils that we use for RTP

**Comment by Rosomah** [comment] 2017-08-18 10:46
Yeah, I confirm, it's working now, thanks. :)

**Comment by Asherslab** [comment] 2017-08-18 12:02
That's great.

**Comment by hron84** [comment] 2017-08-25 23:05
I would not open a new issue for this, but barbarians can/do spawn in 1.11.2? There is no trace of them, even the enchanter hut is hidden.

**Comment by Raycoms** [comment] 2017-08-25 23:14
There is no enchanter hut yet =O

2017-08-26 0:05 GMT+01:00 Gabor Garami <notifications@github.com>:

**Comment by Asherslab** [comment] 2017-08-26 00:33
No enchanter hut, I need to port my spawning fix from 1.10 to 1.11 I'll prob do it today

**Comment by hron84** [comment] 2017-08-27 09:40
@Asherslab can't wait. Announcing message displays correctly, btw. 😃

**Comment by Asherslab** [comment] 2017-08-27 09:41
yep, 'twas merged today

**Comment by hron84** [comment] 2017-08-27 09:42
Btw, if we can't have enchanter hut yet, could you please hide the Tome item from JEI? It looks wonderful, but misleading.

**Comment by Asherslab** [comment] 2017-08-27 09:44
The Tome is currently used to indicate when a raid will Occur, I.E. the day of a raid the Tome will glow as if it's enchanted (Was working last i checked, hopefully still is)

**Comment by hron84** [comment] 2017-08-27 09:45
@Asherslab Ohh, wow. I never checked it at the raid. Awesome! :-)

**Comment by Asherslab** [comment] 2017-08-27 09:46
yep (Only when in inventory, otherwise it won't work)

**Comment by hron84** [comment] 2017-08-27 09:47
Can I get a Tome somehow in-game without cheating?

**Comment by Asherslab** [comment] 2017-08-27 09:53
yes, semi-rare drop from barbarians

**Comment by hron84** [comment] 2017-08-27 09:56
Who aren't spawn yet :-) I heard about some mobs dropping it rarely :-)

**Comment by Asherslab** [comment] 2017-08-27 09:57
other mobs ~not that i know of~ i didn't do. btw newest version should have them spawning (all three versions)

**Comment by hron84** [comment] 2017-08-27 10:23
Ohh, cool. I will download it right now :-)

**Comment by hron84** [comment] 2017-08-29 10:33
@Asherslab I checked out latest build. I have a flatland desert world, and message displays correctly, but barbarians still don't spawn (on 1.11). ToroQuest fugitives do, zombies, husks, skeletons, creepers and spiders do, ThermalFoundation Blitzes do, barbarians don't. Maybe sand / sandstone is not a vaild block for spawning them? 

Also, I move back to 1.10, because - I dunno why but -  I started to get constant client crash after entering to my 1-user multiplayer world. I do not blame MineColonies since the crash log does not include info from what happening, but it started to happening after upgrading to newest build and did not stop after rolling back. I'm sad, a whole week went to trash. :-(

**Comment by Asherslab** [comment] 2017-08-29 10:46
Yeah, you can't go from 1.11 to 1.10 ever. @raycoms correct?

Also, with the barb spawns, do you have more than 5 citizens, and are they enabled in your config, if yes, can you enable "development features" in your config and you'll see a message when a raid happens saying the barbarian spawn point, can you tell me if its null or not?

**Comment by Raycoms** [comment] 2017-08-29 11:32
Yes, because of some Minecrafty things it isn't possible to go from 1.11
back to 1.10, we're only forward compatible

**Comment by hron84** [comment] 2017-08-29 13:24
@Asherslab Let me answer one-by-one.

 - I have 6 citizens (3-3 in two citizen huts)
 - I getting a raid announcement message, so I think they're enabled in the config, but I will check it asap I arrive to home
 - It could be possible I cannot check it anymore, since - as I said - my world broke. I will try to restore an older backup which is may or may not let me try it out. I'll do my best but no promises.

I never planned to copy the world under 1.10. I know right I have to start a fresh world. I'm so sad... :disappointed:

**Comment by XerorBattler** [comment] 2017-09-29 14:02
I noticed one more issue with barbarians not spawning. We have 3 villages on SMP server (1.12.2 4128 version) and barbarians attacks only the last one. Notices are coming both on first and second (third is unloaded at the time), but real attack is only at third. Guy owning this village is pretty angry :D.

**Comment by Raycoms** [comment] 2017-09-29 14:07
Hi @hron84 this should be fixed in the newest version.

**Closed as completed by Raycoms** 2017-09-29 14:07 UTC
Labels: Bug
