### ISSUE TITLE
Stacking items in chests by villagers not working

### ISSUE THREAD

**Issue by thecremeegg** [ldtteam/minecolonies#2793] opened 2018-08-16 13:04 UTC
### Minecolonies version

VERSION minecolonies-1.12.2-0.9.1-RELEASE-universal

### Expected behavior

- Villagers return items to chests, will stack with existing items in chests

### Actual behaviour

- Villagers return items to chests, if existing item in there it does not stack, instead creates new stack

### Steps to reproduce the problem

1. Put X item in chest
2. Give villager X item
3. Villager will return item to chest in a separate stack
4. Profit

**Comment by Nightenom** [comment] 2018-08-16 14:54
Duplicate of #2665, we know it's a problem and it will probably get solved in 1.13 release

**Closed as completed by Nightenom** 2018-08-16 14:54 UTC
