### ISSUE TITLE
Builder lvl2 accepted lvl4 build contract

### ISSUE THREAD

**Issue by jarquafelmu** [ldtteam/minecolonies#5698] opened 2020-09-01 23:30 UTC
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.200-ALPHA
- Structurize Version: 0.13.58-ALPHA
- Related Mods and their Versions: N/A

## Expected behavior

Builder assigned to builder hut level 2 should not be able to accept and work on townhall level 3->4 upgrade job

## Actual behavior

Somehow my builder accepted the job?

![image](https://user-images.githubusercontent.com/5807272/91915676-6c929d80-ec78-11ea-95ab-a7e5af8aebcd.png)
![image](https://user-images.githubusercontent.com/5807272/91915692-77e5c900-ec78-11ea-81c4-7073639575e7.png)
![image](https://user-images.githubusercontent.com/5807272/91915704-816f3100-ec78-11ea-8da7-a6052c2432de.png)

## Steps to reproduce the issue

1. No idea

### Logs

Would the latest.log even show something related to this?

- latest.log: 
- crashlog: 

### Notes

Have to admire that gumption and ambition of the builder.

I do have two other builders at lvl 4 but this guy is the one who took the contract.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment] 2020-09-04 14:34
Is there a way to reproduce this?

**Comment by MatthiasMann** [comment] 2020-09-04 14:58
I had the same thing on 0.13.210 with the following builders (hut level):
1. level 3
2. level 2

Builder 1 was busy digging a big hole in a mountain to place a guard tower (fortress style, had to remove ~10 layers of dirt/stone).
I selected upgrade on a level 2 wall decoration (also fortress style) and the 2nd build started to upgrade the decoration.
After the upgrade to level 3 was finished I selected upgrade again and the 2nd builder did the upgrade of the wall to level 4.

**Comment by Raycoms** [comment] 2020-09-04 15:06
decorations are fine, we don't have limits there. Since decorations may have arbitrary leveling.

**Comment by jarquafelmu** [comment] 2020-09-04 16:05
It was the same for me, both of my (fortress) lvl 4 builders were busy with their own contracts and then the lvl 2 builder took the lvl 4 contract, im not sure what would reproduce it exactly

**Comment by Raycoms** [comment] 2020-09-04 16:12
I tried that with a busy builder and it didn't work

**Comment by jarquafelmu** [comment] 2020-09-04 16:19
I'm not surprised, in my experience bugs act like toddlers. They act up until the person in charge gets there (you) and then they act completely innocent.

**Comment by Raycoms** [comment] 2020-09-04 16:21
I do still need a way to reproduce this to fix it... meh

**Comment by Raycoms** [comment] 2020-09-19 09:02
Can't reproduce. I'll close this until there is a way to reproduce this.

**Closed as completed by Raycoms** 2020-09-19 09:02 UTC
Labels: Bug
