### ISSUE TITLE
Manage Worker button broken

### ISSUE THREAD

**Issue by G1R-Productions** [ldtteam/minecolonies#2971] opened 2018-10-14 08:59 UTC
Version:  10.1 release

### Expected behavior
Click manage workers button and new UI page should open.

### Actual behaviour
Click manage workers button and nothing happens

### Steps to reproduce the problem
Might be a one time weird glitch:
Spammed hire/fire button and possibly the manage workers button.
Now the manage workers button doesn't work on any colonist buildings.
Restarting server/game does nothing to fix it.

**Comment by wetbrownsauce** [comment] 2018-10-14 09:47
Have you tried running the reset command? /mc rs reset colony: 1
Obviously, replace the 1 with your colony's ID

**Comment by G1R-Productions** [comment] 2018-10-14 09:53
I did that that and it didn't work. I did find a solution though. If I went back to the tow hall and switched it back to automatic hiring and then back to manual I was able to open the manage workers page. Though I wouldn't call this an ideal solution since it doesn't explain the initial bug.

I'll let one of the devs decide if this is resolved or not.

**Comment by Nightenom** [comment] 2018-10-14 17:41
There was a functionality of closing the manage worker window after hiring and firing, I disabled that because it is annoying when managing the library. @Raycoms was there a reason for that so I should add it back?

**Comment by Raycoms** [comment] 2018-10-14 17:43
No I think players can close it manually, but the problem here is that it
won't open as far as I understood it. G1R do you have a log of that?

Am So., 14. Okt. 2018 um 14:41 Uhr schrieb Nightenom <
notifications@github.com>:

**Comment by Nightenom** [comment] 2018-10-14 17:47
> Spammed hire/fire button and possibly the manage workers button.

Not sure, but I think it may crash cause of spamming hire/fire really quickly

**Comment by G1R-Productions** [comment] 2018-10-14 17:56
I do not have a log of it sadly.

**Comment by Raycoms** [comment] 2018-10-14 18:02
Can you try to reproduce it again to get one?

Am So., 14. Okt. 2018 um 14:56 Uhr schrieb G1R-Productions <
notifications@github.com>:

**Comment by Raycoms** [comment] 2018-10-20 02:43
Closed until reproducing is possible or log is given. I tried to reproduce it but it was not possible.

**Closed as completed by Raycoms** 2018-10-20 02:43 UTC
