### ISSUE TITLE
0.6.2114 doesn't talk to players with real messages in server mode

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#421] opened 2017-01-03 14:17 UTC
### Minecolonies version

1.11-0.6.2114

### Expected behavior

When in SMP on a server, I expect the NPC to tell me the name of the tool needed as well as other messages.

### Actual behaviour

When in SMP on a server, the NPC

### Steps to reproduce the problem

1. install mod on server
2. connect to server with client that has the same mod version
3. place townhall and assign a worker
4. notice how it doesn't tell you anything useful

Please watch the **unlisted** video at [https://youtu.be/DSXltWHT8zw](https://youtu.be/DSXltWHT8zw), you can jump to 1:48 to see the first of many messages that don't tell the player anthing at all.

**Note**: In SSP we don't have these issues as the player is informed correctly.

**Comment by Raycoms** [comment] 2017-01-03 14:24
Thank you for the good error report.
We are aware of that problem.
We have to give our translation framework a little rework.



2017-01-03 12:17 GMT-02:00 kreezxil <notifications@github.com>:

**Comment by kreezxil** [comment] 2017-01-03 16:17
seems that issue #412 is related.

**Comment by Raycoms** [comment] 2017-01-03 16:51
@Kostronor could you please take care of this?
I have no idea how to handle that.
Will be way faster if you do this

Am Dienstag, 3. Januar 2017 schrieb kreezxil :

**Comment by nekatu** [comment] 2017-01-04 00:08
To add to the ongoing strings fun, thought I'd share this-

WAILA seems to pick up the correct string while InGame XML shows the same string that the console shows in messages.

![2017-01-03_23 44 46](https://cloud.githubusercontent.com/assets/1908371/21627728/bfe4bfac-d211-11e6-8bd7-976e94dc44a2.png)
![2017-01-04_00 05 39](https://cloud.githubusercontent.com/assets/1908371/21627729/bfe8ec26-d211-11e6-810f-7e0e6f6c7649.png)

**Comment by kreezxil** [comment] 2017-01-05 20:09
It's almost like the server doesn't know what language to send the chat in, and so returns the key of the message as the body of the message.

**Comment by Raycoms** [comment] 2017-01-05 20:15
It's exactly that =D

2017-01-05 18:09 GMT-02:00 kreezxil <notifications@github.com>:

**Comment by nekatu** [comment] 2017-01-05 22:36
So something I should be able to workaround locally on the server, right?

**Comment by Raycoms** [comment] 2017-01-05 23:04
Probably not, can't say now how to fix it.

2017-01-05 20:36 GMT-02:00 nekatu <notifications@github.com>:

**Comment by kreezxil** [comment] 2017-01-06 00:38
Shouldn't the client actually handle this as that is where the definition
of what language to use is. it's similar to when the server tries to render
an object but can't and throws an error, but in this case doesn't crash.

**Comment by Raycoms** [comment] 2017-01-06 00:46
it should but we will have to change some code for it to work properly

2017-01-05 22:38 GMT-02:00 kreezxil <notifications@github.com>:

> Shouldn't the client actually handle this as that is where the definition
> of what language to use is. it's similar to when the server tries to render
> an object but can't and throws an error, but in this case doesn't crash.
>

**Comment by kreezxil** [comment] 2017-01-07 22:31
any ETA on this fix? I need to update my pack, there are about 15 outdated mods in it already for 1.11.2 and about 8 more that just updated to 1.11.2 begging to go in. If the fix is not expected soon, what tools does the builder ever need, too bad that doesn't go in the materials section as it would make figuring out what he needs really easy, not to mention, when you are gone for a bit it eliminates you having to do recall to get him to complain about something, in ssp yay, but smp still not yay.

**Comment by Raycoms** [comment] 2017-01-07 22:36
Tools of builder is shovel, axe and pickaxe depending on his terrain. he
needs them level 0: wood, level 1: stone, level 2: up to iron level 3: up
to diamond level 4: enchanted. Should be like this.
All workers follow +- the same pattern. If he isn't satisfied with an iron
he might've found some harder material and requires a higher pick.
Still can't tell any eta because I don't know yet how to fix it. @Kostronor
any idea?

2017-01-07 20:31 GMT-02:00 kreezxil <notifications@github.com>:

**Comment by marvin-bitterlich** [comment] 2017-01-07 22:37
We have to rewrite all our sting pipelines to chain TextComponents, that will be a lot of work and suck lots.

**Comment by Raycoms** [comment] 2017-01-07 22:39
Probably even on the client I bet.

2017-01-07 20:37 GMT-02:00 Marvin Hofmann <notifications@github.com>:

**Comment by Raycoms** [comment] 2017-01-07 22:39
Only 250+ language strings to set a TranslateAbleTextComponent xD

2017-01-07 20:39 GMT-02:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by kreezxil** [comment] 2017-01-08 19:04
I'm really good at typing, autohotkeymacros and using linux to do bulk work. Are all of the strings scattered throughout the entire codebase or located in one place? and what pattern needs to be changed to which. Also notepad++ provides awesome abilities for mass pattern changes and macros. I have that too.

**Comment by Raycoms** [comment] 2017-01-08 21:28
In around 5 minute a new version will appear here:
https://www.dropbox.com/sh/9cnqcjl0nan57cy/AAC99g-CJiTZjQiXMuLKkDgja/branch/version/1.11?dl=0
Can you test if in the new version and in the version previous to that the translations work in single and multiplayer?

**Comment by Raycoms** [comment] 2017-01-08 21:29
I adapted some things. For me in single player stuff in english and german(germany) gets translated correctly. Would have to check for the other language as well. (Portuguese and spanish should be quite complete as well)

**Comment by kreezxil** [comment] 2017-01-09 00:43
2271 

- ssp
  - looks good except for when he starts building as he or the mod says "'''Started building default/Builder1'''"
  - actually asks with the correct string
- smp
  - so logged into my server where I chunk loader running
    - console says '''Starting AI job com.minecolonies.coremod.job.Builder'''
        - in the game
        - builder was standing at his chest, nothing was being said actively in chat, I would think that at least once a minute he would say something, again this can be prevented by adding something to npc's gui, like current material/tool. In my case he was waiting on cobblestone. Then he started to build.
        - Now he just informed me that he needs something with '''Send player message: com.minecolonies.coremod.job.Builder Christopher Y. Robinson: entity.miner.messageNeedBlockAndItem''', it appears in the console the same way

2276 
- ssp
    - looking real good no strange messages when you hit "build building"
    - it actually says "build request created" & "started building"
    - ok, he standing in front of his chest says '''Builder Rory X. Brown: I need a  of a maximum grade of .'''
    - therefore the item name and the item level are missing.
- smp
    - so my guy is standing at the chest and he says "'''Send player message: com.minecolonies.coremod.job.Builder Christopher Y. Robinson: entity.worker.toolRequest'''"

Is it possible that you are experiencing a bug that the Forge team needs to fix?

**Comment by Raycoms** [comment] 2017-01-09 13:22
No but I now know what the problem is. Quite a lot of copy and paste and
the rest is exchange some mechanics.

2017-01-08 22:43 GMT-02:00 kreezxil <notifications@github.com>:

**Comment by Raycoms** [comment] 2017-01-10 12:18
I believe I've fixed it, can you give it a short:
https://www.dropbox.com/sh/9cnqcjl0nan57cy/AAC99g-CJiTZjQiXMuLKkDgja/branch/version/1.11?dl=0&preview=minecolonies-universal-1.11-0.6.2289.jar

2017-01-09 11:22 GMT-02:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by kreezxil** [comment] 2017-01-10 14:51
btw, on these dropbox links, if you guys would take the time and edit the link by hand and change dl=0 to dl=1 they will become downloadable from here, or in my case quite easy to pull into a linux machine using wget.

**Comment by kreezxil** [comment] 2017-01-10 16:54
build 2289
- ssp
  - if by fixed you mean made it stop talking entirely, then you fixed it, :)
  - client console activity log: https://gist.github.com/kreezxil/8981ed56bc15d1b69c7ec7dd7b618f3f
  - i was expecting the builder to at least tell me the strange messages instead of standing there
- smp
  - started a new colony, the messages
   - Build Request Created
   - Started building default/Builder1
   - Colony has reached max size
    - '''builder returned to chest, didn't say anything''' gonna give him an axe
    - He wanted an axe, so this the same behavior as ssp now, they no longer talk not even with the gibberish

**Comment by nekatu** [comment] 2017-01-10 19:10
I can confirm all that @kreezxil says.

Also, to add to the list, when I was testing with the 227x builds last night I found that attribute values on the NPC hiring windows are missing (basically showed all the citizens, but no numbers next to the attributes). 

Will be testing this with 2290 this evening to see if it still has the same issue.

**Comment by nekatu** [comment] 2017-01-10 19:20
OK- with 2290 it looks like we're at least back to the pre-2270 builds with incorrect strings and messages on SMP. NPC attribute values are working again too. :-)

**Comment by nekatu** [comment] 2017-01-10 19:30
Seems a few workers are showing the right strings- Rangers ask for a single bow, so some strings are now working.

**Comment by Raycoms** [comment] 2017-01-12 20:43
Should be fixed in the version I'll upload in a minute.

**Closed as completed by Raycoms** 2017-01-12 20:43 UTC
