### ISSUE TITLE
Problems with builder

### ISSUE THREAD

**Issue by cutpricewizard** [ldtteam/minecolonies#1836] opened 2017-12-12 12:15 UTC
minecolonies-universal-1.12.2-0.8.5950
Also 
minecolonies-universal-1.11.2-0.8.5960
and
minecolonies-universal-1.10.2-0.9.5961
--
I don't know whether this is a bug or if I'm doing something wrong.
The builder doesn't seem to recognise what a bed is. When the builder requires a bed for a building s/he collects a bed or I "fulfil" in the request window. S/he walks to the building, pauses as if to place it and then wanders back to the builder's hut requesting a bed again. I've attempted to cancel the request only to have the process repeat itself over again.

This seems to have happened since the creation of the present request system.
I have created fresh reinstallations of Minecraft. As you can see from above, have run different versions of the game with the appropriate mod version. I have even set the game up with no other mods running, all to no avail.
I really don't know what else to do. Any suggestions?

**Comment by Raycoms** [comment] 2017-12-12 12:29
Might be an issue with red/white bed?

2017-12-12 12:15 GMT+00:00 cutpricewizard <notifications@github.com>:

**Comment by cutpricewizard** [comment] 2017-12-12 13:23
Hi Raycoms
I'm impressed with how swiftly you responded. A similar thought had occurred to me. That might explain the situation with 1.12.2 but surely not with 1.11.2 or 1.10.2? After posting, I thought I'd remove Just enough Items from the equation. That means I'm using no other mods at all apart from minecolonies. So there is also no chance of conflict either. I did not think it likely, but I am of a cautious nature.
There was one reason I had not reported this earlier - I noted it has not been mentioned so far and I thought it must be a problem peculiar to my installation somehow. However desperation drove me to mention it. Having just started using MultiMC I can just leave the game where it is in the hope that a solution is available and move onto something else for a while.
Many thanks for your swift attention. It is much appreciated.

**Comment by Raycoms** [comment] 2017-12-12 13:27
I will try to reproduce this a bit later today and will see if I can come
up with a solution.

2017-12-12 13:23 GMT+00:00 cutpricewizard <notifications@github.com>:

**Comment by Optimistos** [comment] 2017-12-12 13:54
new problem. When builder want upgrade a citizens house at lvl 3 it ALWAYS Looking for 2 BED.. even if he have 2 and in chest 2.

MAybe like the sir Raycoms about colors because in my town hall is red bed but in citizen house he want white and like i say always looking for 2 bed

**Comment by Optimistos** [comment] 2017-12-12 14:02
aah and my farmer is Hoeing and nothing happens xD just walking around and says Hoeing))

**Comment by TheOrionsun** [comment] 2017-12-13 01:07
Similar issue in v 1.12.2-0.8.5930. I was trying to get workers to work and tried to do a repair on the Town Hall. Version 1.12.2-0.8.5950 installed and all workers now work as intended...farmer could see crops and fisherman could find fishing rod ect. But now the builder is stuck on trying to find an item frame for the Town Hall even though I have canceled the repair. When I go into the builder UI it is very slow and showed other items needed for Town Hall but next time it did not. Builder just stands in hut all day and returns to house at night. When I see the chat bubble it always says looking for Item Frame. Not sure if this helps...
Thanks for Great! mod and all the time you give to improve it,

**Comment by Raycoms** [comment] 2017-12-13 01:08
We fixed some of those issues already and will merge them in the next days.

2017-12-13 1:07 GMT+00:00 danielconrad2011 <notifications@github.com>:

**Comment by bob0bob** [comment] 2017-12-13 03:14
I've also notice that workers are requesting things that are in the hut's chest.   The system is not seeing items correctly.  If you remove it and put it back, the mod sees it.   It appears to be an issue when it goes to request something, it not seeing what they have.   I would guess they request it before they get to the hut.  But return to the hut block,  but at that point the request system has marked it to be a player delivery or warehouse.   It doesn't wait to see if its in the hut's inventory before a request goes out.  It appears that step is skipped.

**Comment by marchermans** [comment] 2017-12-13 05:34
I found the beds Problem. @bob0bob Right now we are having some issues with what the RS sees as a valid item and whatnot (mostly to do with should we match Meta and or NBT or not at all).
Which is a anoying things to track down.

The RS will always look into the Building first regardless of were the citizen is. But the Problem with the bed is for somereason our inventory scanning Code does not seem to match against it eventhough it has the same Meta. which is what i am Debugging today.

**Comment by bob0bob** [comment] 2017-12-13 06:38
What I've seen is things like oak fence,  oak plants and such.   Had a miner request oak fences.  I brought them and in the huts inventory there was oat fences.  So I removed them and then put it back in.  Then it noticed them and fulfill the request.  Not just beds.  

For my issue, it seems like the RS looking into the hut chest had an issue seeing the item but once it is request and you add them.  it locates them.   Just a thought, it appears for my issue is the initial scan of the chest at the start of the RS doesn't see it sometime.
Not all the time, it works most times.

**Comment by cutpricewizard** [comment] 2017-12-13 08:07
Hi OrionDevelopment
Greetings to you and Raycoms. I would like to extend my thanks for your swift action and courtesy. Both of which are greatly appreciated. Congratulations at tracking down the primary cause of the problem.
I'm surprised that something like this has not been reported before. Although, I suppose, a bed is not requested until about level 3 or 4 for many of the house styles, except for the birch buildings where the town hall needs beds straight from "out the gate", as it were.

**Comment by lJasonl** [comment] 2017-12-15 09:31
I'm having the same issue with the beds. I look forward to the fix and thank the team for their hard work.
-JaY

**Comment by Raycoms** [comment] 2017-12-17 19:42
Should be fixed in the newest version, should be on curse in a few minutes

**Closed as completed by Raycoms** 2017-12-17 19:42 UTC

**Comment by cutpricewizard** [comment] 2017-12-17 19:53
Many thanks to you, one and all.
