### ISSUE TITLE
[BUG] <Farmer crash>

### ISSUE THREAD

**Issue by crazydud24** [ldtteam/minecolonies#8230] opened 2022-04-06 22:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.577

### Structurize Version

1.0.369

### Reproduction Steps

I completed a lv1 farmers hut at the edge of my village. I assigned an jobless colonist and this crash happened. it now crashes every time I load the world

### Logs

https://pastebin.com/01LrtJDC    https://pastebin.com/AAzcxdk9

### Anything else?

When loading the world I have about 1 second before it crashes. if right clicking on the block this is put into chat
![2022-04-06_18 39 48](https://user-images.githubusercontent.com/17237729/162084269-15c12541-e47c-48a1-bbc2-c968a37fa7d4.png)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment] 2022-04-06 22:42
Duplicate of #8229

**Closed as completed** 2022-04-12 19:55 UTC
Labels: Bug
