### ISSUE TITLE
Fortress Schematic is wrong

### ISSUE THREAD

**Issue by Laz0rus** [ldtteam/minecolonies#6267] opened 2020-12-19 02:33 UTC
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.525 Alpha
- Structurize Version: 0.13.100 release
- Related Mods and their Versions: im using the Valhelsia 3 modpack, and im not sure what mods are related

## Expected behavior
Correct schematic

## Actual behavior
the fortress style university schematic is incredibly wrong

## Steps to reproduce the issue

1. try to build the fortress university
2. set to level 5
3. and the schematic is not what is built

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment] 2020-12-19 02:35
Can you please send a screenshot of the preview versus what is built?

**Comment by Laz0rus** [comment] 2020-12-19 02:38
It’s not fully built, but the left is the preview, the right is what the builder has done so far. Nothing has been build yet, but its being excavated 3+ blocks below the surface, so I’m pretty sure the preview is not what is being built.

**Comment by ravenbuilder934** [comment] 2020-12-19 02:39
I don't see the pictures

**Comment by Laz0rus** [comment] 2020-12-19 02:40
[cid:image003.png@01D6D56D.4F613310]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ravenbuilder934** [comment] 2020-12-19 03:01
That didn't work either. Maybe you need to do it in github, not through the email reply thread?

**Comment by Laz0rus** [comment] 2020-12-19 03:02
![Screenshot (76)](https://user-images.githubusercontent.com/76235597/102679293-91e1e380-4163-11eb-994f-b5b4b7be3a98.png)

**Comment by ravenbuilder934** [comment] 2020-12-19 03:04
Weird, this should've already been fixed in 525. I'll check if I can reproduce it tomorrow.

**Comment by Raycoms** [comment] 2020-12-19 08:59
#5006 for schematic issues please

**Closed as completed by Raycoms** 2020-12-19 08:59 UTC
Labels: Bug

**Comment by ravenbuilder934** [comment] 2020-12-19 17:33
And I can't reproduce it, both the fortress uni and the alt fortress uni work fine

**Comment by Laz0rus** [comment] 2020-12-20 18:26
Weird. I’ll try it in a new world. Thanks for the assistance though

Sent from my iPhone

On Dec 19, 2020, at 9:33 AM, ravenbuilder934 <notifications@github.com> wrote:

﻿

And I can't reproduce it, both the fortress uni and the alt fortress uni work fine
