### ISSUE TITLE
Knights not patrolling

### ISSUE THREAD

**Issue by alexrr10** [ldtteam/minecolonies#2910] opened 2018-09-24 15:43 UTC
Knights in barracks don't patrol, they stand in the hiring place

**Comment by Nightenom** [comment] 2018-09-24 16:31
Hi, try setting their patrol point (the second page of the hut block)

**Comment by alexrr10** [comment] 2018-09-24 17:16
It doesn't work

**Comment by Raycoms** [comment] 2018-09-24 17:19
Do they have anything on the request window and are they on patrol?

Am Mo., 24. Sep. 2018 um 14:16 Uhr schrieb alexrr10 <
notifications@github.com>:

**Comment by alexrr10** [comment] 2018-09-24 17:23
They don't have requests abd they are set on patrol

**Comment by Raycoms** [comment] 2018-09-24 17:24
And it is automatic patrol as well?

Am Mo., 24. Sep. 2018 um 14:23 Uhr schrieb alexrr10 <
notifications@github.com>:

**Comment by Raycoms** [comment] 2018-09-24 17:24
What minecolonies version it is?

**Comment by alexrr10** [comment] 2018-09-24 17:25
The latest

**Comment by Raycoms** [comment] 2018-09-24 17:26
Can you send us the world?

**Comment by alexrr10** [comment] 2018-09-24 17:27
It is in a modpack

**Comment by Raycoms** [comment] 2018-09-24 17:28
As long as the world is not tooo big, it shouldn't be a problem.

Am Mo., 24. Sep. 2018 um 14:27 Uhr schrieb alexrr10 <
notifications@github.com>:

**Comment by Raycoms** [comment] 2018-10-07 21:09
This is a duplicate of a similar issue. I will close this in favor of the other issue.

**Closed as completed by Raycoms** 2018-10-07 21:09 UTC
