### ISSUE TITLE
The same citizen has 2 jobs

### ISSUE THREAD

**Issue by bloodyraoul** [ldtteam/minecolonies#5076] opened 2020-05-25 12:31 UTC
Version: minecolonies-1.15.2-0.11.948-universal
Forge 31.2.4

One of my citizen has 2 jobs. he's a builder and a guard
But in fact, he's a guard, he don't advance any builder's task
All my recruitements are in automatic mod
If I switch to manuel, I cannot remove it from builder
If I switch to manual, I can remove it from guard, so he take another job but he's still present as a builder, so nobody else can take the job
The only way I have found to fix it is to quickly fire it from the 2 jobs, first from the guard, then quickly from the builder (it appears as a builder when it is his only job).
Then I have reassigned it as a builder and now it stay as a builder
I dont know if it is clear ?

**Comment by Raycoms** [comment] 2020-05-25 12:33
is there a way to reproduce this?

**Comment by bloodyraoul** [comment] 2020-05-25 12:49
unfortunatly, i dont know...but I think DiabolosMan have also post a bug about a guy having two jobs...so it is maybe linked (we are on the same server)

**Comment by Raycoms** [comment] 2020-05-25 12:51
Where?

**Comment by DiabolosMan** [comment] 2020-05-25 12:52
I confirm it happened for me for a composter/guard

https://github.com/ldtteam/minecolonies/issues/4663#issuecomment-622840711

**Comment by Raycoms** [comment] 2020-05-25 12:52
Were you able to find some way to reproduce this?

**Comment by DiabolosMan** [comment] 2020-05-25 12:53
And no, I was not able to reproduce it. Like for @bloodyraoul , I had to fire the same citizen in both huts

**Comment by wolfsilver00** [comment] 2020-05-25 18:47
Happened to me once, had both guard tower (normal one, not barracks) open and smelter, recruited, job picking was on auto, dude got both, but in my case he also lived in a house, not on the tower

**Comment by Sharalith321** [comment] 2020-05-28 20:49
the way to reproduce this is:
1.  automatet job assign activ
2. a few open jobs
3. u fire and hire a Miner for example

if ur to slow/fast the Citizen  is assigned to a new job but still count in the old one

Have the Bug atm with my Miner and Composter being the same Guy

**Closed as completed** 2020-05-29 16:03 UTC
Labels: Bug
