### ISSUE TITLE
builder and player item duplication glitch / bug

### ISSUE THREAD

**Issue by rexrapter1234** [ldtteam/minecolonies#799] opened 2017-04-12 09:19 UTC
### Minecolonies version

version 1.10.2 or curse X.X.XX

There seem to be a item duplication glitch / bug with the new update that affects the builder and player.

### Expected behavior

When a player adds new item in to the builders hut block, use the builder's requests list, the items are remove from the player.

When a builder go to but items in the builder hut's block, he don't keep copy of the item on he.

- XXX

### Actual behaviour

When a player adds new item in to the builders hut block, use the builder's requests list, the items are not remove from the player.

When a builder go to but items in the builder hut's block, he ends up keep putting items in to the builder hut's block and also keep a copy of the item on he.

- YYY

### Steps to reproduce the problem

This bug one from the new update.

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by xavierh** [comment] 2017-04-12 10:02
Trying to reproduce it without success. Was it in multiplayer  ?

**Comment by SulpherStaer** [comment] 2017-04-13 01:38
Do you have other mods installed also? Because I cannot duplicate this issue either.

**Comment by marchermans** [comment] 2017-04-13 07:26
Yep known bug, caused by an NPE that is caused in between the adding to the builder and removing from the player with the new Capabilities. This will be fixed in the new update.

See #800

**Closed as completed** 2017-04-13 22:28 UTC
