### ISSUE TITLE
Streets [$5]

### ISSUE THREAD

**Issue by reggaemuffin** [ldtteam/minecolonies#20] opened 2016-08-13 18:24 UTC
Having (perhaps auto-build) roads could be a nice looking way to create immersion.

For Minecraft 1.9 there is http://minecraft.gamepedia.com/Grass_path which we could use for roads.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=36918967)](https://www.bountysource.com/issues/36918967-streets?utm_source=36918967&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Raycoms** [comment] 2016-08-14 00:01
Auto-build roads cause a lot of trouble IMO.
For me there are two possible ways:
- Create a planning tool (Which will be used for roads, walls etc)
- Or use the build tool and give it a "cityplaning" button where we may plan roads, walls etc.

This tool may be used to design possible roads. Similar to the scan tool the player will select certain points which may become a road. These points will be rendered when the build tool is open (For building placement to not place buildings over future roads). If the road crosses a river it will become a bridge and if it crosses a mountain it will become stairs.

**Comment by pmardle** [comment] 2016-08-20 20:31
Personally I would rather just have roads as a "Decoration" item that players can place/create/scan and use as they see fit..  getting it to "auto road" and look good is nigh on impossible

**Comment by xavierh** [comment] 2017-04-17 09:32
What about being able to request more than one build at a time using the build tool?

The idea would be to:
- Open the build tool
- chose a build (in the case a road)
- place it
- add to a tempory list of builds
- repeat step 2 to 4
- confirm all the builds which would create All the work orders related to each build

The preview would render all the temporary build until it is cancel or confirmed.

This would allow roads and walls to be build and place properly next to each other.

**Comment by Isfirs** [comment] 2017-04-17 11:10
I agree.

Also, include the additive `+1` build frame in the preview for easier spacing. (I accidentally build the 2 frames into each other). Can we have an option to prevent oberlapping buildings and add 1 to radius of each building? (Based on `.schematic` data). This could be a client-only option, based on the `View`
 data collected anyway.

Note:
If this `perma preview` is done on the old schematica, I doubt this will work well. I have massive drops when rendering a small hut.

**Comment by xavierh** [comment] 2017-04-17 11:21
An other option that I can think of:
- When the build tools is active, we could render nearby work orders.
- add a button to "confirm and continue" as opposed to "confirm and close"

**Comment by Raycoms** [comment] 2017-04-17 11:45
Problem is, Idk how it is on your pcs. But my laptop goes to hell when
rendering townhall 5. I don't want to know how this turns out when
rendering 10 buildings at a time.
The construction tape should tell you about the dimensions of the buildings
currently building.

2017-04-17 8:21 GMT-03:00 xavierh <notifications@github.com>:

**Comment by Raycoms** [comment] 2017-04-17 11:46
But the option with walls and streets seems quite nice! Also works well for
bridges

2017-04-17 8:45 GMT-03:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by xavierh** [comment] 2017-04-17 13:33
We could render the N closest buildings/decorations from the build tools
reference point. With the ability one the build tools to define N. N being
0 by default?

**Comment by xavierh** [comment] 2017-04-17 13:35
Actually with the player position as a reference point so that the player
could walk around and see the closest work order

On 17 Apr 2017 14:33, "Xavier h" <xavier.hervy@gmail.com> wrote:

We could render the N closest buildings/decorations from the build tools
reference point. With the ability one the build tools to define N. N being
0 by default?

**Comment by Raycoms** [comment] 2017-04-17 13:36
That seems better.
Additional button in the build tool "Render the closest" 1,2,3,4,ALL

2017-04-17 10:33 GMT-03:00 xavierh <notifications@github.com>:

> We could render the N closest buildings/decorations from the build tools
> reference point. With the ability one the build tools to define N. N being
> 0 by default?
>

**Comment by xavierh** [comment] 2017-04-17 13:36
I meant  With the ability in the build tools to define N

**Comment by Raycoms** [comment] 2017-04-17 13:37
Yes that's what I was talking about.

2017-04-17 10:36 GMT-03:00 xavierh <notifications@github.com>:

> I meant With the ability in the build tools to define N
>

**Comment by pmardle** [comment] 2017-04-17 21:18
Better still a button in the build tool GUI to toggle the view of all the
as yet unbuilt structures?

**Comment by Wissi** [comment] 2019-02-13 05:06
OK.. as clean-up is needed. Whats up with all this chatter?
Issue/suggestion is "streets". Which got voted as a deco for cleints to implement and place.
Now converssation ended in 

> Better still a button in the build tool GUI to toggle the view of all the as yet unbuilt structures?

Soo.. I'll close this and if there is a specific suggestion of anything else, make it?

**Closed by Wissi** 2019-02-13 05:06 UTC
Labels: bounty, discussion, enhancement, help wanted
