### ISSUE TITLE
Farmer

### ISSUE THREAD

**Issue by A-Dunois** [ldtteam/minecolonies#5826] opened 2020-09-25 02:13 UTC
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.271-ALPHA
- Structurize Version: structurize-0.13.64-ALPHA
- Related Mods and their Versions: Craft To Exil modpack version 2.4.3

## Actual behavior

I have 2 farmer level 3.
I update the modpack to last version (2.4.3) and manually update minecolonies to 0.13.271-ALPHA
(both client side and server side)
After that, i join my server. Check if anything work fine  ... I'll pass all detail..
I see in my clipboard: need hoe for 2 farmer. 
I craft some cobblestone hoe but my farmer don't want.
I try with wooden and iron hoe, no success.

I reload one farmer: no success
Fire and re-hire one: no success.

I try with tungsten hoe (end: reborn) and they happily accept that.

### Logs

- latest.log: https://gist.github.com/A-Dunois/9fa1b9ea609638691fdf24e42af40d82

**Comment by Raycoms** [comment] 2020-09-25 13:02
Are you makign vanilla hoes, or modded stone/wood hoes?

**Comment by A-Dunois** [comment] 2020-09-25 13:21
Vanilla hoes

edit:
no issue with 0.13.215-ALPHA before server update

**Comment by Raycoms** [comment] 2020-09-26 08:56
Which plants?

**Comment by A-Dunois** [comment] 2020-09-26 12:58
Potatoes, carrot and wheat

**Comment by Raycoms** [comment] 2020-09-26 13:00
Very strange, I can't reproduce this.

**Comment by A-Dunois** [comment] 2020-09-26 13:05
yeah, very strange.
They don't use the durability of this hoe.

edit: i add mekanism 9, applied energistics 2, withar staff, extra golem and enigmatic legacy to the modpack.
Maybe, one of them cause this bug ?

**Comment by Raycoms** [comment] 2020-09-26 13:15
AE2 and mekanism shouldn't cause this, I already used those alongside minecolonies without a problem. It must be some other mod causing it.

Since It can't be reproduced without any additional mods I'll close it for now. If you find out which mods causes it, you could either report it to them or make a request here: https://github.com/ldtteam/minecolonies-features/issues for mod compatibility.

**Closed as completed by Raycoms** 2020-09-26 13:15 UTC
Labels: Bug, Bug: Can't Reproduce
