### ISSUE TITLE
[BUG] Server throws "UUID of added entity already exists" message each ~25 seconds for Visitors

### ISSUE THREAD

**Issue by Knaxia** [ldtteam/minecolonies#9912] opened 2024-04-13 13:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.550-BETA

### Structurize Version

structurize-1.20.1-1.0.718-BETA

### Related Mods and their Versions

1.20.1-forge-47.2.23

blockui-1.20.1-1.0.151-BETA.jar
domum_ornamentum-1.20.1-1.0.184-BETA-universal.jar
jei-1.20.1-forge-15.2.0.27.jar
journeymap-1.20.1-5.9.20-forge.jar
multipiston-1.20-1.2.32-ALPHA.jar

### Current Behavior

When in the colony, with my tavern with visitors, each ~25 seconds, my server will pop, once or twice, the message :

UUID of added entity already exists: Enity: entity.minecolonies.visitor Type: [VisitorCitizen] at pos: BlockPos{x=xxxx, y=xxxx, z=xxxx} civilian id: none colony: none

Sometimes the name of the actual Visitor will show up, but in general, it won't.

### Expected Behavior

No messages.

### Reproduction Steps

Have a colony with a working tavern and visitors

### Logs

[latest.log](https://github.com/ldtteam/minecolonies/files/14967504/latest.log)

### Anything else?

The issue seem to have only appeared after I updated from 1.1.536 to 1.1.550. The server has been restarted a few times already, all the visitors that existed before the update are long gone. Also, ignore the fact I move too quickly, I use Journeymap to teleport around a lot.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment] 2024-04-13 13:44
Duplicate of #9909

**Closed as not planned by uecasm** 2024-04-13 13:44 UTC
Labels: Bug
