### ISSUE TITLE
Warehouse improvements

### ISSUE THREAD

**Issue by Paril** [ldtteam/minecolonies#2953] opened 2018-10-09 19:04 UTC
The Warehouse is great, but there's a few things that I think should be changed/added to make them even better.

* The limitation of having one warehouse per town should be removed. I'm not sure if this was specifically for balance purposes or because of any kind of code-wise limitation, but having more than one warehouse would be lovely. If you have woodcutters set to collect trees and replant them, you can easily get over 10k wood in a day, filling up the warehouse with a lot of wood overnight.
* With the ability to have multiple warehouses, having some additional configuration for warehouses would help keep things tidy; Warehouses should have a filter of some sort, letting you decide what items are kept in what warehouses.
* Warehouses should also have the ability to decide whether they are Pick-Up, Drop-Off, or Both (default). A Both warehouse is like they are now; Deliveryman will drop extra items off and pick up items they need from it to deliver. Pick-Up and Drop-Off warehouses are essentially "manual" warehouses, managed by players; Deliveryman can pick-up items from it that the players insert but not drop off items, or drop off items to them that they then cannot pick up again (again for the player to micro-manage the inventories).
* The removal of 1 Warehouse limitation could also bring change to the Deliveryman mechanics. The limit of 5 per Warehouse should be dropped, allowing as many Deliveryman as you like (although obviously if you're adding too many you're gonna slow down efficiency and all that). Deliveryman should also gain the ability to scan for items to pick up from the world in the town, and in their options have the ability to specify whether they fulfill requests by villagers (Yes/No), whether they attempt to scan/pick up items from the world to deliver to Warehouses (Yes/No) and whether they will clean up extraneous items from villager chests (Yes/No). This would let you optimize your setup and have Deliveryman that specialize in those certain tasks.

My main purpose for suggesting this change is my attempts to keep the warehouses from overflowing, as well as working with other mods to provide the villagers a constant stock of the items they need without me having to do it by hand. It would still be useful for vanilla players, of course, at least from what I can see.

**Comment by Raycoms** [comment] 2018-10-09 19:40
You can have multiple warehouses, just turn it on in the config. Although
there is still the limit of 5 dman per warehouse.

Am Di., 9. Okt. 2018 um 16:04 Uhr schrieb Jonathan <notifications@github.com

**Comment by Paril** [comment] 2018-10-09 20:36
Oh nice! Okay, I'll look into that. What's the reason for the limitation, just out of curiosity?

**Comment by Raycoms** [comment] 2018-10-09 20:43
performance, warehouses cost a bunch of performance on servers

Am Di., 9. Okt. 2018 um 17:36 Uhr schrieb Jonathan <notifications@github.com

**Comment by shammon5** [comment] 2018-10-12 06:22
Sorry, I started a new topic, but just saw this one. :P I have some suggestions for the warehouse too!

I've been trying to keep things in my warehouse organized, but it's a bit difficult because the deliverymen like to place items on random racks throughout my warehouse, sometimes without stacking. I had a full rack with 3 different spots used for stacks of 64, 15, and 37 of the same item. I can use inventorytweaks for sorting my own inventory and chests, but there isn't any compatibility yet with racks or a similar feature implemented.

Finding items in the warehouse is also a little troublesome because I have to search each and every rack for an item I need (since items are delivered to random racks). Maybe a simple computer-like interface for inventory of the warehouse could be good. For now I've been using RFTools storage scanner to make finding things easier in the warehouse, but it's a suggestion. :)

Thanks for all your hard work! You are an amazingly dedicated team!

**Comment by Nightenom** [comment] 2018-10-12 13:19
As I remember racks were supporting inventorytweaks but after some patches it went away
Searching wh was and still is causing headaches, in not so far future we might add some kind of stacking items from one mod together (@Raycoms would it be possible to do when migrating wh to the new BO?)

**Comment by Paril** [comment] 2018-10-12 20:54
I've been hooking up the warehouse to a RefinedStorage computer, that's
been very handy for management.

**Comment by PoroUsedSnax** [comment] 2018-10-14 19:12
As far as I'm aware InvTweaks has never inherently supported the racks, but there is a means I posted in #2453 that will allow it to work with them

**Comment by shivachirr** [comment] 2018-11-07 17:41
im going to add to this instead of adding a new topic. for the warehouse why not add a warehouse manager worker that cleans up the storage inventory. and also let the worker be a crafter along with you able to put alimit on how many items are stored. like i want there to be 1 stone hoe always for my farmers to use. or keeps a stack of torches for the miners.

**Comment by PoroUsedSnax** [comment] 2018-11-07 17:44
There are plans for a worker that will manage the warehouse in someway, presumably to sort it as you've suggested. The crafters will be multiple separate workers, not part of the warehouse

**Comment by ghost** [comment] 2019-05-11 20:17
As cool as a room full of chests is, maybe it's time to consider a dependency to simplify things? Something like Impractical Storage or Storage Drawers could provide a single location (limit CS support to the controller) for picking up/dropping off. (Plus, cool piles with IS.) Once the warehouse is operating on only a couple of inventories it becomes easier to add support for mods like Refined Storage and ideas for tracking multiple warehouses. I think it would also simplify #2186.

**Comment by Raycoms** [comment] 2019-05-11 20:27
Actually, the warehouse chest is an interface to all inventories of the
warehouse, we just have to construct the GUI for it =D

Am Sa., 11. Mai 2019 um 17:17 Uhr schrieb scribbler957 <
notifications@github.com>:

**Comment by ghost** [comment] 2019-05-11 20:29
Oh. I just assumed the performance was the workers trying to make sense of 40 chests.

**Comment by Raycoms** [comment] 2019-05-11 20:40
the problem is not the number of chests, the problem is the number of slots
to query (we are currently developing a better indexing mechanism for this)

Am Sa., 11. Mai 2019 um 17:29 Uhr schrieb scribbler957 <
notifications@github.com>:

**Comment by Raycoms** [comment] 2020-03-30 14:22
Closed in favor of joint issue.

**Closed as completed by Raycoms** 2020-03-30 14:22 UTC
