### ISSUE TITLE
Visual Duplication of Colonists

### ISSUE THREAD

**Issue by WPaul15** [ldtteam/minecolonies#2424] opened 2018-05-05 09:33 UTC
### Minecraft Version

- 1.12.2

### Minecolonies Versions

- 0.8.8160
- 0.8.8147
- 0.8.8140

### Forge Versions

- 14.23.3.2678
- 14.23.3.2674

### Expected Behavior

- Colonists should appear only once.

### Actual Behavior

- Occasionally, a colonist will suddenly appear twice. This doesn't seem to affect anything in-game, but I'm pretty sure that this shouldn't be happening. Below are some screenshots:

![2018-05-05_11 09 17](https://user-images.githubusercontent.com/16868897/39661663-b076ffee-5055-11e8-9341-a9efd731c92e.png)
A duplicated guard.

![2018-05-05_11 10 06](https://user-images.githubusercontent.com/16868897/39661664-b0c381ac-5055-11e8-83bb-16d25d8252a1.png)
It's a bit crowded in the house, but the Builder (Vera V. Gardiner) and the Deliverywoman (Parnell Cockayne) are in there twice.

### Steps to Reproduce the Problem

1. Load the game with any of the three MineColonies versions listed. (I've seen it in all of these versions, though it may be present in others as well).
2. (This is my theory as to what causes this, but I may be wrong) Go somewhere far enough away so that the colony is no longer loaded (The Nether or the End work as well).
3. Come back and look around for duplicated colonists.

**Comment by Raycoms** [comment] 2018-05-05 16:38
Yeah I think we have some issue on that already, we don't know yet what causes it, we're trying to prevent it by a few systems but are still working on fixing this.

**Comment by bongotezz** [comment] 2018-05-21 13:52
I can confirm that this is also happening in Minecraft 1.10.2 using minecolonies 9.7587. I don't even have to leave the area when it happens. I've used golden lasso to clean up some of the dupes but the builder would respawn one dupe if i lassoed one of them. 

https://imgur.com/a/Xz0wAcC

**Comment by Nightenom** [comment] 2018-05-21 14:05
Try using any version above 0.8.8235 included (https://minecraft.curseforge.com/projects/minecolonies/files). Duplication probably got fixed in this version.

**Comment by PoroUsedSnax** [comment] 2018-05-22 07:05
Yes, this has been fixed with #2461. On a side note, 1.10.2 has been lacking updates for a bit, given our small team and them needing time for University and such, so it's best to be on 1.12.

**Closed as completed by PoroUsedSnax** 2018-05-22 07:05 UTC
