### ISSUE TITLE
Smelters can't smelt the raw versions of ores

### ISSUE THREAD

**Issue by BarionLP** [ldtteam/minecolonies#7809] opened 2021-11-27 07:08 UTC
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.** I hope

### Context 

- Minecraft Version: 1.17.1
- MineColonies Version: 1.0.175

## Steps to reproduce the issue / details
Smelters can't smelt the raw versions of ores. 
It seems like they can't smelt copper ore at all but I'm not sure.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment] 2021-11-27 07:24
Duplicate of #7803

**Closed as completed by uecasm** 2021-11-27 07:24 UTC
Labels: Bug, AI Log
