### ISSUE TITLE
Warehouse disappears items

### ISSUE THREAD

**Issue by DestinyPlayer** [ldtteam/minecolonies#1233] opened 2017-06-24 17:41 UTC
### Minecolonies version

version 0.8.2488

### Expected behavior

- Items delivered by the delivery man should be deposited into one of the chests in the warehouse

### Actual behaviour

- They disappear completely and totally

### Steps to reproduce the problem

1. Build a warehouse T1
2. Build a delivery man T1
3. ...
4. Anti-profit

**Comment by Asherslab** [comment] 2017-06-24 22:42
Yep, this was fixed in one of the most recent versions @xavierh

**Comment by DestinyPlayer** [comment] 2017-06-24 22:43
Woop. Okay, thanks.

**Comment by xavierh** [comment] 2017-06-24 23:14
No. I fix the delivery man failing to deliver tools. However the tools
stayed in his inventory, nothing was lost.

I am not aware that the delivery man lose some items.

**Comment by DestinyPlayer** [comment] 2017-06-24 23:15
The items completely disappear when the delivery man tries to deposit the items into the warehouse. They're there in his inventory when I look, and then go _poof_ the moment he tries to put them down into the warehouse. I've checked all chests and the main block, nothing.

**Comment by xavierh** [comment] 2017-06-24 23:17
Did you check in all the chest from the warehouse?  He looks like he
deposit in the main chest but he does not.

**Comment by DestinyPlayer** [comment] 2017-06-24 23:18
Yes, checked every single chest in the warehouse. Empty.

**Comment by Terpo** [comment] 2017-06-29 06:09
I can confirm this bug in minecolonies 1.11.2 0.8.2488 on 1.11.2 with forge 2315

We have discovered this problem in two colonies. For now we fired the delivery men.

**Comment by Raycoms** [comment] 2017-08-13 01:18
Should be fixed by our new warehouse racks.

**Closed as completed by Raycoms** 2017-08-13 01:18 UTC
