### ISSUE TITLE
Most buildings level 5 Medieval Spruce refuse to be built.

### ISSUE THREAD

**Issue by JevilFromVSauce** [ldtteam/minecolonies#5632] opened 2020-08-21 12:59 UTC
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.161-ALPHA-universal.jar
- Structurize Version: structurize-0.13.42-ALPHA.jar
- Related Mods and their Versions:

## Expected behavior
1. Build up the building, place the stair and continue on building.

## Actual behavior
1. He just goes and tries to place down a stair (/mc citizen info 1 14) and then he just goes back and gathers materials before even placing down anything.
## Steps to reproduce the issue

1. Try and upgrade a building to level 5 using the Medieval Spruce blueprint.
2. There's like a 90% chance it won't build anything no matter what you do.
3. Cry because this happens so often.

### Logs

- latest.log: https://gist.github.com/JevilFromVSauce/974fdcd46e6d7327d9b1fa255bf57c95
- crashlog: 

### Notes

The builder is buggy but he is my slave and cannot deny me service.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment] 2020-08-21 13:29
Which buildings in particular?

**Comment by JevilFromVSauce** [comment] 2020-08-21 13:39
Both the Delivery Man level 5 and Cook level 5 are refusing to be built passed a certain point, I had a similar issue with the builders hut but was so sick of waiting I just copy and pasted the hut to level 5, and something miraculous happened with the warehouse 5 that had the exact same issue and after like 3-5 RL days of waiting, it finally built up, I think it was a fluke.

**Comment by lebanni** [comment] 2020-08-23 22:08
I don't know if it's related, but my carpenter stopped requesting spruce logs, allthough he knows the recipe to craft planks. In the builder's request log, only spruce planks are requested.

**Comment by Raycoms** [comment] 2020-08-24 16:28
Couldn't reproduce this. So I'll close this. If you can find AI reports or similar that would probably solve it. Else, I suspect it being a mod compat issue where a mod changes one of the items the builder needs.

**Closed as completed by Raycoms** 2020-08-24 16:28 UTC
Labels: Bug

**Comment by JevilFromVSauce** [comment] 2020-08-24 18:21
Ok, Also it turns out It got deliveryman done finally, it just randomally works, but it is still stuck on 14% for the cook.

**Comment by JevilFromVSauce** [comment] 2020-08-27 13:21
https://www.linkedin.com/posts/melatronine-dcx-84790b1b4_builder-bug-where-he-refuses-to-build-happens-activity-6704739189956648960-bfjN
