### ISSUE TITLE
Pathfinding fails when colonist is standing on half block

### ISSUE THREAD

**Issue by keldor314** [ldtteam/minecolonies#3110] opened 2018-11-27 14:21 UTC
### Minecolonies version
Version:  1.12.2 - 0.10.27 Release

### Expected behavior
Colonist should continue on to their destination.

### Actual behaviour
Colonist remains stuck where they are indefinitely.  Sometimes shoving them until they're standing on a full block fixes the problem.  Recalling them works.

### Steps to reproduce the problem
My delivery man gets stuck every time they go to the level 2 Medieval Fisherman's Hut.  The delivery point is on top of some wooden slabs on the "dock" portion of the structure.  The fisherman gets stuck in the same location.

**Comment by Raycoms** [comment] 2018-11-28 18:16
Do you have some special slab block?

**Comment by winsrp** [comment] 2018-11-28 18:22
same here... on normal slabs

https://ibb.co/bWdYjTx

I have also tried putting waypoints on intersections but its a big nope for them. (on the screenshot there is a waypoint on the "south intersection" and the "north intersection" (relative to the image not the map) and they still want to go sideways

**Comment by Raycoms** [comment] 2018-11-28 18:24
Uhm, 2 questions with this
1) Is there water under the halfslab at the fisherman?
2) Do you have an easy way to reproduce it?

**Comment by winsrp** [comment] 2018-11-28 18:30
on my case the easiest way to reproduce is with the guard tower, and put the guy on patrol, around the guard tower the path goes down a couple blocks, 1 step down each 5 blocks, guy just doesn't know how to get up.

**Comment by Raycoms** [comment] 2018-11-28 18:32
I'll debug it here

Am Mi., 28. Nov. 2018 um 16:30 Uhr schrieb winsrp <notifications@github.com

**Comment by winsrp** [comment] 2018-11-29 00:40
![image](https://user-images.githubusercontent.com/13665046/49191660-05c2b080-f33d-11e8-8d4f-6564056c9eb2.png)

**Comment by Raycoms** [comment] 2018-11-29 00:47
Yeah, I found the code, I got them to avoid going up, but they are still
going down. I need to fix that yet

Am Mi., 28. Nov. 2018 um 22:40 Uhr schrieb winsrp <notifications@github.com

**Comment by winsrp** [comment] 2018-11-29 00:49
check the fall, if its too big don't jump? don't see the issue going down? or maybe use the waypoint he has right next to it?

**Comment by Raycoms** [comment] 2018-11-29 00:51
Yeah, I'm trying to flesh it out. Pathfinding is never very easy to work
with.

Am Mi., 28. Nov. 2018 um 22:49 Uhr schrieb winsrp <notifications@github.com

**Comment by winsrp** [comment] 2018-11-29 01:02
u the man!

**Comment by keldor314** [comment] 2018-11-29 01:10
I caught my builder stuck on a stairs block earlier too.  It seems to be that they're confused if they're standing at a halfblock height when they try to path, rather than anything to do with the block itself.  Maybe they think they're falling, and won't path until they "land"?

In my case, there was a water block under the halfslab, which was just a regular wooden one (oak I think).  The stairs were just normal oak stairs in the builder's hut, and the builder had stopped while standing on them for some reason and then couldn't figure out how to get off.

**Comment by Raycoms** [comment] 2018-11-29 01:12
Difficult to handle yeah

Am Mi., 28. Nov. 2018 um 23:10 Uhr schrieb keldor314 <
notifications@github.com>:

**Comment by Raycoms** [comment] 2018-11-29 21:20
https://teamcity.minecolonies.com/guestAuth/repository/download/LetSDevTogether_Minecolonies_Branches_Build/22006:id/build/libs/minecolonies-1.12.2-0.10.198-PERSONAL-universal.jar

This should solve it, will be merged soon as well

**Comment by winsrp** [comment] 2018-11-29 22:13
will try it right away TX

**Comment by winsrp** [comment] 2018-11-29 22:28
they sure are jumpers now!... jajaja... one just went down 2 1/2 blocks taking 1 point of damage like it was nothing XD (I really don't mind the jumpling will be checking if they jump from higher up.

**Comment by winsrp** [comment] 2018-11-29 22:29
but the going up part seems to be fixed

**Comment by Raycoms** [comment] 2018-11-29 22:31
That's the max they're going to drop, max 3 blocks.

Am Do., 29. Nov. 2018 um 20:29 Uhr schrieb winsrp <notifications@github.com

**Comment by winsrp** [comment] 2018-11-29 22:42
do they do checks to see if they are going to fall/move into hazardous terrain?, is there a config to tell them to avoid certain blocks? I have punji sticks on floors and walls from tinkers, and they just keep hitting those?

**Comment by Raycoms** [comment] 2018-11-29 22:54
Actually, they check if the block on which they drop is walkable, like they
always did. They will only drop on stuff they would've dropped on
previously as well (just from height of 3 and not height of 1)

Am Do., 29. Nov. 2018 um 20:42 Uhr schrieb winsrp <notifications@github.com

**Closed as completed** 2018-11-30 12:30 UTC
Labels: System: Pathfinding
