### ISSUE TITLE
GUI not working

### ISSUE THREAD

**Issue by cathaldus2** [ldtteam/minecolonies#4047] opened 2019-11-05 23:18 UTC
### Minecolonies version

Version: 0.10.493-RELEASE-universal

### Expected behavior

- Expected townhall and other GUI menus to show lists

### Actual behaviour

- GUI lists are covered by the pale background, and only a couple items can be seen at the bottom of the screen.

![2019-11-05_17 08 42](https://user-images.githubusercontent.com/57420630/68254443-305ac600-fff0-11e9-98de-f5a229c14f3c.png)
![2019-11-05_17 08 38](https://user-images.githubusercontent.com/57420630/68254444-305ac600-fff0-11e9-8e24-e0bed4dab291.png)
![2019-11-05_17 08 19](https://user-images.githubusercontent.com/57420630/68254445-305ac600-fff0-11e9-8066-d5f042742d27.png)

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment] 2019-11-05 23:20
Duplicate of this: https://github.com/ldtteam/minecolonies/issues/3993

By chance, are you on a mac?

**Closed as completed by Raycoms** 2019-11-05 23:20 UTC

**Comment by cathaldus2** [comment] 2019-11-05 23:23
I am yes.

**Comment by Raycoms** [comment] 2019-11-05 23:24
Maybe you can contribute a few more details to the issues I linked so we can find out what is causing this particularly.

**Comment by cathaldus2** [comment] 2019-11-05 23:27
I saw another thread where this exact problem is going on. What do you need?

**Comment by Raycoms** [comment] 2019-11-05 23:30
Best to post the answer to this in that other thread: -java version, mac version, graphics card
