### ISSUE TITLE
Problem with OptiFine

### ISSUE THREAD

**Issue by Kocytos** [ldtteam/minecolonies#2420] opened 2018-05-03 15:40 UTC
Minecolonies version: minecolonies-universal-1.12.2-0.8.8140
Optifine version: OptiFine_1.12.2_HD_U_D2

Problem: 
![2018-05-03_17 38 35](https://user-images.githubusercontent.com/28514610/39587102-fc0450c8-4ef8-11e8-8652-8596fb0a32a5.png)

this is a Supplychest shematic lol

**Comment by Justen-N** [comment] 2018-05-03 16:14
Please see #2388.

**Comment by Justen-N** [comment] 2018-05-03 18:51
Kocytos, the issue is dealing with how optifine handles VBOs. I would try modifying your optifine settings,  to see if that would help, but this doesn't  look like a problem we can fix on our own.

**Comment by marchermans** [comment] 2018-05-03 19:03
Actually we can. It is just on the lower priority end of the task list.

**Comment by Justen-N** [comment] 2018-05-03 19:05
Oh, did you find something? Last I saw you weren't  very hopeful.

**Comment by Raycoms** [comment] 2018-05-03 19:06
We asked the Optifine devs and they linked us into a direction

**Comment by Justen-N** [comment] 2018-05-03 19:07
Got it.

**Comment by Raycoms** [comment] 2018-05-22 23:17
Closed inf avor of: https://github.com/Minecolonies/minecolonies/issues/2399

**Closed as completed by Raycoms** 2018-05-22 23:17 UTC
