### ISSUE TITLE
Miner level 5 broken

### ISSUE THREAD

**Issue by shivachirr** [ldtteam/minecolonies#414] opened 2017-01-02 08:57 UTC
### Minecolonies version

curse 1.10.2-0.6.2115

### Expected behavior

- Miner(level 4 and 5 building) reads it has pic

### Actual behaviour

- Miner (level 4 and 5)  dose not read it has a pick and says "I need a pickaxe of atleast     (note multiple spaces) grade and at maxium grade  (note multiple spaces) Grade.

### Steps to reproduce the problem

Just have miner level 4 and 5 as far as i can tell

**Comment by nojo121** [comment] 2017-01-02 10:32
I think @Raycoms already fixed it?
It'll be fixed in the next update i think.

**Comment by shivachirr** [comment] 2017-01-02 10:33
do you know when that is

**Comment by nojo121** [comment] 2017-01-02 10:51
sry i don't know.
ask @Raycoms xD

**Comment by Raycoms** [comment] 2017-01-02 11:08
The problem is that the miner level 5 can use any, therefore no maximum
grade. I've notified the responsible people of this.

2017-01-02 8:51 GMT-02:00 nojo121 <notifications@github.com>:

**Comment by shivachirr** [comment] 2017-01-02 11:09
yeah but it dose not seem to reconize it has a pick at this point

**Comment by Raycoms** [comment] 2017-01-02 11:10
okay that's strange. Did you give him a diamond pick. It's possible he
found obsidian.

2017-01-02 9:09 GMT-02:00 shivachirr <notifications@github.com>:

**Comment by shivachirr** [comment] 2017-01-02 11:11
diamond and a few modded ones i know the acctully addtions tools work on the lumberjack and builder but the miners wont do a thing with anything

**Comment by Raycoms** [comment] 2017-01-02 12:38
He might have found a ore with a very high grade. Can you try to give him a tinkers one with a really high grade (tinkers normal pickaxes he recognizes even with fancy materials)

**Comment by shivachirr** [comment] 2017-01-02 12:44
that did it the miner is working now may i suggest instead of the miner saying just in need a pickaxe for this make the miner say i can mine something

**Comment by Raycoms** [comment] 2017-01-02 12:45
We'll have him say "Need a higher tool" or similar soon.
I've notified the responsible =D

2017-01-02 10:44 GMT-02:00 shivachirr <notifications@github.com>:

**Comment by shivachirr** [comment] 2017-01-02 12:47
also i suggest you add info to you wiki saying what tools can the npcs use i mean it kinda should say that

**Comment by shivachirr** [comment] 2017-01-02 12:58
also i like confermation if weather or not you guys are moving on to 1.11 and abandoning 1.10.2

**Comment by Raycoms** [comment] 2017-01-02 12:58
Good point

2017-01-02 10:47 GMT-02:00 shivachirr <notifications@github.com>:

**Comment by shivachirr** [comment] 2017-01-02 12:58
also i like confermation if weather or not you guys are moving on to 1.11 and abandoning 1.10.2

**Comment by Raycoms** [comment] 2017-01-02 13:00
We are developing 1.10 and 1.11 on parallel.
Therefore, 1.10 as well as 1.11 will gain continuous support.

2017-01-02 10:58 GMT-02:00 shivachirr <notifications@github.com>:

**Comment by shivachirr** [comment] 2017-01-02 13:00
ok thx wanted to be sure

**Comment by shivachirr** [comment] 2017-01-02 13:22
o and one more thing sorry i keep doing this but add some info on how to add well user created buildings to the mod i looked all over and all ive been able to find out is you use the scan tool but nothing more or how to use it

**Comment by Raycoms** [comment] 2017-01-02 13:23
There is a youtube video on how to use it.
And we'll add it to the wiki as well.

2017-01-02 11:22 GMT-02:00 shivachirr <notifications@github.com>:

**Comment by shivachirr** [comment] 2017-01-02 13:23
well i have yet to find it or its jsut hard to find

**Comment by Raycoms** [comment] 2017-01-02 14:15
https://www.youtube.com/channel/UCqXDtO68H7ulwXW6tSlbmqA

2017-01-02 11:23 GMT-02:00 shivachirr <notifications@github.com>:

**Closed as completed** 2017-01-07 11:41 UTC
