### ISSUE TITLE
Farmer accidentally tramples farmland near fence gate when leaving field

### ISSUE THREAD

**Issue by darthvader45** [ldtteam/minecolonies#6304] opened 2020-12-27 18:41 UTC
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.543
- Structurize Version: 0.13.104

## Expected behavior

Farmer uses their fence gate as expected and exits the field.
## Actual behavior

The farmer goes to exit the field via the fence gate, jumps in place for a couple seconds (trampling the farmland they're standing on), then opens and goes through the fence gate.

## Steps to reproduce the issue

1. Get a farmer lv 3 or higher (needed for fence gates)
2. Let them plant their field, then wait...
3. Profit.

## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by darthvader45** [comment] 2020-12-28 02:26
Thanks Ray.  Knew this issue was a bit of a problem, as it likely would lead to farmers breaking their hoe a little too quick.

**Comment by uecasm** [comment] 2021-01-27 11:12
It does seem like there needs to be some improvement to the door/gate AI.  I frequently find colonists stuck with their face inside half a double door, sometimes opening and closing the other door, sometimes doing nothing at all.  After I open the door for them they continue on ok.  Similarly the jumping at fence gates rather than actually opening them at first.  (I also sometimes find two colonists trying to go through the same 1-wide doorway, alternating between opening and closing the door but jammed against each other so can't actually go through it.  This is especially bad after one guard wakes another as they tend to synchronise patrol routes after that.)

**Comment by Raycoms** [comment] 2021-01-27 11:41
There is some random handling on purpose. Gates and doors are hard to handle, especially when they are stacked together. That's why we used an intermediate compromise that always works but sometimes looks a bit derpy

**Comment by uecasm** [comment] 2021-01-27 20:09
The thing is that it doesn't always work.  Like I said, they'll get stuck in the doors permanently (or at least until end of day when they give up and go to bed, _usually_ making them go find a different door).  But then nothing gets done that whole day.  The fence gates are a bit better, but they still have the derpy jump thing.

I'm using the birch design, so I have a lot of fence gates, especially in the animal pens, so it's quite noticeable.  (Also the current system tends to let my rabbits escape quite frequently.)

I've actually had to remove the doors on the courier huts since they were the worst offenders.  Perhaps poor building placement is partly at fault (most of my buildings are very close together and they need to go through the courier hut to reach the warehouse) but both guards and couriers were getting permanently stuck in those all the time.

**Comment by someaddons** [comment] 2021-01-27 20:39
please report this in its own issue instead of randomly posting in another, aswell as adding the steps to reproduce, they're pretty important in this case

**Comment by Raycoms** [comment] 2021-01-30 16:25
https://buildsystem.ldtteam.com/guestAuth/repository/download/LetSDevTogether_Minecolonies_Branches_Build/66850:id/build/libs/minecolonies-0.13.1198-PERSONAL-universal.jar

Can you tell me if this fixes the problem?

@uecasm and @darthvader45

**Comment by tecnobrat** [comment] 2021-01-30 17:35
I'm testing this same build for the fix on #6458 but I can confirm that that build still has issues with citizens jumping 3-4 times before opening a gate.

**Comment by Raycoms** [comment] 2021-01-31 19:42
But no getting stuck, right? Just a bit of jumping.

**Comment by uecasm** [comment] 2021-01-31 20:12
They were never getting entirely stuck on gates, just doors.  But I haven't observed them getting stuck on doors for a few versions now, so perhaps that was already fixed -- or perhaps it was just because I removed the worst offending doors.  (Well, they still can get stuck, but only when there's an extenuating circumstance, such as it starting to rain, or two people trying to use the same door at the same time.)

But this particular issue was mostly about the jumping itself.

**Closed as completed** 2021-05-10 22:43 UTC
Labels: Bug, System: Pathfinding, Good First Issue
