### ISSUE TITLE
Minecolonies causing huge TPS drop in 1.16.4

### ISSUE THREAD

**Issue by iamnoobplzhelp** [ldtteam/minecolonies#6366] opened 2021-01-07 05:59 UTC
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.514-ALPHA-universal
- Structurize Version: structurize-0.13.102-ALPHA-universal
- Related Mods and their Versions: Mods located here https://www.curseforge.com/minecraft/modpacks/noobville/

## Expected behavior

Server runs at 20 TPS

## Actual behavior

When I'm running my server on the Modpack above, everything is running smoothly at 20 TPS. As soon as my wife logs in and goes to her minecolonies town, the TPS drops to ~4-7 and stays that low until I restart the server.

## Steps to reproduce the issue

Log into server
Walk to Minecolonies town

1. 
2. 
3. 

### Logs

Java profiler here: https://pastebin.com/0R6j2REG

- latest.log: 
- crashlog: 

### Notes

I'm guessing this has to do with some mod incompatibility. Minecolonies works fine on my 1.16.3 server, though I can't figure out which mod is doing it.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment] 2021-01-07 10:56
Can you please run a profiler?

**Comment by Raycoms** [comment] 2021-01-07 11:18
Sorry, I just saw the profiler just now, but that one is very hard to analyze. Can you run spark?

**Comment by iamnoobplzhelp** [comment] 2021-01-07 22:55
@Raycoms I ran it twice. First without going into the town:  https://spark.lucko.me/#LTG7T4U7hW
Then I ran it again after going into the town: https://spark.lucko.me/#VN57C3sGp3

I've never used spark before, but I can't seem to find the TPS here in the profiler. However, it does drop from ~20TPS to ~5TPS after opening the town.

**Comment by Raycoms** [comment] 2021-01-07 22:57
do you mean tps or fps?

**Comment by Raycoms** [comment] 2021-01-07 23:00
We have a config option to keep colonies loaded while someone is in them. If you have this turned on, this might load more chunks with other entities than your server can handle. From the profiler minecolonies is not the cause (we barely use any tps in either of the profiler logs). If you mean fps, that might be sth different.

**Comment by iamnoobplzhelp** [comment] 2021-01-07 23:00
I mean TPS. If there are FPS issues, then it's usually client side.

**Comment by Raycoms** [comment] 2021-01-07 23:02
Okay, I'll close this then because it is not minecolonies related. Either you have for some reason a lot of other mod entities or similar specifically in the minecolonies chunks or, by chance, you got the chunk loading turned on, you load a few more chunks of the colony and your server can't handle it. Nonetheless, there are a lot of other mods (like the bad weather mod using 15% of your server performance) you should report this to.

**Closed as completed by Raycoms** 2021-01-07 23:02 UTC
Labels: Bug

**Comment by iamnoobplzhelp** [comment] 2021-01-07 23:24
The profiler doesn't seem to suggest that too many chunks are loaded.

**Comment by Moleculor** [comment] 2021-01-07 23:37
> The profiler doesn't seem to suggest that too many chunks are loaded.

So as someone who is sorta watching this from afar and trying to learn how profilers work, can you point me towards where in the Spark report it suggests Minecolonies is the issue? I'm having a hard time finding much of Minecolonies in there at all.

**Comment by iamnoobplzhelp** [comment] 2021-01-08 01:36
@Moleculor it doesn't, and that's the problem. I only think it's a Minecolonies issue because it only happens when I enter a Minecolonies town. I don't think it's too many chunks loaded either, though. I have tons of chunks loaded and they don't cause this lag. It only happens in Minecolonies. However, I'll try some other stuff and tweak the settings.

**Comment by Raycoms** [comment] 2021-01-08 01:36
Affects any Minecolonies town?

**Comment by Moleculor** [comment] 2021-01-08 01:48
> enter a Minecolonies town.

It's a specific town in a specific part of your world, which means that it's loading a specific set of chunks, any one of which might be uniquely causing your TPS issues through some other mod doing something in that area. Or even vanilla Minecraft, if that rare weird bug still exists where massive numbers of passive mobs spawn in a single chunk. 

Take, for example, the Better Weather mod. If one or both of you are anywhere near a biome tagged as cold/snowy, you could still be running the old version of that mod that had a bit of a performance issue with those kinds of biomes. Since one or both of you load chunks that the mod was tripping over when you enter a colony, you could trip over that performance issue and boom, your TPS crater when you enter the colony. You associate the TPS drop with the colony, when in reality it's an entirely separate mod.

(PS: Update Better Weather. They may have just fixed a performance issue an hour or so ago, thanks to your profile report.)

You would need to likely create several different worlds with separate colonies and show that in each and every world the same issue occurs regardless of any other conditions in the world in order to be convincing that it's likely to be a Minecolonies issue.

**Comment by iamnoobplzhelp** [comment] 2021-01-08 01:48
I just have the one town; my wife's. I'm going to test some of the Minecolonies specific settings and I'll get back.

**Comment by iamnoobplzhelp** [comment] 2021-01-08 01:50
Hmm. I was having a lot of lag in Ice biomes due to Ice and Fire, specifically the dragons. I ended up turning off most of the Ice and Fire mobs and that solved most of the lag issues. My wife's town is near an ice biome, though. I'll have to try that, too. I'm also going to test turning off Better Weather.
