### ISSUE TITLE
Invisible Racks

### ISSUE THREAD

**Issue by mgwerner** [ldtteam/minecolonies#2051] opened 2018-01-19 05:31 UTC
### Minecolonies version

minecolonies-universal-1.11.2-0.8.6843

### Expected behavior

- Racks should be visible

### Actual behaviour

- Warehouse level 3, after logging racks are invisible.  Can be accessed by right clicking, and can move items to and from.  Moving item into rack inventory and closing GUI makes the rack visible.  No materials are lost.

### Steps to reproduce the problem

1. Log out and in
2. Go to warehouse
3. ...See hitbox of rack, but no rack
4. Profit

**Comment by Raycoms** [comment] 2018-01-20 00:31
Is there a way to reproduce this? I'm trying for a while already, but I can't seem to find a way =/

**Comment by mgwerner** [comment] 2018-01-20 04:41
It happens every time I go far away or to the nether and come back.  In those cases, I can interact with the racks and they become visible.  If I die, I have to log out and back in in order to interact with them.

I have the iron chest mod, which also has an invisible chest issue.  I took the mod out, in case it was related to that.  Same problem, racks in the warehouse are invisible.

**Comment by mgwerner** [comment] 2018-02-04 02:06
Have gone through several updates since reporting this, issue has not returned.  Warehouse was upgraded to L4, not sure what fixed issue, so closing.

**Comment by mkienenb** [comment] 2018-02-06 03:23
This is happened to me just now.   I have a level 2 warehouse.   I've never left the overworld.  The racks were populated by the deliveryman, not by me.  A single rack shows the "stuff on them" visual indicator.  The rest of the rack show as empty even though they contain many items.   I have not logged out of the game nor left the overworld since creating my warehouse and deliveryman, so the chunks have stayed loaded the entire time.

**Comment by marchermans** [comment] 2018-02-06 06:37
Yep I it is a known issue
We need to trigger a chunk update when we do that.

**Comment by mkienenb** [comment] 2018-02-06 16:19
I'm not sure I'm understanding you.   Are you saying that we need to trigger a chunk update when the deliveryman put something in the warehouse?

**Comment by marchermans** [comment] 2018-02-06 18:08
Yes. That is exactly what i am saying.
The DMan does not directly interact with the block in the way a user does. So he does not trigger a redraw of the chunk. Which breaks the Feature.

**Comment by mkienenb** [comment] 2018-02-06 18:46
Ok.  That sounds like it's simple enough for me to understand how to fix it.   I'll take ownership.

**Comment by marchermans** [comment] 2018-02-06 20:13
Yes it is relatively simple.
`World.setBlockState(BlockPos, IBlockState, int)` takes a `Integer` as third parameter. This third parameter is a Flag. If you pass it 3 (I think) then you update the chunk it is placed in it. Dig a bit in the source code to figure out what it calls to redraw the chunk.

**Comment by Asherslab** [comment] 2018-04-26 07:10
Is this still happening?

**Comment by Raycoms** [comment] 2018-05-22 23:06
This should be fixed.

**Closed as completed by Raycoms** 2018-05-22 23:06 UTC
