### ISSUE TITLE
Builder gets stuck in barracks

### ISSUE THREAD

**Issue by imnapr** [ldtteam/minecolonies#2724] opened 2018-08-02 20:07 UTC
### Minecolonies version

version 0.9.1 1.12.2
### Expected behavior
Wanted builder to upgrade citizen hut
- XXX

### Actual behaviour
Always goes through the barracks and gets stuck, turning in circles
- YYY

### Steps to reproduce the problem

1. Make builder do anything basically
2. Builder goes through barracks for some reason, get's stuck

**Comment by Nightenom** [comment] 2018-08-03 05:42
Are barracks in the way between citizen hut and builder hut?

**Comment by Wetz1990** [comment] 2018-08-09 07:52
I am also having troubles regarindg the builder and the barracks. When the builder is to upgrade/build the building he goes to one of the corners of the construction site and just stands there with all the materials in his inventory, but does nothing.

**Comment by Raycoms** [comment] 2018-08-09 11:47
The problem is that the barracks have big areas underground so the builder needs a bit to scan all of this.

**Comment by Raycoms** [comment] 2018-08-09 23:13
The barracks have a huge underground structure he will need a while to scan
this

**Comment by Raycoms** [comment] 2018-09-03 20:25
Should be fixed

**Closed as completed by Raycoms** 2018-09-03 20:25 UTC
