### ISSUE TITLE
Update University 2 -> 3 (birch)

### ISSUE THREAD

**Issue by Waxime64** [ldtteam/minecolonies#7032] opened 2021-04-28 23:01 UTC
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: forge-1.16.5-36.1.13
- MineColonies Version: minecolonies-0.14.134-ALPHA-universal
- Structurize Version: structurize-0.13.169-ALPHA-universal
- Related Mods and their Versions: 

## Expected behavior
Upgrade university 2 -> 3

## Actual behavior
Upgrade is stock at 0% and builder only make the road between builder and university without add block
![image](https://user-images.githubusercontent.com/10803383/116483221-aaba7e00-a854-11eb-824b-c546be851186.png)

## Steps to reproduce the issue

Play in Survie and update University
https://www.twitch.tv/waxime64/videos <- make 2 days a try to update university and always block at level 2

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment] 2021-04-28 23:04
Fill in template please

**Comment by Waxime64** [comment] 2021-04-28 23:13
I make a video to show the problem
https://www.twitch.tv/videos/1004330143

**Comment by Waxime64** [comment] 2021-04-28 23:17
> Fill in template please
Raycoms, you are little too fast to close bug. I didn't have enough time to fill it and make my video

**Comment by Raycoms** [comment] 2021-04-28 23:19
Usually people fill in the template before submitting it =D

**Comment by Waxime64** [comment] 2021-04-28 23:23
> Usually people fill in the template before submitting it =D

no problem and I make a video to show no block is put every time and that make 2 day I try to upgrade it. I try to repair it and after upgrade too

Oh yes, I break my anvil in university during level 2, but now they are present after repair

**Comment by Waxime64** [comment] 2021-04-29 05:45
After 6 more hours of playing and with fill completly the eventory of the builder ... always 0%
![image](https://user-images.githubusercontent.com/10803383/116507031-7fec1c00-a88c-11eb-815e-65fc67d27787.png)

**Comment by fr3akb0y** [comment] 2021-04-29 18:42
This is currently happening to mee too (since updating from 131 to 134). This happens on every building when upgrading but weirdly not when repairing. The Builder is stuck in a loop of GATHERING_REQUIRED_MATERIALS and just picks up 1 ItemStack at a time until the inventory is like half full.
I just checked on what version it starts happening since I downgraded back to 131 and it worked again and it stops working when upgrading to 132 so this version might be at fault?
Also reloading seems to super rarely work for 1 block at a time. And if reloaded the state goes into NEED_ITEM (or something like that) and to INVENTORY_FULL even with an empty inventory.
That is all I could gather. Hope it helps here since I too cannot do anything with my builder right now :P

**Comment by Waxime64** [comment] 2021-04-29 18:46
I destroy my building completly in this moment, I put my game in peacefull and now I rebuild completly to see if that append again. I check if tomorrow my university is now done at level 3. Remember, I play in survival.

**Comment by Waxime64** [comment] 2021-04-30 23:04
I destroy my University 2 and rebuild with exactly same style. Same problem exactly same place during build.
I create a new video
https://www.twitch.tv/videos/1006627778

**Comment by erbauerderbeste** [comment] 2021-05-03 20:16
This bug is affecting me too, but only for the university (though I can't say yet wether it is just when upgrading from level 2 to level 3), allthough for me the builder gets stuck at 36%, and then request 6 additional water bottles on top of the 3 she initially requested. I tried multiple things: Restarting the build, rehiring the builder, completly clearing the builders (hut) inventory, I even built another university, upgraded it to level 2 and then tore it down completly, the builder still gets stuck at 36%. Maybe it has something to do with the placement of brewing stands containing water bottles or other potions? I will try downgrading my minecolonies version, maybe that'll help

**Comment by fr3akb0y** [comment] 2021-05-04 06:55
Hmm weirdly enough there seems to be a pattern with upgrading from level 2 to 3. I didnt say that in my comment but this issue first occured to me when upgrading my alternative medieval oak builder from 2 to 3. Since then that builder hut cannot be upgraded to 3 anymore. I then downgraded to 131, build another builder but that one could upgrade to 3 but the original builder still cannot. It can be repaired in level 2 though. But yeah everything I tried upgrading in version 132 or higher seemed to be broken. Only the builder error came through downgrading to 131. (I am currently not updating anymore cause I am scared if that happens to other things >.< should try that with a backup)

**Comment by ravenbuilder934** [comment] 2021-05-11 16:48
If it stopped working after updating to 132, it looks like this is Structurize's fault then, as 132 bumped its version. but it doesn't look like either of the two changes in that version could cause it either. are you *sure* it was 132's fault? Does it still happen in the latest?

**Comment by fr3akb0y** [comment] 2021-05-16 14:19
I now tested a few more situations but for some reason I now cannot even reproduce anything other than that one builder hut.
I tested versions 131, 132, 133 and the current newest 162 with always building 3~4 builders pasting level 2 in and upgrading to level 3. I also did different stiles and I made following observations:
1. Builder huts with racks a floor under the hut block (mostly basement) take longer to take resources since they for some reason only get 1 item at a time rather than standing still and taking everything they need from that rack.
2. Of all stiles I put down only the 'medieval oak alternative' one takes a really long time to obtain the needed items.
3. While building the medieval oak alternative builders hut from 2 to 3 they always palced a few netherbrick blocks and than it took them about 5 minutes to continue while continuously running to the basement and back to the hut block. Maybe this has to do with trying to place buildings in a filled area and not correctly reaching because the basement would get an extension and since he only digs away the dirt at the end of upgrading it might mess up something.

At the End I also tried to deconstruct my broken builder and rebuild it (even assigning a new builder), but nothing worked. Even when picking up and placing a new builders hut other than the picked up one it doesnt work. Maybe my colony is just cursed I am out of Ideas xD

**Comment by fr3akb0y** [comment] 2021-05-16 14:22
Ahh and also I dont know if the way a building is rotated decides where the Builder starts building but they take different times (sometimes about 3x times faster) than others in certain rotations so I thought about them having not enough time before bed but doDaylightCycle=false doesnt help so prob not.

**Comment by Raycoms** [comment] 2021-06-07 11:47
Should be fixed by now.

**Closed as completed by Raycoms** 2021-06-07 11:47 UTC
Labels: Bug
