### ISSUE TITLE
Massive log file.

### ISSUE THREAD

**Issue by attilavv** [ldtteam/minecolonies#2094] opened 2018-01-26 23:11 UTC
### Minecolonies version

First detection :
forge-1.12.2-14.23.1.2665-universal + minecolonies-universal-1.12.2-0.8.6905 ( and other version )
Lastest test :
forge-1.12.2-14.23.1.2604-universal + minecolonies-universal-1.12.2-0.8.7200

### Expected behavior

No log, reduct log to minimum, place a option in config file for stop log, place this log in separated file.

-------------------
run /mc colonies rsResetAll in Version: 1.12.2-0.8.7193 ( read in description )
Same problem.

Massive LOG file. 2531 entry in one second in file fml-junk-earlystartup.log

[12:07:16] [Server thread/DEBUG] [minecolonies]: Attempting to find a Factory with Primary: com.minecolonies.api.colony.requestsystem.factory.FactoryVoidInput -> com.minecolonies.api.colony.requestsystem.data.IRequestSystemBuildingDataStore
[12:07:16] [Server thread/DEBUG] [minecolonies]: Found matching Factory for Primary input type.

Log file : Reducted file from a server start to stop.

[fml-junk-earlystartup.log](https://github.com/Minecolonies/minecolonies/files/1669467/fml-junk-earlystartup.log)

**Comment by Raycoms** [comment] 2018-01-26 23:12
2 questions:

a) do you have some log4j setting somewhere which trigger this?
b) Do you have the debug log of the request system turned on in the file?



2018-01-26 23:11 GMT+00:00 attilavv <notifications@github.com>:

**Comment by attilavv** [comment] 2018-01-26 23:24
Not for me. I don't have found or set a option for this.
And no debug file found for me.

Edit : log4j  is a software dev. Possible other mod use it and have activated it. but not me.

Edit : Memory usage + disk usage from Verygames in picture.
Same problem for fml-junk-earlystartup.log Now very very very big and before just big.

![rammemory](https://user-images.githubusercontent.com/35277791/35465416-12ddd88a-02fc-11e8-8232-ad8dde2c915f.jpg)

**Comment by attilavv** [comment] 2018-01-29 14:40
Hi,
Some news.
After removed all other mod, one by one.
It is only minecolonies.

For reproduct

Use MultiMC5
Create news instance.
Install forge ( recommanded for this test but same problem with beta version of forge )
Install minecolonies-universal-1.12.2-0.8.7200

run and create news world in creative, flat world.
( i have set difficulty in passive )

Place a supply camp, place a town hall, place two builder ( for my test ).

Goto folder logs and edit fml-junk-earlystartup.log
With Notepad++ you can refresh and reloading after some time and see news entry.
With more villager it is more and more entry.

For information : It is no entry in night and when is rain.

----------------------

You can see, if builder have ressource in chest, it is no action.
See issues : #2105

**Comment by marchermans** [comment] 2018-01-29 16:20
I did this. And I can not reproduce this.

**Comment by marchermans** [comment] 2018-01-29 16:22
I am sorry. But I have tested this over 10 times now in different configurations. I even asked in IRC what could do this. And everybody keeps telling me that you either are using a version that is not intended for public use, which is highly unlikely. Or you have something in your configuration that makes it so.

**Comment by attilavv** [comment] 2018-01-29 18:11
[fml-junk-earlystartup.log](https://github.com/Minecolonies/minecolonies/files/1674746/fml-junk-earlystartup.log)
[latest.log](https://github.com/Minecolonies/minecolonies/files/1674749/latest.log)
[fml-junk-earlystartup.log](https://github.com/Minecolonies/minecolonies/files/1674751/fml-junk-earlystartup.log)


Yes it is possible that my computer have some trace of dev.

Don't close this issues, i have needed some help for testing in my team.
I i can make some action for you, let me a description.

I have see same issue for Minecolonies ; #2013 
I found another trace of this problem on Forge too.

What is strange ... this problem is found on my server ( Verygames have probably no virus on machine ) and on my computer. I continu to investigate.

Edit : add full fml-junk-earlystartup.log file 
[fml-junk-earlystartup.log](https://github.com/Minecolonies/minecolonies/files/1674757/fml-junk-earlystartup.log)

[latest.log](https://github.com/Minecolonies/minecolonies/files/1674762/latest.log)

[fml-client-latest.log](https://github.com/Minecolonies/minecolonies/files/1674763/fml-client-latest.log)

Edit ; [15:24:52] [Server thread/ERROR] [FML]: An Entity minecraft:villager(Villager) has thrown an exception during loading, its state cannot be restored. Report this to the mod author

Probably never read with this problem of masive file.

**Comment by marchermans** [comment] 2018-01-29 21:22
@attilavv This is not a Minecolonies error.
From the Log you can clearly see that you are also getting Trace and debug log messages from other thinks. For example FML and Forge.

It is just that Minecolonies Factory system does extensive debug logging to keep track of objects in case we need the data.

But under normal Forge operations this does not end up in the .log file since Log4J is configured to hide it.
As stated this is not a Minecolonies error. Nor is it something we can change. I am going to close this issue now. If you need support for this. Ask the Guys from MinecraftForge or SpongeForge depending on what server you are running.

**Closed as completed by marchermans** 2018-01-29 21:22 UTC

**Comment by Raycoms** [comment] 2018-01-30 17:28
The newest version should resolve this now.

**Comment by attilavv** [comment] 2018-01-30 17:48
Or not "closeman team" !

[18:38:55] [Server thread/DEBUG] [minecolonies]: Attempting to find a Factory with Primary: com.minecolonies.api.colony.requestsystem.factory.FactoryVoidInput -> com.minecolonies.api.colony.requestsystem.token.IToken
[18:38:55] [Server thread/DEBUG] [minecolonies]: Found matching Factory for Primary input type.
[18:38:55] [Server thread/DEBUG] [minecolonies]: Found input factory with matching super OUTPUT type. Search complete with: com.minecolonies.api.colony.requestsystem.token.InitializedTokenFactory@38913b95

Don't panic i have open many issues for you in EU, in France, in Deuchland and other big team probably come for help you. But you can't contact Forge team for help. 

When your team say : From the Log you can clearly see that you are also getting Trace and debug log messages from other thinks. For example FML and Forge.

YES i use Forge and YES i use FML but it is Forge Mod Loader and YES you can found trace of Minecraft too.


Edit ; Version is minecolonies-universal-1.12.2-0.8.7264

**Comment by Raycoms** [comment] 2018-01-30 17:50
![image](https://user-images.githubusercontent.com/6438347/35582199-044a2c0a-05e6-11e8-9c9c-35ab19227872.png)

**Comment by attilavv** [comment] 2018-01-30 18:00
![mineco](https://user-images.githubusercontent.com/35277791/35582562-75794506-05ef-11e8-9ce7-2969b2e46bf0.jpg)

Possible that you ignore another thinks on how works github.com but you are admin and not me.
Have you direct link ?

**Comment by Raycoms** [comment] 2018-01-30 18:12
I meant to say, it's still under review.

2018-01-30 18:00 GMT+00:00 attilavv <notifications@github.com>:

**Comment by attilavv** [comment] 2018-01-30 18:31
Ok .. no problem .. why not reopen this issue ?

And for duplication, it is comic When you say ;

> Yeah this happens occasionally unfortunately, it seems to be minecraft which causes this. Please restart to fix it.

See #2103 closed too.
My team have found same bug #1992 

What is a bug for you ?
Only for the same computer, same windows that your ?

And YES my team, i works for the biggest team in FR and probably in EU.


Now Wait and see "closeman" !

**Comment by Raycoms** [comment] 2018-01-30 18:36
Like we said, the workers occasionally copy themselves, it is minecraft who
seems to do it with entities, simply restarting fixes this.
And we fixed the log issue and we leave it closed because the fix is on the
way to curse already.

How you use github:

a) You discuss objectively (Something you're not doing).
b) You close an issue as soon as the fix got merged (What we're doing).
c) When you believe the error is not on your side (What we're doing).

And I don't care how big your team is, I can't believe it is as big else
you'd treat people who do this for free in their free time with more
respect.

2018-01-30 18:31 GMT+00:00 attilavv <notifications@github.com>:

**Comment by attilavv** [comment] 2018-01-30 20:20
That good ! Good Jobs for this issues !

a) Read my first issue, only report for 3 probable bugs. Probably resolved the nomber 3, massive lag, massive CPU usage. What you want more ? Read what you have say for 3 issues ! ! !

> 

We do not chunk load anything. This is not caused by minecolonies.
--

Result ; at this time you have one problem ONLY but "(Something you're not doing)" ! ! !

b) Yes that good for this. 

c) False ! Your team have one method ; Not me ! not me ! not my team. Contact Forge but FML is bugged ! Imagine how they laughed at Forge when i have open a "issues for your bug" and go read what your team say.

Now, all is a big team, Forge, Your team, my team ...
All works for FREE ...
All make video for FREE ...
All make live for FREE ...
You can have a Smartphone for FREE too ...

But all accept money from donation, all from my team and you too !
All accept money from subcriber and you accept money from Patreon !
But all need advertising and you too !


Good job "closeman" but for me you are my friendly "closeman"

**Comment by Raycoms** [comment] 2018-01-30 20:27
If you look at our issues, we have around 120 open issues and around 2000 issues we closed already. 
Around 10 of the issues we said it's not our fault.
Of those 10 issues probably, 8 the fault was of another mod and 2 we said the fault is with minecraft itself.
We never said its with forge.

and again a) I read it and I'm still being respectful and reasonable.
If you do so much for free I invite you to clone minecolonies and fix the things yourself and stop being so rude.
