### ISSUE TITLE
Builders standing in one place after i issue a command.

### ISSUE THREAD

**Issue by Cavemanuni** [ldtteam/minecolonies#664] opened 2017-02-28 05:35 UTC
### Minecolonies version

version 1.11-0.6.2919

### Expected behavior

- chatBox:"Build Request Created!"
- chatBox:"Started Building 'type/name of building' "
- NPC starts acquiring materials, clearing area, building structure (with the occasional "name" needs more "number" "material")
- chatBox:"Finished building"

### Actual behavior

- chatBox:"Build Request Created!"
- NPC stands where he was when he completed his/her last building

### Steps to reproduce the problem

I am not sure as to how his is caused so i cant give the steps directly, and this does not happen consistently from what i have seen. This happens upon the requesting a build either by just placing the "building block" or by using the "magic wand." Once the command is issued the builder assigned to it (shown in the town hall) will proceed to stand there and do nothing. The message showing that he has received the job does not even show (chatBox:"Started Building 'type/name of building' "). This has happened on two different worlds, it has happened with my own personal structures and with actual buildings/structures with this mod. This "Glitch", i presume unless i am a complete idiot and am missing something, is not just limited to brand new orders(which they occasionally stop in the middle of and is fixed by firing and re-hiring them) but is also possible when issuing an upgrade. As said before i am no able to state the reason for why it is happening but i hope this will help and bring a possibly big bug into light.

**Comment by Cavemanuni** [comment] 2017-02-28 05:39
Correction: "Once the command is issued the builder assigned to it (shown in the town hall) will proceed to stand there and do nothing."->The statement "(shown in the town hall)" is in relation to upgrades not new buildings which is fixed by "(which they occasionally stop in the middle of and is fixed by firing and re-hiring them)"

**Comment by marvin-bitterlich** [comment] 2017-02-28 07:11
Can you check the builders hut what materials he needs? What if you supply them?

**Comment by Cavemanuni** [comment] 2017-02-28 07:37
Yes i can check the builders hut's materials and it shows up empty. From my observation its not so much as they don't have the resources as it is more of i don't have the chance to give them the resources. Once the build is activated, i assume it is supposed to show the message "Started Building 'type/name of building' " like it has with all of the other buildings i have made(being multiple thriving colonies with several buildings at max level 5), instead no message is shown, the builder stands where ever he was when the build was originally placed, and in the town hall it shows the different build "opportunities" with no one assigned to them(being the NPC's name under the title of the structure).

Here are three pictures to hopefully show a bit of a better idea of what is going on. During the time of all three images i have three projects i am currently trying to build while having one available builder that has a level 2 builders hut, a custom road made of gravel, upgrading the mine, and building a new guard tower(not upgrading).

![2017-02-27_23 32 10](https://cloud.githubusercontent.com/assets/26078575/23395790/50fc0168-fd45-11e6-9cf5-91fdeb76af37.png)

![2017-02-27_23 33 53](https://cloud.githubusercontent.com/assets/26078575/23395791/50fe16e2-fd45-11e6-859b-7820b7da4187.png)

![2017-02-27_23 34 07](https://cloud.githubusercontent.com/assets/26078575/23395792/50fe1b7e-fd45-11e6-918e-d3c02bcf3bf0.png)

**Comment by Cavemanuni** [comment] 2017-03-01 06:15
This problem has now just happened on a colony that me and a friend have just made. Can i email the file to this world to you so you just need to extract and plug it in and see what is happening? This is preventing me and my friend from doing anything with this mod once the builder "Locks."

**Comment by Cavemanuni** [comment] 2017-03-01 06:35
Actually i just started another world and it started immediately, so it has a smaller file size. if you want the other one i will be happy to send you that one to.
[Colony.zip](https://github.com/Minecolonies/minecolonies/files/809861/Colony.zip)

**Comment by marvin-bitterlich** [comment] 2017-03-01 06:43
The not requesting will be solved with #638 
Question is if there are other bugs ;)

**Comment by Cavemanuni** [comment] 2017-03-08 01:35
This may or may not be a bug, but my miner currently has a pick, shovel, torches, oak planks, oak fences, and ladders. however the miner is just standing by the LV 2 miner block. The miner isn't even asking for anything. out of the 4 colonies that i have on different worlds this is the first time this has happened so i don't know how credible it is.

**Comment by Balu-bln** [comment] 2017-03-12 14:26
Ill encountered the same problem since 3 days in 3/4 worlds, in the 3rd game no citizen spawned after placeing a townhall a builders hut and a chitizens hut even after 5 minutes waiting. The worlds were fresh, ill reinstall minecraft and the mod today and will post if it will be fixed.

**Comment by Raycoms** [comment] 2017-03-12 14:34
citizens always should spawn. is there enough space around the townhall?

2017-03-12 11:26 GMT-03:00 Balu-bln <notifications@github.com>:

**Comment by Balu-bln** [comment] 2017-03-12 15:01
yes it is enoth but if i command "/gamerule doDaylightCycle false" they would never spawn so ill some kind of fixed this maybe maybe not bug.

**Comment by Raycoms** [comment] 2017-03-12 15:02
Yeah "/gamerule doDaylightCycle false" this hinders them from spawning. Why
don't you set up a commandblock connected with a daylight sensor to make it
/time set 0 every time it triggers to night?

2017-03-12 12:01 GMT-03:00 Balu-bln <notifications@github.com>:

**Comment by Balu-bln** [comment] 2017-03-12 15:09
nice tip thanks :) i will do that, the "lazy builder" as Cavemanuni descriped is still a problem. I will test some more worlds, maybe it is a map problem. Maybe it is a incompability with another mod i will test that to and report back if i find something.

**Comment by Raycoms** [comment] 2017-03-12 15:23
Builders seem to get stuck from now and then, usually if they can't get to
a place where they want to build from. But that usually repairs itself from
alone.

2017-03-12 12:09 GMT-03:00 Balu-bln <notifications@github.com>:

**Comment by rscott6666** [comment] 2017-03-12 16:35
The easy way is to just let him stand outside the build zone, but that (to
me), is aesthetically unpleasing.

**Comment by Raycoms** [comment] 2017-03-12 16:36
At the moment he calculates a position outside of the build zone to build
from there.
It would be cool to calculate a dynamic position depending on the block he
will build and will walk around the building while building.

2017-03-12 13:35 GMT-03:00 rscott6666 <notifications@github.com>:

**Comment by Balu-bln** [comment] 2017-03-14 17:12
**## So far the bug never happens again. This time i installed the mod via the curse mod pack "MineColonies TestPack"** (cause i wanted to check up the server together with my girlfriend ;) ) I think the problem only occures when u install the mod on itself without the pack. So i think its not a bug as all wiki and tutorials point that u have to **## install the full pack**.

**Comment by marvin-bitterlich** [comment] 2017-04-18 10:05
I close this for now, comment if it needs reopening

**Closed as completed by marvin-bitterlich** 2017-04-18 10:05 UTC
