### ISSUE TITLE
Builders items disappear

### ISSUE THREAD

**Issue by SlavikSnek** [ldtteam/minecolonies#5552] opened 2020-08-11 17:25 UTC
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version: minecolonies-0.13.81-RELEASE-universal
- Structurize Version:structurize-0.13.32-RELEASE

## Problem description
Sometimes when i give my builder items the blocks will disappear and the builder will ask for them again and will have to get even more blocks to them.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment] 2020-08-11 17:27
Duplicate of #4905

**Closed as completed** 2020-08-11 17:35 UTC
