### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by Chaoszokker** [ldtteam/minecolonies#2466] opened 2018-05-22 10:58 UTC
### Minecolonies version

version 0.8.4063 in the Modpack The Simple Life 1.6

First hello to the development team.

I have an idea what could be improved on the mod.

Because it is very time consuming when you have to find out with some villagers what they are missing now again. How about if you just insert a line of text in the villager's view and then what is the villager missing?

That would simplify the day for all.

I have currently in my stream always the problem that the worker puts his work and there is no indication of what he lacks or why he no longer works. No information in the chat or anywhere and I have to go then always on the search why he no longer works. The last time he lost a block too much, no ladder set, so his workplace was probably no longer accessible. I just had to put a ladder and he resumed work.

In addition, a manual would be good in it in there is how to start with the mod s.besten how you can for example create a forge or a stonemason, because I have not found out yet. Furthermore, it would be very good if you could insert the villagers needed mats would get from the warehouse, because it is very annoying when you are currently busy with another mod and a Villager is missing again a ingredient so that he can continue working and you have his interrupt work.

Furthermore, I have often stuck the mistake of the villagers in a house when the house of 2 villagers is occupied. The villagers then want to get out of the house at the same time, because you can shove in mycraft again, but then they are always stuck. If you do not notice the two then the whole day only door open, door closed. You then have to get one of the workers back to work so the other villager can leave the house. And then you have to check every day also whether the two stuck again in the front door or not.

**Comment by PoroUsedSnax** [comment] 2018-05-29 17:43
For future reference, it would be greatly appreciated if you could fill out the issue template and maybe split issues up, it helps us to quicker see what the problem is. :D

Anyways, I was about ready to give some information on the issues but I noticed you are running 4063, our current alpha version is up to 8402, so it's definitely worth updating, there are lots of nice features in these past 4000 or so builds.

I can say in-terms of a manual, you can visit our [wiki](https://wiki.minecolonies.com). One of our contributors is working on implementing our own book to the mod, which will update its content from a newer wiki (currently in the works). The stonemason and forge are yet to be implemented but are on their way.

**Comment by Justen-N** [comment] 2018-05-29 22:14
Main issue is that the 8000 + builds haven't been backported to 1.10, which
is where the simple life  modpack lives.

**Comment by marchermans** [comment] 2018-05-30 06:10
However 1.10 is 2 major Minecraft versions behind, nearly three. Certain things are host not portable and then the music stops for that version.

**Comment by Nightenom** [comment] 2018-08-01 09:24
@ColonelJN Please update to the latest version (and go check if your issues are solved) or stay with 1.10 but then close this issue

**Closed as completed** 2018-09-03 20:22 UTC
