### ISSUE TITLE
ATM 10 players being kicked from server suggest Minecolonies is the problem

### ISSUE THREAD

**Issue by ncottrill** [ldtteam/minecolonies#10437] opened 2024-11-12 00:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.776-1.21.1

### Structurize Version

1.0.754-1.21.1

### Related Mods and their Versions

NeoForge 21.1.74
blockui-1.0.192
domum_ornamentum-1.0.204

### Current Behavior

This error keeps happening to players in ATM 10 modpack. Players are saying it happens when they enter or leave a Minecolony. For me, it happens randomly when I think I'm in the colony, but it could be where FTB Teams and Minecolonies boundaries intersect.

[disconnect-2024-11-11_14.28.28-client.txt](https://github.com/user-attachments/files/17709240/disconnect-2024-11-11_14.28.28-client.txt)

### Expected Behavior

I really want to stay connected to the server.

### Reproduction Steps

Install ATM 10
Make an FTB team
Claim FTB chunks that overlap the boundaries of a Minecolonies colony
Wait to get kicked from the server as you move in and out of various team / colony boundaries.

### Logs

https://gist.github.com/ncottrill/f7929d00e8406519e659c247ebaf6284

### Anything else?

ATM 10 Discord - #ATM10-techsupport channel has discussion

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ibrudiiv** [comment] 2024-11-12 04:31
Seems to be more frequent in ATM10 1.18. Just updated and got the error immediately upon entering the world. And have gotten it 2 more times within 10 minutes.

**Comment by Talyda** [comment] 2024-11-12 06:39
Claiming colony area with other claim mods can  mess a lot of things up

**Comment by Moobien** [comment] 2024-11-12 06:41
I can't see anything in that log that even indicates minecolonies is the issue.

**Comment by Thodor12** [comment] 2024-11-12 07:42
We have already gotten a second report of this, closing as duplicate of #10425

**Closed as not planned by Thodor12** 2024-11-12 07:42 UTC
Labels: Bug
