### ISSUE TITLE
Builder does not start building

### ISSUE THREAD

**Issue by Powerminer11** [ldtteam/minecolonies#6654] opened 2021-03-03 19:01 UTC
- [ x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.669-alpha

## Steps to reproduce the issue / details
One of my builder does not start building after recieving an order. The chat never says: "(builder) has started building (building name)" I have tried to fire and rehire him. Fired him and hired another worker. The issue seems to affect whatever builder that uses that specific builders hut and whatever building he is trying to build. My other builder works just fine. 

The log says:
[19:29:59] [Server thread/INFO] [minecolonies/]: WorkOrderBuild at location BlockPos{x=376, y=74, z=879} is using schematics/caledonia/plantation1 instead of schematics/caledonia/plantation1
19:29:59.940
[19:29:59] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] Build request created!

So the request is created, but the building doesn't start and the builder just wanders around without requesting any item or doing anything useful.

Here is more of the log: https://paste.ubuntu.com/p/Jznq5y5N7f/

**Comment by Raycoms** [comment] 2021-03-03 19:05
Are you sure the task got assigned to this particular builder? Did you try direct assignment in the UI? Did you try recalling the builder?

**Comment by Powerminer11** [comment] 2021-03-03 20:06
Yes, the task was assigned to that particular builder, and I tried recalling.

**Comment by ravenbuilder934** [comment] 2021-03-03 20:10
is the builder sick or hungry?

**Comment by harmalom** [comment] 2021-03-03 21:32
I have a similar problem, it seems that the builder can't pick up the materials from his station and stands still indefinitely waiting for something, it just doesn't do anything.
It has all the materials and is not hungry.
Version:
 minecolonies-0.13.669-ALPHA-universal
forge-1.16.5-36.0.43

**Comment by Powerminer11** [comment] 2021-03-03 22:10
No he is not sick or hungry

**Comment by ravenbuilder934** [comment] 2021-03-03 22:11
if you right-click on him and hover over the icon in the top right, does it say Working? (you too @harmalom)

**Comment by Raycoms** [comment] 2021-03-03 22:13
Can you try the newest alpha that's going to come out in a minute?

**Comment by Powerminer11** [comment] 2021-03-03 22:17
It's in the middle right and it says Working. I'll try the newer alpha

**Comment by Powerminer11** [comment] 2021-03-03 22:32
Been on the newest alpha for a few minutes now, and he still doesn't do anything. It says working though

**Comment by sboigelot** [comment] 2021-03-03 23:29
@Powerminer11  I had the same issues as you but fixed it by cancelling the build and re starting the build order. You may want to try that too

**Comment by Powerminer11** [comment] 2021-03-04 00:16
Tried that a few times, didn't work

**Comment by gnamly** [comment] 2021-03-04 10:56
I had this Issue until I used version minecolonies-0.13.670.
Now it seems to be fixed. 
The builder still has some pathfinding issues where a block is in his way or they can't reach a level of the building without the ladders placed first, if this is happening the builder again goes in a infinity loop of doing nothing or jiggling around.
At one point the old behavior was persent, but I can't reproduce it and after some restarts it was gone.

**Comment by Powerminer11** [comment] 2021-03-04 13:23
Just updated. The issue is still around for me

**Comment by sshagent** [comment] 2021-03-04 17:48
i had this.  i updated, restarted the job, restarted him and then saw loads more requirements in the building hut.  In case that helps you Powermine11 (not sure which of the steps helped, but its definitely resolved for me now )

**Comment by Powerminer11** [comment] 2021-03-04 19:00
I have fired and rehired. Restarted the job and it didn't work. I have another builder who works just fine though. So its strange

**Closed as completed** 2021-03-05 19:16 UTC
Labels: Bug
