### ISSUE TITLE
Exception in Server Tick Loop

### ISSUE THREAD

**Issue by NielsPilgaard** [ldtteam/minecolonies#2524] opened 2018-06-10 20:22 UTC
### Minecolonies version

0.8.8518

### Expected behavior

- The player joins the game and the world loads

### Actual behaviour

- The world crashes

### Steps to reproduce the problem

I don't know unfortunately

Crashlog: https://pastebin.com/HT6vsE9W
Latestlog: https://pastebin.com/0smmqrg7
Original report: https://github.com/NillerMedDild/Enigmatica2/issues/41

**Comment by Raycoms** [comment] 2018-06-17 00:45
duplicate of https://github.com/ldtteam/minecolonies/issues/2525

**Closed as completed by Raycoms** 2018-06-17 00:45 UTC

**Comment by NielsPilgaard** [comment] 2018-06-17 06:33
That issue didn't exist when I opened mine. Thanks for looking into it regardless!
