### ISSUE TITLE
Crafters not leaving homes for work

### ISSUE THREAD

**Issue by taggianto** [ldtteam/minecolonies#5684] opened 2020-08-30 21:48 UTC
A number of the crafting citizens in my colony will not leave their homes to go to work. I've noticed it mainly with the Blacksmith and the Carpenter. They will stay in their homes, or leave to get food, but they will not go to their hut blocks to work unless I manually recall them to the workstation. In their gui it will show that they are "Working" even though they don't leave. I'm playing on the latest Beta, though I noticed this issue when I was playing on the latest Release as well.

**Comment by Raycoms** [comment] 2020-08-30 21:55
They should walk to their job as soon as there is an open task, did you check on this?

**Comment by taggianto** [comment] 2020-08-30 22:02
Hi! Yes, I checked. There was a request for a shield for one of my knights. The deliverymen had delivered the materials, but until I went to the blacksmith hut and manually recalled him, he didn't do anything.

**Comment by taggianto** [comment] 2020-08-30 22:24
I haven't been able to re-create the issue now though. Both my Carpenter and my Blacksmith have now started going to their hut once the materials are delivered.

**Comment by Raycoms** [comment] 2020-08-31 09:03
yeah, I'd love a reproduce

**Comment by taggianto** [comment] 2020-09-03 02:05
Haven't been able to reproduce it unfortunately. Closest I've gotten is my couriers refusing to deliver to my stone smelter, and the system stuck on thinking it needs over 200K cobblestone. Not sure if that's a separate issue though.

**Comment by BlueLadyAces** [comment] 2020-09-04 08:09
I suspect this may be related to an issue I've been seeing in my save (minecolonies-0.13.184-ALPHA-universal, so not the very latest alpha, but a recent one; playing a slightly modified version of the Craft to Exile pack). My miner's been going to one specific spot near my builder, and standing around there with his GUI showing that he's "Working" without moving or doing anything. The moment I recall him to his hut block he'll happily zip down into the mine. It doesn't seem to happen every day, and he's been standing at his hut block every time he's gotten sick, but it does happen somewhat frequently.

If it'll help I can send you a copy of my save (along with a list of the extra mods I added to the pack) - since it's been happening repeatedly with the same worker it might make it easier/possible to reproduce.

**Comment by Raycoms** [comment] 2020-09-04 08:11
@BlueLadyAces that is different, that means smething is blocking the miner from reaching the spot in the mine they want to go to

**Comment by LucidDreamer0322** [comment] 2020-09-25 19:04
made an observation yesterday.
Earlier into the mod progression i ran into very few bugs, builders hanging on torch placement, and visitors getting yeeted out of the world. Bit of an inconvenience, but not game breaking.
Now that i've progressed further, (have smith/sawmill), my builders are struggling in other ways as well, wont start building even with all materials (have to open the builders ai and force clear requests), not claiming a build request even though they didnt have one and many were available (fixed by clearing the request list and upgrading that builder), not showing up for work (recall them and punching them a few times seems to help, or at least makes me feel better xD).  Also my sawmill doesn't actually do a lot of requests ~80% of the time and my smith is on crack, (I have 6 guard towers, i think 2/3 of them are knight) taught my smith to make swords shields and armor thinking that would auto equip my guards, which it did. but while going through to try and sort the warehouse i found that i had about 60 shields, which means he just spammed shields until i had no iron left in the colony inventory xD

My verdict is that there seems to be a few issues with the request system, like maybe a loop thats causing memory drain which at first is barely noticeable, but eventually causes even bigger issues, like my town now barely functioning at all.  I used to spend my days running around and manually filling requests, now that i have the auto system set up, i spend my days running around punching my villagers and trying to fix the auto system. Still having a blast though, I do indeed love this mod :)

**Comment by ravenbuilder934** [comment] 2020-09-25 19:06
The issue with the smith is probably related to #5395

**Comment by LucidDreamer0322** [comment] 2020-09-25 19:15
@ravenbuilder934

That is definitely what happened with the builder, but this bug stops them from working until/if all of those resources are present, I don't think thats what caused my smith to actually do the crafting of so many shields.  I think it was just that there was a request for shields, so he made one, but by the time the shields actually made it to my guards he filled that request a ridiculous number of times, because the request stays until the order is fulfilled. unless there is a trigger for the smith to acknowledge that he has already crafted one to fill it, it makes sense that he would continue making more in the meantime.

**Comment by Raycoms** [comment] 2020-09-26 08:57
Will close this until there is a reproduce for this. For other crafter related errors there are othe ropen issues already

**Closed as completed by Raycoms** 2020-09-26 08:57 UTC
Labels: Bug: Can't Reproduce
