### ISSUE TITLE
NPC remain stuck in front of the doors

### ISSUE THREAD

**Issue by Auriel1** [ldtteam/minecolonies#900] opened 2017-04-29 18:36 UTC
### Minecolonies version

version 1.10.2-0.6.112 or curse v0.7.4.2
with and without Malisis doors installed

### Expected behavior

- NPC can enter and go out by doors

### Actual behaviour

- NPC remain stuck in front of the doors

### Steps to reproduce the problem

1. Let the builder build
2. See what happen near a door
3. Watch him trying to cross without opening the door
4. Profit

**Comment by geldonyetich** [comment] 2017-04-29 22:33
I have noticed this issue too.  It is usually caused by one of three things when I encounter it:

1. The NPCs get in a fight over who can access the door.  There's a double door there, one opens the side of the door.  Another NPC immediately closes that door.  You can resolve this temporarily by actually walking up and opening the OTHER door, whereupon both NPCs will egress in a smooth manner.  (Possibly resolved by a check immediately before opening the door to see if the door is already open?)

2. The NPC actually has a need that is not being met but they are not broadcasting it.  Examples of these needs include:
* Miner needs to mine but does not have cobblestone needed to fill an empty spot.
* Builder needs dirt to build a foundation to fill an empty spot.
* The builder is unable to empty their inventory.
* One of the spaces of the inventory has a stack of cobblestone with a zero count on it.  That seems to get the NPC "stuck" until the player manually removes it.

3. A general pathing failure.  Behavior is very similar to a builder who gets stuck in a tree, unable to find a way back to their hut chest: they just kinda stand there.

Cases 2 and 3 can result in an NPC standing around doing nothing, often at a door.  Case 1 is a bit more noticeable because a door is opening and shutting.

It's possible the issue Auriel1 is encountering here is something else, though.

**Comment by Auriel1** [comment] 2017-04-30 13:57
Not with me, whether it is a simple or double door, he stays in front of without trying to open it, even if he is alone.
At the moment, the only thing that I found it is to open doors after their construction, and never to close them.
Furthermore, if I put a pressure plate in front of and behind doors, the NPC seems to think that the door is blocked, and do not approach it any more.

**Comment by geldonyetich** [comment] 2017-04-30 14:53
I have noticed pressure plates tend to prevent them from using the doors, yeah.  Sometimes they'll get on top of the pressure plates and spin around for a long time.  Works better when I remove the pressure plate.   But my NPCs generally do use the doors successfully without, so I wonder if it's a mod mix issue.

I do recommend (as a workaround) fiddling with the NPC's inventory a bit.  If it's a builder, try giving them a stack of cobblestone or dirt.  If you see a stack of either with a zero count, click on it to remove it.  If their inventory is full, try clearing it out a bit.  

Also, go back to the builder's hut and hit the "recall NPC" button, as that can force them to reset their pathing.  I have sometimes encountered a builder who seems comatose, resetting them to their builder hut resulted in them dumping the contents of the inventory into the builder hut chest so they can get back to work.

**Comment by Auriel1** [comment] 2017-04-30 15:10
Yes, sometimes they dance on the pressure plates.. ^^

But nothing to do with their inventory, whatever is their job or activity of the moment, they have never opened any door.

Yes I thought more of a conflict of mods, I imagine that I am not the only one to mix mods of NPC, I am finalizing a modpack of almost 250 mods.

For those who could interfere, I think in:
- MalisisDoors - malisisdoors-1.10.2-5.2.0.jar (already tested with and without this mod)
- Village Box - villagebox-1.10.2-0.6.0.jar
- Improved Villagers - iv-1.0.0.jar
- Minecraft Comes Alive (MCA) - MCA-1.10.2-5.2.3-universal.jar

**Comment by Raycoms** [comment] 2017-04-30 15:11
I guess it most be a door mod. Other vilagers mods won't interfere with our
citizen. (Only if coremod)

2017-04-30 12:10 GMT-03:00 Auriel1 <notifications@github.com>:

**Comment by Auriel1** [comment] 2017-04-30 15:16
OK, that's why I had thought at first of MalisisDoors, but it is not him ...
When and if I find I say it to you.

**Comment by marvin-bitterlich** [comment] 2017-04-30 19:38
MalisisDoors was a problem before if I recall correctly. But only updating the display state was.

**Comment by marvin-bitterlich** [comment] 2017-05-10 11:06
closing for now

**Closed as completed by marvin-bitterlich** 2017-05-10 11:06 UTC
