### ISSUE TITLE
Feature Request: Colonists should close doors behind them when passing through

### ISSUE THREAD

**Issue by GrifVindh** [ldtteam/minecolonies#3854] opened 2019-09-15 15:06 UTC
(I don't consider this a bug, because it's not directly related to structures built within minecolonies, which appears to be working as intended. So I'm presenting it as a feature request.)

Version: 1.12.2-0.10.357-ALPHA-universal

I created a dwelling inside the camp, and built my colony up around it. Eventually I tore down the camp (scavenging for materials) so that only my dwelling remains.

The delivery colonist frequently cuts through the first floor while making her deliveries. Unfortunately, she doesn't shut the door behind her, so I'll come back to a house with doors wide open.

This is mostly an aesthetic issue in a post-Town Hall world, but I notice that doors close behind colonists in the structures that get built within Minecolonies -- it's just the non-builder built structures where they display bad manners. :-)

So the request is for colonists to close all doors behind them as they're zooming around, even in structures built outside the builder tool.

**Comment by GrifVindh** [comment] 2019-09-16 00:15
I should note the workaround for this is to place a pressure plate on the interior side of each door, which causes the door to close automatically a few seconds after it opens. Of course I didn't think of it until I posted the feature request, and that's probably a lot simpler than mucking about with code.

**Comment by Raycoms** [comment] 2019-09-16 00:27
It's weird, colonists should respect all doors and open and close them

**Comment by GrifVindh** [comment] 2019-09-16 02:28
Oh. Well, maybe it _is_ a bug, then. :-)

**Comment by lunadragnstar** [comment] 2019-09-16 02:43
The only time I've run into this is when I opened the door and didn't close it, they only close doors they open.

**Comment by GrifVindh** [comment] 2019-09-16 14:08
@lunadragnstar that's the behavior I see for structures that have been built within the mod. For example, if I open the door to a warehouse and forget to close it, the deliveryman goes in and out without bothering with the doors at all -- until I close the door, then they'll open and close the doors themselves.

In this case, it's a structure I built myself that just happens to be in the colonist's way. So it opens the door on one side, crosses the room, then opens the door on the other side and goes on its merry way. The doors stay open -- at least they did till I put the pressure plates on the floor.

I was wondering if minecolony structures get tagged in some way that trigger the "close the door behind you, you savage" behavior, and since this was hand built it doesn't have that tag. Or... something like that. They're acting like there's a difference between a door built within minecolonies and a door placed outside it.

**Comment by Raycoms** [comment] 2019-09-16 15:12
No, we do nothing alike, do you have any door mod installed?

Am Mo., 16. Sept. 2019 um 11:08 Uhr schrieb GrifVindh <
notifications@github.com>:

**Comment by GrifVindh** [comment] 2019-09-17 10:17
I don't think I have any mods specifically focused on doors. Biomes O'Plenty adds a few new doors based on new trees it introduces, but it doesn't (as far as I know) alter how doors work.

Though it occurs to me I am running Minecraft Comes Alive, which modifies villager behavior. Could that be affecting colonists as well?

**Comment by Asherslab** [comment] 2019-09-17 10:40
nah MCA won't affect citizens. unless they're doing some really nuts coremodding.

**Comment by GanthorPrime** [comment] 2019-09-18 05:48
Im using Minecolonies with Biomes O Plenty and i can confirm minecolonies citizens open / close BOP doors as spected.  Im using Rustic that adds some doors too and that also work.

**Comment by GrifVindh** [comment] 2019-09-18 11:37
OK, so it's just me. Well, I've managed to work around it by using pressure plates, so I'll live. It's a fantastic mod.

**Comment by Raycoms** [comment] 2019-09-18 11:48
I am currently moving, I will check these days if I can reproduce this.

Am Mi., 18. Sept. 2019 um 08:37 Uhr schrieb GrifVindh <
notifications@github.com>:

**Comment by Raycoms** [comment] 2019-10-03 07:47
Can't reproduce

**Closed as completed by Raycoms** 2019-10-03 07:47 UTC
