### ISSUE TITLE
[2669] can't open npc inventory

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#569] opened 2017-02-09 05:14 UTC
While connected to dedicated server, when trying to access the inventory on an npc, in this case the builder, I can't, and the following enters the servers console:

https://gist.github.com/kreezxil/5095283607d1593c6aa85ecb63fb9d5e

**Comment by Raycoms** [comment] 2017-02-09 11:14
I checked the code it's strange, the citizen seems to be null, does this always happen?
How can I reproduce it?

**Comment by kreezxil** [comment] 2017-02-09 12:47
I'm not sure what happened, I can access the Forrester. Just not the builder. It might have been some kind of start error. I'll check again in a few hours when I do another run of my test server.

-----Original Message-----

**Comment by Raycoms** [comment] 2017-02-09 12:50
This crash only occurs when the entity is null.
But I can't figure out how an entity might be null if you can right click
it.
I guess minecraft did something very very bad to that builder.

2017-02-09 10:47 GMT-02:00 kreezxil <notifications@github.com>:

**Comment by kreezxil** [comment] 2017-02-11 13:14
Would like to point out that build 2735 doesn't have this issue, or the entity is no longer null for some reason.

**Comment by marvin-bitterlich** [comment] 2017-05-10 09:18
closing as solves

**Closed as completed by marvin-bitterlich** 2017-05-10 09:18 UTC
Labels: Bug
