### ISSUE TITLE
Citizens getting stuck on rails

### ISSUE THREAD

**Issue by Lightshardz** [ldtteam/minecolonies#6542] opened 2021-02-14 05:46 UTC
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.610-ALPHA
- Structurize Version: 0.13.113-ALPHA
- Related Mods and their Versions: Valhelsia 3 v3.1.8a modpack
- Minecolonies Style: Fortress

## Expected behavior

Citizens moving around town as normal, using Rails when available in their pathfinding.

## Actual behavior

Citizens are constantly getting stuck on Rails, trying to get on and off minecarts or just stuck where a rail ends to grass or grass path. Sometimes they get stuck being on their minecart in the grass off the tracks, but mostly they are stuck getting on and off the minecart at the end, but still "on" the rails. This tends to appear mostly when there is a "doorway" or a 1-block wide area they can stand on in the inner parapets, like the warehouse back door entrance, or a citizenAlternate building on an edge where the doorway entrance to the "Shed" is near the exit.

![image](https://user-images.githubusercontent.com/77556352/107869480-902f5600-6e5c-11eb-95f9-8e8e77df5882.png)
![image](https://user-images.githubusercontent.com/77556352/107869487-a210f900-6e5c-11eb-835e-6eddafc1f0b2.png)
I could not get a good program to record a video. If need be, I can record on my phone and send separately in a DM/Email request.

## Steps to reproduce the issue

1.  Build a Fortress Style colony, level 3-5 buildings.
2.  Research Rails at the University
3.  Watch citizens "exiting" inner parapet walls. Most of the time they work.

### Logs

- latest.log: 
- crashlog: 
- * Do not have crashes related to this issue. If necessary, can send separately.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment] 2021-02-14 08:32
I am seeing this a LOT, my interim fix was to remove rails from my fortress buildings

**Comment by Sylfa** [comment] 2021-02-14 17:44
The bug appeared in one of the versions after 0.13.566.

My partner built a colony and manually added tracks with booster rails which the citizens used in that version, the worst they did then was get in a minecart when crossing a track. But then yesterday we upgraded to 0.13.610 and after this many of the citizens would get stuck in a loop, from what it seemed to me the following happened every time:

1. Citizen is standing still/moving slowly in the blockspace next to the track
2. They get into a minecart and quite slowly start moving towards the next track block
3. As soon as they enter that track they abort and hop back into the blockspace they were at step 1
4. Goto 1

Due to the booster tracks it was fairly easy to see that it was when they just entered that block, or just before they were about to enter that track, that they dismounted.

Removing the track they were entering at step 3 would sometimes cause the citizen to slowly slide through the now trackless block until the cart times out, in most cases they would then return to position 1 and continue doing this. In some cases removing the booster rail did not change the sequence at all and they dismounted just before they entered the now trackless position 3.

At least once the citizen was ill and trying to path to the hospital that was halfway across the colony from their position, ie they were not near the destination and going through the rails would have been the fastest option, but they started moving in the opposite direction of the hospital while on the rail.

This was with minecraft 1.16.4, forge 35.1.36, no optifine

**Comment by Raycoms** [comment] 2021-02-15 11:28
I can't reproduce this in the latest unless in certain corner cases:
a) At entry/exit there is less than 3 block space -> valid behaviour, there should be enough space to enter the cart
b) the track starts with a slope -> also valid

Can you give me ways to easily reproduce this in other cases than the above?

**Comment by uecasm** [comment] 2021-02-15 11:48
When you say "at least 3 block space", do you mean along the track or beside the track?

Because fortress buildings have a 1-wide rail corridor only, and the track is usually not extended outside the boundaries of the building.  The entry/exit points within buildings are usually only 1-wide, rarely more than 2-wide.

**Comment by Moobien** [comment] 2021-02-15 12:05
test it in a fortress style Ray, I had to rip all my fortress rails up because of it, the guard towers are a good example, rails end 2 blocks either side of the doors

**Comment by Raycoms** [comment] 2021-02-15 12:12
Three high, not three wide.

**Comment by Raycoms** [comment] 2021-02-15 12:13
> test it in a fortress style Ray, I had to rip all my fortress rails up because of it, the guard towers are a good example, rails end 2 blocks either side of the doors

Yes, that is then a schematic issue to be fixed #5006

**Comment by Lightshardz** [comment] 2021-02-15 13:49
@Raycoms I will list below the specific buildings I have noticed it on to give a better example. All buildings are on completely level terrain, as thats how the fortress style is obviously laid out since they "link" together. All buildings are lined up to the chunk borders as recommended.
Fortress Warehouse level 3+, specifically without a building to the right (side closest to interior stairs). - There is an iron door in the back that allows the couriers in and out the rail system, but it is close to the edge of the building)
Fortress CitizenAlternate level 4+ (the one with the straight rails not corner), specifically without a building to the right (side closest to the outside shed) - There is a path through the shed to the rail system. I have seen no issue with the houses in the middle of the row, only when exiting the one side, and only from the citizens living in that house.
Fortress Guard Tower level 3+, specifically the half-chunk ones with the straight rails; I have not yet tested the corner variant, and no building on the side (either) - These have the doors on either side for barbarian security. 

* There are still a number of other buildings I have not yet made. Most of these issues all involve the citizen getting on the cart from the side that has that entryway, then progressing a half or most of a block (as Sylfa explained above), then dismounting but ending up back at the beginning of that block or right before it, where they had initiated the minecart. Very specifically, this occurs with the same citizens each time, with other citizens being able to pass them without issue, however those other citizens are using different paths and are not originating from the side doors. For example, the only people getting stuck at my warehouse are the couriers. The only ones getting stuck at the specific citizen house are citizens that live there and are heading that direction for work. The guards from the specific guard towers. 

** I have another player close friend of mine on our server as well report these issues. He has an Acacia style open colony without a lot of pre-planning, but mostly in a grid pattern with some adjustments in elevation. He has a good 12-16 blocks between most of his buildings and has manually built "roads". He has since manually added a rail system on the side of these roads (just a couple wide polished Blackstone i believe), and he has pointed out 2 specific areas that they were getting stuck doing the above. In his instance, they were at a rail intersection, so he pulled up the rails making the intersection and gave them 5 blocks distant. He said that helped, but on one side they continued having the issue. He pulled out 4 rails off the end of that one side and has fixed his issue. 

*** In the case of my citizens that were doing this repeatedly, they would not break this cycle, even to return to beds at night. I could watch them performing this loop all through the night and into the next day. If I recalled them to the town hall, they would be fixed until they ran into that specific pathing location either the same or next minecraft day and would get stuck again. I was not able to observe them getting sick like Sylfa mentioned above. I was able to rip up only the 4-5 rails in these spots (all of them in regards to guard towers) and it alleviated the issue for those citizens. I would still have the occasional issue where a citizen gets "stuck" in a minecart on non rail blocks, but they seem to time out of the minecart after so many ticks and continue on their way.

**Comment by Sylfa** [comment] 2021-02-15 17:44
@Lightshardz I believe the citizen in question _was_ sick and were heading to the hospital when they ran into the bug, rather than getting sick while doing it. I mentioned it mostly in case moving slower was more likely to trigger the bug, and to highlight that their destination was not close by.

@Raycoms in the build I mentioned there was nothing but sky above the tracks, and both sides of the track was clear as well, they were pathing into the track and slowly started moving on the cart. The tracks were on level ground, no slopes, but did change from regular rail to powered rails in the block next to the rail they mounted - not certain if that was a requirement for that to happen on open space though.

The problem occurs randomly, in this particular build there is plenty of open space so they path freely and rarely get into the same problematic spots, and that's assuming the spot always has the problem or if it's a combination of variables such as position inside a block when mounting the rail or such.

**Comment by Sylfa** [comment] 2021-02-15 19:44
Managed to recreate the issue with a small test world, here's a zip file of the world (not used that site before, hope it behaves): https://we.tl/t-xPAPkG58LF
Sadly the bug resolves itself when the game reloads, here's a demonstration though: https://youtu.be/XFBZRooVV4U

To recreate it with the downloaded world, give the builder the items she asks for, then once she has entered the work site, take the items off of her. Repeat until she bugs out. 
The bug happens fairly consistently when she tries to cross from the build site to the builders hut. I.e., when she tries to cross the tracks. You will note that there's plenty of space for them to move about, and the only thing really special is that there are 2 tracks with a block space apart, and she needs to cross both tracks to get to/from work.

The bug does happen in other locations as well, and the video I recorded shows another NPC being stuck right next to her for instance. But it seems to trigger more often when they move across the tracks rather than along them. Many times they will start sliding along the track, presumably because they are not moving perfectly across the track, and this appears to cause them to abort the movement, only to retry the exact same thing again.

Side note - it would make sense if they didn't sit down in a minecart unless the path goes along the track for a minimum distance, say 3+ blocks. This might not fix the issue with the pathing though, only hide it since it appears to happen even when they are intentionally moving along the tracks as well.

Here's the versions I'm using, no optifine was used:
LWJGL 3.2.2
Minecraft 1.16.4
Forge 35.1.37

ftb-backups-2.1.1.6
ftb-chunks-1604.2.2.58
ftb-gui-library-1604.1.1.26
ftb-janitor-1604.1.0.18
ftb-ranks-1604.1.1.9
ftb-teams-1604.1.0.13
ftbessentials-1603.1.0.11
jei-1.16.4-7.6.1.65
jeiintegration_1.16.4-6.1.1.11
JustEnoughProfessions-1.16.3-1.1
JustEnoughResources-1.16.4-0.12.0.104
minecolonies-0.13.615-ALPHA-universal
structurize-0.13.113-ALPHA-universal

**Comment by chrysillis** [comment] 2021-02-16 20:10
I'm also facing this issue on the warehouse with fortress style level 3. I even made sure there are rails leading to the warehouse and from the warehouse, but the couriers continuously get stuck on the rails every single time they try to use them to go to the warehouse entrance. I even tried removing the rails and replacing the rails.

I'm using Minecolonies 0.13.610-ALPHA and Structurize 0.13.113-ALPHA.

**Closed as completed** 2021-02-17 12:08 UTC
Labels: Bug, System: Pathfinding
