### ISSUE TITLE
Resources disappearing from builder

### ISSUE THREAD

**Issue by fisher0065** [ldtteam/minecolonies#4077] opened 2019-11-14 22:41 UTC
### Minecolonies version

Version: minecolonies-0.10.493-RELEASE-universal

### Expected behavior

When using the builder menu to add resources for a build (clicking the "up" arrow for each thing in the list), everything was filled out and showing black (as in fulfilled), but when I came back a few minutes later, most of it was missing again, and the builder was requesting resources.  

More of a related question, but where do resources get stored when you upload them like that?  I checked the builder hut, the builder herself, and the in-progress building, and couldn't find anything.

### Actual behaviour

When adding resources for a build, they don't disappear.  Note this is before I have production facilities/warehouse/deliverymen, this is all related to delivering resources by hand to the builder.

### Steps to reproduce the problem

1. Gather all necessary building materials
2. "Upload" them to the builder through the build menu
3. wait a few minutes, and the builder will request already uploaded resources that I can't find.
4. ... Profit

**Comment by hotluck** [comment] 2019-11-26 02:09
I have come across the same problem with the same version. I fulfill the resources needed and then a few minutes later, half of them are being requested again. I have had it happen at least 3 times on each building and am going through more resources than is actually needed. The resources have gone from both mine and the builder's hut inventory. They are also not in the builder's inventory.

**Comment by Raycoms** [comment] 2019-12-01 22:55
I'm checking into this, but I couldn't reproduce this yet

**Comment by hotluck** [comment] 2019-12-02 07:28
I'm using medieval oak if that helps :)

**Comment by fisher0065** [comment] 2019-12-03 14:55
I am using medieval oak too.  I can't be certain, but for me, it only seemed to happen at building level 1.  Other than the building object (the bench or whatever), is there any other storage containers at level 1?  Maybe that is contributing to the problem.

**Comment by hotluck** [comment] 2019-12-04 09:19
I am using medieval birch. Maybe the medieval buildings are haunted lol

**Comment by Raycoms** [comment] 2019-12-04 09:20
I tried medieval oak, dark oak and spruce already without problems

**Comment by hotluck** [comment] 2019-12-05 23:56
I installed the latest alpha (574) and it is still happening, but very random. I tried not adding the resources that way and waiting to fulfill a builder's request but when you fulfill it, they request it again between 2 and 6 times!

**Comment by hotluck** [comment] 2019-12-19 08:20
Any news?

**Comment by gswvmware** [comment] 2019-12-24 08:58
Same for 0.10.569-ALPHA

**Comment by MatthiasMann** [comment] 2019-12-24 18:21
Also happens in minecolonies-0.10.602-ALPHA-universal when using the "Fulfill" button in the builder's personal menu - and with the 2nd page on the builder's hut block.

In addition the builder seems to build without having materials - eg it places the first layer of the medieval oak warehouse without me having given him any fences or stairs.

The builder in question in a stone one level 2 (with a dual rack, crafting table and a furnace in the hut).

The missing items are in no storage (I checked all warehouse/builder racks, hut blocks and personal inventories of the builder and the delivery man).

The issues did not happen in my first world of this mod pack - but then I started a new world in the same Minecraft instance and there all these issues show up. I also added the performant-1.14.4-1.4 mod at the same time.

Edit: This is single player - maybe it is related to the recent commit which added client side simulation to the builder hut to allow faster fulfillment of requests?

**Comment by jdm311** [comment] 2019-12-30 05:56
I noticed this too when I first started my colony and built the builder's hut and townhall medieval oak, but I think after upgrading the builder's hut it went away. Maybe the hut storage is passing the items to a non-existent chest and the items are vanishing into the Ether? Upgrading the builder's hut adds a chest which can store the fulfilled resources, so that may restore the broken link. Just guessing, tho....

**Comment by MatthiasMann** [comment] 2019-12-30 08:36
@jdm311 that's a good point. I'm currently building mostly 'nordic' and 'wooden' style buildings which mostly use racks instead of chests. And In noticed that lots of items which should have been returned to the ware house appear in other building like the composter (he had iron bars, logs and glass panes in it) or deliverman (he had glowstone, chests, stone bricks etc) hut.

And I gave my 'nordic' miner a stack of oak ladders which ~30 minutes later I couldn't find anywhere in his own inventory, hut or ware house (but I did not check all other hut's inventory this time, and he certainly did not build deep enough to use them all up).

**Comment by jdm311** [comment] 2020-01-07 16:10
@MatthiasMann I saw that a few times when I deposited armor items the blacksmith had made into a deliveryman's inventory, hoping he would take it to the warehouse. Instead, he dumped it off at another hut. Although, to be fair, it could be that a knight/ranger was assigned to that hut and they dropped these items when their inventory became full. I can't say I was paying close enough attention to know for sure. I've since stopped doing that and haven't noticed any other occurrences. I wonder if a deliveryman might do that when the warehouse is full? But in regards to the title issue, I only experienced it very early in the colony build before I had the warehouse and deliverymen. I think it might have been just with building builder hut level 1. It was clear that some resources given to the builder hut had disappeared because the builder didn't have it in his inventory, nor was it in the builder hut inventory, yet the builder still required them.

**Comment by MatthiasMann** [comment] 2020-01-08 18:25
I think items no longer disappear from the build with build 616 (but so far I haven't build a warehouse - only a builder level 1 plus a few other huts like miner, farm and lumberjack).

But what I still see is that the builder is often requesting the same items again after you fulfilled the request after a 1-2 second pause. You then have to cancel that 2nd request.

Also with the new dialog UI you need to do a lot extra clicking before you can fulfill a request. It would be good to also have the fulfill option in the dialog if you have the required items in your inventory.

**Comment by MatthiasMann** [comment] 2020-01-08 22:23
Ok - it is NOT fixed - once I upgraded my "wooden" builder to level 2 the items started disappearing again. This time no deliveryman or warehouse has been build so they can't have taken the item.

I fulfilled a request for 20 glass panes (for a level 2 wooden citizen hut) with 16 glass panes. One glass pane ended in the inventory of the builder (who at that time was standing directly next to his hut block) and the other 15 are gone (I checked the builder hit block and all 4 racks - even the furnace).

**Comment by MatthiasMann** [comment] 2020-01-08 23:50
More info: I put all required materials in the rack next to the furnace in wooden builder level 2. Including nearly 2 stacks of oak stairs (the UI of builder reported all materials in black).

After building parts of the building 57 oak stairs were missing (oak stair were now red). So I think the material loss happens when the builder takes material out of it's rack.

**Comment by HelixCreations** [comment] 2020-01-18 08:49
I would like to add to this, I am using 631 version and it happens to my builder as well. Stuff just vanishes. Has anyone tried just putting it all in the builders inventory?

**Comment by Raycoms** [comment] 2020-01-18 08:50
In singleplayer or in multiplayer?

Am Sa., 18. Jan. 2020 um 06:49 Uhr schrieb Meathead01 <
notifications@github.com>:

**Comment by HelixCreations** [comment] 2020-01-18 08:52
This is on a multiplayer server, my own MP server using the mod pack  Enigmatica 4 version 0.3.7 It does not just happen to my own colonies but also my friends. I have uploaded the latest log in bugs114.

**Comment by hotluck** [comment] 2020-01-19 18:19
Since I first got this problem, I have tended to not use the builder hut requests until they are at least level 2 and then I haven't noticed the problem. What I have been doing a lot of though is fulfilling the builder's current request and I have found that 80% of the time when you have fulfilled his request, he will request it again. At first, I was re-fulfilling his request (and obviously using more than should have been necessary), but then I found that if I cancelled the second request, he would register that I had fulfilled it the first time and start building with it.

**Comment by HelixCreations** [comment] 2020-01-20 03:12
Yeah, that did not help me. I also noticed the delivery man will also take the items off the builder and put it in the stock house. Why takes his stuff he needs it? 

I am also still having the issue of items vanishing from just my builder.

**Comment by MatthiasMann** [comment] 2020-02-26 19:18
I just had this happening in minecolonies-1.12.2-0.10.719-ALPHA-universal in the following constellation:
I put 64 + 8 oak stairs in the builder's hut block's inventory.
The builder took 64 from it into his own inventory, the other 8 are gone.
But he still got the exclamation mark on his head and requested 64 oak stairs.
Canceling the request did not help as it reappeared directly again.
Then I removed the  4 oak stairs from his inventory and used the fulfill button in his request menu - that worked.
But the other 8 oak stairs are still lost.

So currently it looks like the builder can't handle more than 1 stack of any resource in any of his inventories.

**Closed as completed** 2020-03-25 18:08 UTC
