### ISSUE TITLE
Request system asks for thousands of items

### ISSUE THREAD

**Issue by Tenebranas** [ldtteam/minecolonies#5721] opened 2020-09-06 13:16 UTC
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.223
- Structurize Version: 0.13.64
- Related Mods and their Versions: forge ver. 31.2.36

## Expected behavior

Dyer requests only the amount of items required to craft the blocks/items requested by the builder.

## Actual behavior

Built a dyer, taught some recipies, dyer started requesting thousands of items.

![image](https://user-images.githubusercontent.com/13907081/92326584-0d31e600-f008-11ea-9ba4-956710bf695f.png)

## Steps to reproduce the issue

1.  Create dyer
2.  Teach dyer recipies (in my case light gray dye from oxeye daisies, light gray wool from light gray dye and white wool)
3.  Ask builder to build something that requires light gray wool
4. Request system borks itself

### Logs

- latest.log: https://gist.github.com/Tenebranas/2d829d0af0063aef8a545a725574cb52 

- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment] 2020-09-25 19:07
Duplicate of #5395

**Comment by ravenbuilder934** [comment] 2020-10-05 15:12
This issue is a duplicate of #5395.

**Comment by Raycoms** [comment] 2020-10-05 15:15
No. slightly different

**Closed as completed** 2020-10-11 10:14 UTC
Labels: Bug
