### ISSUE TITLE
To many civilians

### ISSUE THREAD

**Issue by RhyxMormarteno** [ldtteam/minecolonies#2221] opened 2018-02-13 19:43 UTC
### Minecolonies version

version 1.12.2-0.8.7508 or curse X.X.XX

### Expected behavior

- 14 housing slots
(4 taken by first 4 then 10 extra civs)

### Actual behaviour

- 14 civs and starting 4(18)
Build birch styled town and my first 4 civs dont want to be assigned to any house.

### Steps to reproduce the problem

1. install modpack All the mods 3
2. Upgrade minecolonies on server pack and client
3. Build birch villige about 20% chance to get this bug
4. Profit more civs for jobs but no hapopines as you need to constantly open their invs to give food with is dumped to their job chests

**Comment by MineShadow7** [comment] 2018-02-14 13:21
Since Townhall is now a house - this is not a bug. Can we close this?

**Closed as completed** 2018-02-14 13:21 UTC
